### ISSUE TITLE
5-1 black screen of doom after fight

### ISSUE THREAD

**Issue by Shukinen** [OmegaPrivateServer/issues#100]
## Summary
all the party went in the BC , did the  mission 5-2 fight  and when the CS was supposed to kick in, we got a black screen, only way to leave was to shut down windower, then use a warp item because we were stuck in qubia arena with no mobs no nothing, after a while on the 2nd atttemps it seems that the nms respawned but couldnt be attacked and no lvl sync

## Expected Behavior
CS after the fight and loose the new fei'yin seal and get to talk to halver

## Current Behavior
previouslay said

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/The_Ruins_of_Fei%27Yin?oldid=616243

## Characters
Shukinen
Snes - had alreeady done the mission
Alexzi
Vixen
Indora
Amia

## Context
https://www.youtube.com/watch?v=IPBC6amKKCA

**Comment by OmegaBison** [comment]
Unable to reproduce. Message me if you need the mission to be manually completed.
