### ISSUE TITLE
Blue Mage AF

### ISSUE THREAD

**Issue by tt127** [OmegaPrivateServer/issues#102]
## Summary
Cannot get the Blue Mage crafted Artifact armor(Hands, Legs, and most important of all, the Body). Doing the "Transformation" quest for the AF hat there was not a single cut scene and I finished it and got the hat. The cut scene at the "Imperial Whitegate" is supposed to open up the dialogue to craft the AF armor at npc "Lathuya" . But I seem to not be able to get any cut scenes related to anymore of the AF at any of the related NPCs.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Implemented. Changes will go live with the next patch.
