### ISSUE TITLE
Sanction Buff arent working

### ISSUE THREAD

**Issue by raventn** [OmegaPrivateServer/issues#103]
When the Astral Candescence is under Imperial control, you may choose to obtain one of the following effects with Sanction at the cost of 100 Imperial Standing credits:

Regen
The Regen enhancement is active at a progressively higher percentage of HP, active from 1 HP to an HP cap of up to 95% of the player's maximum HP. Regen is 1 HP/tick.
Refresh
The Refresh enhancement is active from 0 MP to an MP cap of up to 75% of the player's maximum MP. Refresh is 1 MP/tick. This does not appear to stack with Refresh, Refresh II, nor Refresh from gear.
Increased Meal Duration
The meal duration enhancement doubles the normal length of food eaten.

Also Imperial Standing Points amounting to 10% of the base Experience Points not sure if that works.

**Comment by OmegaBison** [comment]
Please re-submit this ticket with the correct template & explain which part(s) are broken, with an example of expected behaviour vs current behaviour.
