### ISSUE TITLE
Puppetmaster Report

### ISSUE THREAD

**Issue by ElectronicMan83** [OmegaPrivateServer/issues#104]
Here is what I can tell of puppetmaster so far 

==> Puppetmaster switch to ranged attack on all frame sometimes
--> seem to happen when it get stuck in tree / rock
--> When it does it start spamming WS/TP move; probably because of the ranged attack damage.
--> Happen mostly in solo situation. Rarely on Xp Party.
--> Puppetmaster should be C+ hand to hand. But I dont complain it help us in xp party.
--> Tank frame seem weak in xp party. It shouldnt die so quick when getting hate. 
--> Some attachment might not be available in game yet. 
The only big issue so far seem to be the **ranged attack bug > WS TP move spam > Tank frame squishy in xp party (** First time playing pup that high level, it might be normal )
**--> Forgot to add puppet Skillchain dont seem to work**.

**Comment by dakumauler** [comment]
The TP spam should be fixed when the mob TP spam gets fixed I would guess. As for the h2h Eden has it at a B ranking to stay on par with other classes and gives access to asuren fist WS which is needed.
