### ISSUE TITLE
Did Not Receive Shiva After Winning Mini Battle

### ISSUE THREAD

**Issue by JigokunoOusama** [OmegaPrivateServer/issues#105]
## Summary
I was fighting Shiva and beat her, during her cutscene I was disconnected. When I relogged, I was outside the crystal and had not received her as a summon. 

## Expected Behavior
I should have received Shiva as a summon. 

## Current Behavior
Shiva was not rewarded. 

## Characters
Euto

## Steps to Reproduce

1.  Enter crystal.
2.  Beat Shiva.
3.  Watch cutscene.

**Comment by Swerve256** [comment]
Should have been a GM ticket
