### ISSUE TITLE
Earthen Ward overwritting Stoneskin

### ISSUE THREAD

**Issue by Shukinen** [OmegaPrivateServer/issues#106]
## Summary
Earthen Ward is overwritting Stoneskin where it shouldnt

## Expected Behavior
it should gives trhe " Earthen Ward has no effect"

## Current Behavior
it wears off SS and then Earthen Ward applies

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Stoneskin (sadly the info isnt in the history on prior date)

## Characters
Shukinen

## Steps to Reproduce

1.cast SS
2. Smn cast Earthen Ward
3.
4.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
