### ISSUE TITLE
Sororo selling exclusive scrolls

### ISSUE THREAD

**Issue by NyanNyanSquad** [OmegaPrivateServer/issues#11]
NPC Sororo in Bastok Markets is selling an exclusive version of the scroll Dia, possibly Cure

## Expected Behavior
These scrolls should not be exclusive

## Current Behavior
Sororo gives you exclusive versions of the dia scroll

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
