### ISSUE TITLE
Carby mitts/light staff mp issues 

### ISSUE THREAD

**Issue by Jwter2** [OmegaPrivateServer/issues#111]
## Summary
 when equipping light staff with carby out and carby mitts equipped, carby cost 4mp per click, unequip light staff carby cost 2mo per click. This is the opposite of what is supposed to happen. 

## Expected Behavior
 when equip the light staff carby should cost less, not more. 

## Current Behavior
 carby cost more per click when equipping light staff. 

## Possible Solution & Detailed Description
 unknown 
 mp cost for carby should be at 0-2 per click with light staff equipped and carby mitts. 

## Characters
 Lowrider 

## Steps to Reproduce

1.
2.
3.
4.

## Context
 less mp cost with carby out

**Comment by Ashenbubs** [comment]
Light Staff and Dark Staff appear to be swapped with their avatar cost perps - Dark Staff gives Carbuncle less MP Perp whereas Light staff gives it more.

**Comment by Ashenbubs** [comment]
Seems all staves aren't working with Avatar Perp cost - Ice staff with Garuda/Shiva costs same per tick

**Comment by OmegaBison** [comment]
Just tested as level 75 SMN

No mitts, no light staff, carbuncle costs 8 MP/tick
No mitts, light staff, carbuncle costs 6 MP/tick
Mitts, no light staff, carbuncle costs 3 MP/tick
Mitts, light staff, carbuncle costs 1 MP/tick

Seems fine to me?
