### ISSUE TITLE
PROMIES BLACKSCREEN

### ISSUE THREAD

**Issue by Catfightx** [OmegaPrivateServer/issues#112]
## Summary
Sometimes when u teleport after killing the MR u dont teleport, but instead get stuck and Blackscreen. 

## Expected Behavior
When u teleport well u should teleport even if you got blackscreen, because ur PT teleports but the one stuck stays behind. After 4-5 times rezoning back . kill again get stuck. Thats painless.

## Possible Solution & Detailed Description
I think the CS has something to do with this. Dunno how the CS are triggered but Imo this has something to do with IP.
First happened, I had Main and Alt logged in. Got blackscreens.
We redid the run, but logged out Alt, logged it on my Laptor.
Everything went fine.

1- The CS doesnt had much to the story and can be part of the issue. I would simply desactivate it and insta teleport.
2- Keep the CS but save the Respawn point after the CS even if not triggered, so even if u have to Force DC u wont frustrate your teammates.

## Characters
Catfight / Cona

## Context
We were doing prommies. Had 2 DBs, and both DBs got the same problem. We just gave up.
Second time, just me DBing on different CPUs and the other DB just brought 1 toon.
We had no issues whatsoever the second time.

**Comment by OmegaBison** [comment]
Extended portal despawn to 10 minutes to mitigate this issue.
