### ISSUE TITLE
Lv60 MNK ability Footwork 

### ISSUE THREAD

**Issue by Ashenbubs** [OmegaPrivateServer/issues#116]
## Summary
The Lv60 MNK ability "Footwork" was added in June 2008 as found detailed in the wikia here:
https://ffxiclopedia.fandom.com/wiki/Footwork?limit=500&action=history

## Expected Behavior
Noticed WAR got Retaliation from a patch very close to this, checked MNK's ability dates and they seem a month or two apart.

## Current Behavior
MNK doesn't have access to Footwork

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Footwork?limit=500&action=history
https://ffxiclopedia.fandom.com/wiki/Footwork

## Possible Solution & Detailed Description
Add access to Footwork

## Characters
Ashenbubs

## Steps to Reproduce
MNK doesn't have access to Footwork at Lv60

1.
2.
3.
4.

## Context
I like to kick things a lot. I cannot kick things a lot. Punching things is okay though, but kicking things a lot is also fun.

**Comment by OmegaBison** [comment]
Implemented, will go live with the next patch.
