### ISSUE TITLE
I don't think blocks are acutally mitigating damage

### ISSUE THREAD

**Issue by mpinholster** [OmegaPrivateServer/issues#118]
## Summary

I don't think blocks are acutally mitigating damage
## Expected Behavior

I was fighting crabs in Qufm. When I would shield block, it hit for 19, 20, 20.  And regular hits without siheld blocks were 20-22 non crits.  Shield blocks should reduce damage by a good amount.
## Current Behavior

I was fighting crabs in Qufm. When I would shield block, it hit for 19, 20, 20.  And regular hits without siheld blocks were 20-22 non crits.
## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/Category%3AShields
## Possible Solution & Detailed Description
 Unsure how to fix

## Characters

I was on Kurma as WAR/MNK and had Yertle as a RDM/WHM
## Steps to Reproduce

1.
2.
3.
4.

**Comment by dvalderrama89** [comment]
Please provide additional information. What shield were you using and what is your shield skill level currently? What level is your character? What was your total defense at the time?

**Comment by OmegaBison** [comment]
Closing due to lack of followup.
