### ISSUE TITLE
NM Crystal Eater

### ISSUE THREAD

**Issue by Shukinen** [OmegaPrivateServer/issues#119]
## Summary
The NM will not Spawn upon Trading Crystals

## Expected Behavior
Every hours and 20 min we should be able to trade the Dampsoil roaming around  in the area 1 crystal to maybe spawn Crysal Eater NM

## Current Behavior
Currently, nothing happens and the crystals arent even taken from our inventory when trading to the dampsoil

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Crystal_Eater?oldid=299476

## Characters
Shukinen, Nanami, Nageki and Tenchu

## Context
Trying to get the Rapture Earring

**Comment by Sjshovan** [comment]
Below is my solution for this ticket.
**May require a table update which is provided in a migration.**

[NM Crystal Eater #119.zip](https://github.com/OmegaPrivateServer/issues/files/4288813/NM.Crystal.Eater.119.zip)

**Comment by OmegaBison** [comment]
Thanks @Ap0gee. Don't have access to my machine for testing right now but the changeset looks good. I've submitted a merge request to the Omega repo with your changes.
