### ISSUE TITLE
Level 80+ mobs 

### ISSUE THREAD

**Issue by raventn** [OmegaPrivateServer/issues#12]
## Expected Behavior

There is alot monster in Omega that is not adjusted to right levels.
Alot high level monsters still around 
## Possible Solution
Just change there level bases to monsters around.
Exampel:
Maze of Shakhrami 
**Crypterpillar around** 86-88 can be changed to same level as **Caterchipillar** level 29-31.
**Bleeder Leech** 80+ should be same as **Poison Leech** 24-28
**Warren Bat** 80+ can be same as **Ancient Bat** 26-29

Im sure there alot mobs that need be changed.

**Comment by OmegaBison** [comment]
This is a very broad task and it's very difficult for any one individual to track down everything OOE. We're going to need a handful of content/playtesting team members to tackle this effectively.

In the meantime, if there's anything that's exceptionally gamebreaking I can make one-off adjustments.

**Comment by raventn** [comment]
Here is a list of few area where some of them are popular exp place.
kinda need to be adjusted fact if server gets more popular. 
+ Hunting Af coffer chest when they guarded by 80 to 110+ monsters is big problem like Toraimarai Canal those frogs in there are true sight + true hearing.


Zeruhn Mines - Colliery Bats, Soot Crabs, Burrower Worms, and Veindigger Leeches
Inner Horutoto Ruins - Troika Bats, Goblin Trailblazers, Deathwatch Beetles, and Goblin Fleshers
Outer Horutoto Ruins - Fetor Bats, Thorn Bats, and Fuligo
Gusgen Mines - Madfly and Accursed Sorcerers
Dangruf Wadi - Fume Lizards, Goblin Brigands, Goblin Headsman, and Goblin Healers
 Korroloka Tunnel - Lacerators and Spool Leeches
Crawler's Nest - King Crawlers and Vespos
 Crawler's Nest - Dancing Jewels and Olid Funguars
Garlaige Citadel - Donjon Bats, Fortalice Bats, Warden Beetles, and Kabooms
Toraimarai Canal - Starborers, Deviling Bats, Plunderer Crabs, Blackwater Pugils, Sodden Bones, and Drowned Bones
Toraimarai Canal - Flume Toads and Poroggo Excavators
Labyrinth of Onzozo - Babaulas and Boribaba
Bostaunieux Oubliette - Blind Bats and Wurdalaks
Fei'Yin - Balayang, Wekufes, and Sentient Carafes
Kuftal Tunnel - Kuftal Delvers and Machairoduss

**Comment by OmegaBison** [comment]
https://github.com/OmegaPrivateServer/issues/issues/38

**Comment by dvalderrama89** [comment]
Fixed for the next patch. NMs have not been adjusted (yet). Please note that the mob names are client side and will still be the OOE name until we get a renamer fix in, but the levels and loot pools should now be accurate to era.

Also, there may still be OOE mobs excluding the list above. It's a large task to get full coverage so please consider this a first wave adjustment.
