### ISSUE TITLE
BLU Attack Bonus Trait Not Working

### ISSUE THREAD

**Issue by TheJapolian** [OmegaPrivateServer/issues#121]
## Summary
When setting the BLU spells Uppercut and Battledance it gives the trait Attack Bonus 1 and even shows it on my  trait list. But it DOES NOT give any +attack at all.

## Expected Behavior
Supposed to give +10 attack from the trait.

## Current Behavior
Currently it gives no additional attack from setting the spells. But it does show the trait in the trait list.

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Attack_Bonus

## Characters
Hap

## Steps to Reproduce

1. Set Battledance
2. Set Uppercut
3. Check Attack with them on
4. Check Attack with them off

**Comment by Sjshovan** [comment]
My solution for this ticket is below.
**Please have a look at the README within for more information.**

[BLU Attack Bonus Trait Not Working #121.zip](https://github.com/OmegaPrivateServer/issues/files/4290538/BLU.Attack.Bonus.Trait.Not.Working.121.zip)

**Comment by OmegaBison** [comment]
@Ap0gee nice catch, thank you! Merge request submitted to Omega repo.
