### ISSUE TITLE
San d'Oria Mission 2-3

### ISSUE THREAD

**Issue by steelwalker89** [OmegaPrivateServer/issues#122]
## Summary
Return to the Consulate in bastock and traded the Mythril Sand to Savae E Paleade and he would not take it.
## Current Behavior
no dialogue or anything.....would not take the trade, can not continues on to windhurst to finish up mission
## Characters
Arctic

## Steps to Reproduce

1.
2.
3.
4.

## Context
trying to do sandy rank mission 3 to con

**Comment by OmegaBison** [comment]
Leaving this here for debugging later since this is the 3rd player this has happened to.

`!checkvar Arctic MissionStatus` 3

**Comment by Sjshovan** [comment]
We need to ensure that these players talked to Grohm NPC which pushes status to 5, otherwise it remains at 3. Status must be 5 to trade the Mythril Sand.
