### ISSUE TITLE
Knight Stalker (DRG AF)

### ISSUE THREAD

**Issue by Vixen-Sim** [OmegaPrivateServer/issues#126]
## Summary
Clicking the ??? after doing all prerequisites does not spawn the two shadow NMs.  I think Rahal being bugged is the reasoning. He does no actions when trying to talk to him anymore. 

## Expected Behavior
Shadows should spawn. 

## Current Behavior
Shadows don’t spawn. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Unable to reproduce. I checked your character's progress and it should be working fine.

Please make sure you're clicking the ??? at F-9 between the Rumble Crawlers and Branding Irons, and make sure your wyvern is summoned when you click the ???, which is one of the requirements specified in the wiki details.

Also please provide character names & wiki links in future bug reports so we can investigate properly.
