### ISSUE TITLE
Mololo wrong time/OOE Items

### ISSUE THREAD

**Issue by FriskArt** [OmegaPrivateServer/issues#127]
## Expected Behavior
Guild NPCs are supposed to be 8:00-23:00 Vana diel time. 

## Current Behavior
Mololo and most Blacksmithing Guild Vendors are opening at 5AM instead of 8AM like theyre supposed to. Also sells the out of era item Niobium

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Mololo?oldid=726346

## Possible Solution & Detailed Description
Adjust the time as she says in-game her shop hours. Remove The out of era items.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Removed Niobium Ore.
