### ISSUE TITLE
Thunder Weather from Qufim does not proc "I can hear a rainbow" quest for SMN

### ISSUE THREAD

**Issue by mpinholster** [OmegaPrivateServer/issues#129]
## Summary

Thunder Weather from Qufim does not proc "I can hear a rainbow" quest for SMN
## Expected Behavior

Thunder weather in Qufim should make a cutscene occur for  SMN quests per FFXIClopedia *IF* we zone from Lower Delkfutt's Tower
https://ffxiclopedia.fandom.com/wiki/I_Can_Hear_a_Rainbow
The line:
To get the weather for Qufim Island, you must enter Qufim by exiting Lower Delkfutt's Tower.
## Current Behavior

I did not get Thunder Weather for quest from Qufim
## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/I_Can_Hear_a_Rainbow

## Characters

Yertle was on Taru RDM32/WHM16
## Steps to Reproduce

1.
2.
3.
4.

## Context
I was trying to unlock SMN

**Comment by dvalderrama89** [comment]
It seems like that wiki entry is about current retail, here is the 2008 entry that matches our server era: https://ffxiclopedia.fandom.com/wiki/I_Can_Hear_a_Rainbow?oldid=646746
Please note that Qufim is not included in the list of zones where you can obtain Thunder weather.
