### ISSUE TITLE
spell scroll npc's are listing out of era spells, and missing some important ones.

### ISSUE THREAD

**Issue by bungdup** [OmegaPrivateServer/issues#13]
certain spell npcs are selling out of era spells, and missing some in era spells

## Expected Behavior

hasim for example should sell all the bar and bar aga spells for rdm and whm, the 2006-07 era list of spells.

## Current Behavior

hasim is selling higher tier spells and missing most of the bar and bar aga spells, most of which are only obtainable through him.

Npcs in selbina, mhaura, rabao, and jeuno are selling out of era spells, idk if they work but they're listed for sale, Tya padolih in mhaura for example sells distract and frazzle, out of era rdm spells that lowers targets physical and magic evasion.

## Possible Solution
backdate the individual npc's wiki'pedias to 2007 for a reference, and delete the out of era spells and add the missing spells.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
cannot buy all important bar spells for rdm and whm. and possible use of overpowered out of era spells.

**Comment by OmegaBison** [comment]
Hasim's item list now reflects 2008 version: https://ffxiclopedia.fandom.com/wiki/Hasim?oldid=586982

Frazzle/Distract/Frazle II/Distract II were removed from Nilerouche, Mazuro-Oozuro, Tya_Padolih.

Changes will go live with the next patch.
