### ISSUE TITLE
Conquest 1st Place Items availability and workaround suggestion.

### ISSUE THREAD

**Issue by CosmicForge** [OmegaPrivateServer/issues#131]
## Summary

Currently SanDoria has a massive lead in conquest, which otherwise on a server where everyone starts with Outposts unlocked wouldn't be an issue.... until you factor in attempting to acquire First-place only items from each nation. 

## Expected Behavior

First place conquest items should be available for those respective nations. 

## Current Behavior

Since San Doria has a large population imbalance, other nations stand little chance in taking first overall in Conquest, thereby making those First-only items virtually unobtainable.

## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/Conquest_Points

## Possible Solution & Detailed Description

Two possible fixes for this issue.
1) Quick and Easy: Temporarily allow First place Conquest items to not require those respective nations to be in first place. I would suggest however that the ability to purchase them from other nations through their embassy be restricted, so that the items are only purchasable by their respective nation.

2) Longer term solution: Institute a weighted conquest similar to Eden's system that was put in while having this same issue. Those nations that are 2nd/3rd/Tied have an even more increased chance to win region control, giving them a higher chance at overall conquest winnings. I'm unsure as to the exact formula used to facilitate this "comeback" or "handicap" mechanic.

## Steps to Reproduce

1.
2.
3.
4.

## Context

In the current state, although technically working, the sheer imbalance of Sandy players makes it near impossible for other nations to win conquest each week, thereby restricting access to First Place nation items from entering the game and economy. A tweak or fix of some kind enabling those items to be purchasable by those respective nations, or a weighted conquest system would be a nice QoL change to allow these items to surface until the issue resolves later on.

**Comment by JigokunoOusama** [comment]
Even items which should be available for purchase by Sandy citizens when Sandy is in 1st place are missing from regional vendor.  Millicorn is a good example.

**Comment by zierk** [comment]
A solution will be announced in the next patch notes.
