### ISSUE TITLE
Blacksmithing NPC not allowing a trade to obtain Guild Items

### ISSUE THREAD

**Issue by Ashenbubs** [OmegaPrivateServer/issues#132]
## Summary
The Smithing NPC states I can receive up to 4081 guild points by trading an item (Bronze Mace) to her before the time limit is up, however, when I try to trade her any of the 38 maces I have, I get nothing in return...
![image](https://user-images.githubusercontent.com/61240482/75291598-71cee580-581a-11ea-9e01-1325b241ee08.png)

## Expected Behavior
The NPC should allow me to trade her the items to receive my daily points

## Current Behavior
NPC is not trading the item for points.

## Steps to Reproduce

1.  Reach 28 in Blacksmithing
2.  See the NPC Macuillie in North Sandoria
3.  When she asks for the daily item "Bronze Mace", trade her some
4.  She should accept the items and reward you with Guild POints

## Context

I have 38 Bronze Maces clogging up my inventory, unable to trade and the daily timed limit will pass, making the work null and void.

**Comment by dvalderrama89** [comment]
This is documented, but looks to be part of a retail update made in 2012:
https://www.bg-wiki.com/index.php?title=Category:Guild_Points&oldid=525354
https://ffxiclopedia.fandom.com/wiki/Guildworker%27s_Union?oldid=385879

In 2008 it seems like we were able to switch guilds at any time and trade items immediately, but any GP accumulated at the guild you had a contract with before the switch would then be lost.

**Comment by Ashenbubs** [comment]
This was a standard issue that is correct for in-game.  Not a bug.

If you rank up in a craft via test item trade-in, you **cannot** trade in items for GP for that day, you must wait for the following day.  This is with all guilds.
