### ISSUE TITLE
Moblin enemies not on pathway, are on floor instead

### ISSUE THREAD

**Issue by Ashenbubs** [OmegaPrivateServer/issues#134]
## Summary
Several moblins are spawning on the floor of the map, unclaimable, instead of above on the pathways they should be - This is in Oldton Movalpolos, have not checked Newton Movalpolos yet.

## Expected Behavior
Enemies are out of bounds, shouldn't be

## Current Behavior
Enemies are either spawning or leash issues causing them to walk off path and off to unaccessable areas.
Image attached:
![image](https://user-images.githubusercontent.com/61240482/75363539-308a1480-58b2-11ea-9973-b5a5cd5ecdf4.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Sjshovan** [comment]
This looks to be a visual bug as the enemy positions/distances do not change when they fall down. A player is likely able to attack and be attacked by the enemy in this state if they reach it while in combat. Currently unsure how to detect this.
