### ISSUE TITLE
Equipping Light Staff Increases Perpetuation Cost of Carbuncle Summon

### ISSUE THREAD

**Issue by JigokunoOusama** [OmegaPrivateServer/issues#135]
## Summary

When a light staff is equipped, Carbuncle's perpetuation cost increases by 2mp per tick.  This is the opposite effect it should be having.
## Expected Behavior

When a light staff is equipped, the perpetuation cost of the summon Carbuncle should be reduced by 2 per tick.
## Current Behavior

When a light staff is equipped, Carbuncle's perpetuation cost increases by 2mp per tick.
## Possible Solution & Detailed Description

The light staff should reduce the perpetuation cost of Carbuncle by 2mp per tick.  All elemental staves have this effect on their corresponding elemental summons.  Using a summon with an  opposing element to the currently equipped elemental staff will instead increase perpetuation cost by 2.  

## Characters

Narsel, Euto
## Steps to Reproduce

1. Equip light staff.
2. Summon Carbuncle.
3. Check mp cost.
4. Unequip light staff.
5. Check mp cost.

## Context

The light staff is used in combination with Carbuncle's Mitts to reduce perpetuation cost  of the Carbuncle summon significantly.   This allows a summoner to be active for a longer amount of time, instead of spending most of the time resting.

**Comment by dvalderrama89** [comment]
Reported to be fixed as of the last patch.
