### ISSUE TITLE
Could the global Conquest Rank requirement be removed from Conquest Items

### ISSUE THREAD

**Issue by mpinholster** [OmegaPrivateServer/issues#137]
## Summary

Certain items require a country to be in first place for certain items to be sold.
Example: Windy needs to be in first place for Combat Caster Axes to be sold 
## Expected Behavior

It is working as intended now. I just thought it would help with weapons and armor for certain jobs if this was changed. I have only seen Sandy in first place the last 4-5 weeks?
## Possible Solution & Detailed Description

Just removed Global Conquest Requirements or just change the items to be 2nd place instead of first (since it is always Sandy in first...and Bastok and WIndy combined to be in second)

## Characters

I was on Kurma
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
A solution will be announced in the next patch notes.
