### ISSUE TITLE
Eldieme Necro. - Wrong loot table - Tomb Warrior/Mage

### ISSUE THREAD

**Issue by Ashenbubs** [OmegaPrivateServer/issues#138]
## Summary
Tomb Warrior's are dropping a Chest Key rather than a Coffer Key.
![image](https://user-images.githubusercontent.com/61240482/76002552-b2a3ba00-5efe-11ea-9397-ac9b6c4498b1.png)

![image](https://user-images.githubusercontent.com/61240482/76002566-b9323180-5efe-11ea-8721-23231b1d5a59.png)

## Expected Behavior
Should drop Eldieme Coffer Key

## Current Behavior
Dropping Eldieme Chest Key

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Tomb_Warrior

## Possible Solution & Detailed Description
Change drop/loot tables for mob, possible check Tomb Mage also.

## Characters
Ashenbubs

## Steps to Reproduce
Farm Tomb Mages and Warriors for an hour then cry when you get the incorrect key finally :(

## Context
Farming Coffer Keys for AF.

**Comment by Ashenbubs** [comment]
![image](https://user-images.githubusercontent.com/61240482/87285881-fe3f2380-c4ef-11ea-852d-2e55e0304ff9.png)

Still seeing these drop Chest Keys.

**Comment by Ashenbubs** [comment]
https://ffxiclopedia.fandom.com/wiki/Eldieme_Coffer_Key?oldid=577596

Coffer Key drop list from June 2008 - along with drop rates:

![image](https://user-images.githubusercontent.com/61240482/87286185-71e13080-c4f0-11ea-9356-5c135e9b295e.png)

**Comment by zierk** [comment]
Tomb Warriors were dropping both chest and coffer keys. Mage's had a lower drop rate. Patch submitted to remove chest keys from warriors and increase mage drop rate of coffer key. Thank you for the report should go live next patch.
