### ISSUE TITLE
Friend stuck in upper Jueno

### ISSUE THREAD

**Issue by Sirlootzttv** [OmegaPrivateServer/issues#139]
## Summary

Rulien is stuck in Upper Jueno and cannot leave spot. If he teleports and goes back to Chocobo stables he gets teleported back to spot and is stuck.
## Expected Behavior

Be able to get unstuck and not get teleported back to spot when he gets out.
## Current Behavior

Rulien is stuck in spot and cannot move. When he gets unstuck and returns to Chocobo stables he is teleported back to the spot he was stuck at.
## Characters

Rulien
## Steps to Reproduce

1.
2.
3.
4.

## Context
We cant go to upper Jueno without him being teleported back to the spot he gets stuck at.

**Comment by OmegaBison** [comment]
Submit a GM ticket if this is still an issue: https://xi-omega.com/home
