### ISSUE TITLE
Enmity Issues

### ISSUE THREAD

**Issue by Jeffrow419** [OmegaPrivateServer/issues#140]
## Summary

Enmity Issue
## Current Behavior
 last night fighting a NM, friend used SAM 2hr and I couldn’t pull NM off him with Provoke, Flash, Sentinel and I even PLD 2hr and Cure 4 spam and never gained enough enmity back to pull NM off him.

## Possible Solution & Detailed Description

 Boost Enmity Gains on PLD and NIN from spells or job skills

## Characters

Jeffrow
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
I realize this was a while ago. Which NM were you fighting and how long was the fight?

**Comment by Jeffrow419** [comment]
> I realize this was a while ago. Which NM were you fighting and how long was the fight?

Yea this was a while back, was fighting KA and had SAM friend with me. Enmity seemed kinda clunky.  But over all at current state of server seems good.

**Comment by Thayos** [comment]
I would also like to second the Sentinel Enmity seems off, alone, it should have enmity close to that of provoke.  I have in a party where I pull a link with banish and sentinel and it not remain on me through a single cure II from healer.

**Comment by Thayos** [comment]
https://ffxiclopedia.fandom.com/wiki/Sentinel?oldid=589317

**Comment by zierk** [comment]
I'll take a peek at this. We did a balance pass on a lot of spells recently for enmity but haven't gotten to JAs or WS yet.

**Comment by zierk** [comment]
We made some changes already to Warcry/Rampart. Sentinel and Ninja enmity buffs coming soon.
