### ISSUE TITLE
5-1 bug

### ISSUE THREAD

**Issue by Godlylegato** [OmegaPrivateServer/issues#141]
## Summary
had a bug in 5-1 fight. not all of our group were in the same instance so after we won they didnt get the burnt seal and credit.  goodjuice,badjuice,dps,semin were the one's who didnt get credit
## Characters

Goodjuice, Badjuice, Dps, Semin
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Duplicate Ticket
