### ISSUE TITLE
spell lost on zone after use

### ISSUE THREAD

**Issue by oo7sk8punk** [OmegaPrivateServer/issues#142]
## Summary
bought absorb-acc from vendor in whitegate for 44,000g as normal, used it on the spot (1:09am pst mar10th), sorted spell list and verified the spell on the list...later after zoning i noticed the spell no longer on my list
## Expected Behavior
spell should be available as per mar 08 update https://ffxiclopedia.fandom.com/wiki/Absorb-ACC?oldid=463399

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Absorb-ACC?oldid=463399

## Possible Solution & Detailed Description

can has refund or spell added back to list?
## Characters
Retounen

## Steps to Reproduce

1.buy spell
2.use spell
3.zone
4.lose spell

**Comment by dvalderrama89** [comment]
This spell is likely marked as WOTG in the DB. According to the wiki it should be in our server era so all we have to do is update the tag to TOAU and you'll have it in your spell list without purchasing it again. We'll try to update it for the next patch.

**Comment by OmegaBison** [comment]
Resolved
