### ISSUE TITLE
BLU 2-Hour & /THF Sneak Attack & Trick Attack Not Working

### ISSUE THREAD

**Issue by TheJapolian** [OmegaPrivateServer/issues#145]
## Summary
Blue Mage 2-Hour ability does not work. When you pop your 2-hour the 2-hour symbol doesnt even show up on your status. Also, when playing sub THF. The abilities Sneak Attack and Trick Attack do not stack up on the BLU Physical Spells like they should. For example Sneak Attack + Jet Stream should stack and do extra damage but it does not. I know this because when you do it, your Sneak Attack status symbol is still their after you use the BLU Spell.

## Expected Behavior
2-Hour should give chain / burst affinity during the duration. Sneak & Trick attack should stack with BLU Physical Spells.

## Current Behavior
2 Hour does nothing. Using Sneak Attack and Trick Attack as subjob doesnt stack on BLU spells.

## Characters
Hap

## Steps to Reproduce
1.
2.
3.
4.

**Comment by dvalderrama89** [comment]
This should be resolved by Phase 1 from last patch. If there's any issues please submit another ticket.
