### ISSUE TITLE
Smoke on the mountain issue. 

### ISSUE THREAD

**Issue by plugin1003** [OmegaPrivateServer/issues#147]
## Expected Behavior
 Supposed to be 1 earth minute after trading meat to fire. 

## Current Behavior
 having to wait full game day. 

## Relevant Wiki Link
 https://ffxiclopedia.fandom.com/wiki/Smoke_on_the_Mountain?mobile-app=false

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
https://ffxiclopedia.fandom.com/wiki/Smoke_on_the_Mountain?oldid=424281

> Wait 1 full game day--approximately 58 minutes real-time--for the sausage to cook.
