### ISSUE TITLE
Bastok Dangruf Wadi and Gusgen map quests

### ISSUE THREAD

**Issue by Nageki-noki** [OmegaPrivateServer/issues#15]
## Expected Behavior

see below

## Current Behavior

When completing any of these quests,the npc will give you the map but not the 2k experience,which is the exact opposite of the king ranperre,s tomb map quest.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Fix has been implemented and will go live with the next patch.
