### ISSUE TITLE
Sabotender Bailarina NM Missing - Has no placeholder attachment

### ISSUE THREAD

**Issue by Ashenbubs** [OmegaPrivateServer/issues#150]
## Summary
Sabotender Bailarina has no placeholder in Quicksand Caves

## Expected Behavior
Placeholders should be in room/tunnel and aren't visable

## Current Behavior
No placeholders - The placeholder currently doesn't have a place to spawn.

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Sabotender_Bailarina

## Possible Solution & Detailed Description
Add drop table for NM and placeholder links.

## Characters
Ashenbubs

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
Confirmed no PH and additionally no loot. Fix is in progress.

**Comment by zierk** [comment]
Fixed.
