### ISSUE TITLE
megalobugard Placeholder issues

### ISSUE THREAD

**Issue by whiskeyhughes** [OmegaPrivateServer/issues#152]
## Summary
It appears that the placeholder isn’t spawning. I’ve been killing these mobs for three days and only have seen one pop when I first arrived

## Expected Behavior

https://ffxiclopedia.fandom.com/wiki/Megalobugard

Testimonials are saying that he is usually up every two hours.

## Current Behavior
Not spawning after days of killing all Bugards in the area.

## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/Megalobugard

## Possible Solution & Detailed Description
Double check that placeholders are popping correctly 

## Characters
AFK

## Steps to Reproduce

1. Social distancing
2. Kill Bugards
3. Get sad when NM doesn’t pop

## Context

My wife says I’m more tense than normal.

**Comment by Sjshovan** [comment]
@whiskeyhughes Hey there, it looks like there is one PH in the H-7 area. The Megalobugard spawns away from the PH in the G-8 area. Can you please confirm that you have been killing the PH in H-7?

**Comment by whiskeyhughes** [comment]
Yeah, I spent three days killing everything. Since the last reboot, I haven't. I am trying now.

**Comment by Sjshovan** [comment]
@whiskeyhughes ok cool, I will work on adding the other two PHs. Please report back what you find today! Thank you.

**Comment by Sjshovan** [comment]
I have added the additional PHs and ensured only one is up at a time. I have also verified that the PHs are spawning the NM.
PR available.

**Comment by whiskeyhughes** [comment]
Cant thank you enough! It has popped 2x since yesterday!!!
