### ISSUE TITLE
Ranger/Corsair missing Recycle trait

### ISSUE THREAD

**Issue by twigete** [OmegaPrivateServer/issues#155]
## Summary
trait missing for ranger level 20 corsair level 35

## Expected Behavior
Occasionally allows ranged attacks without consuming ammunition.

## Current Behavior
not in game

## Relevant Wiki Link
http://www.playonline.com/pcd/update/ff11us/20060725vNusN1/detail.html
patch update from  july 25,06
https://ffxiclopedia.fandom.com/wiki/Recycle

## Possible Solution & Detailed Description
add please

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
From what I can tell, recycle was a merit-only ability in 2008, as is mentioned in the playonline.com article that you linked. The RNG20 and COR35 versions weren't made available until later.

**Comment by twigete** [comment]
the merit trait (Proc rate increases by 5% per merit level) of the recycle trait so it can work more, so i ask you how can the merit work with out the having the trait before hand. and the post i sent you was from 2006 when corsair came out

**Comment by OmegaBison** [comment]
The post you linked was referencing merit points, not native level 25/35 traits. Can you find any source that says Recycle was available in August 2008?

**Comment by OmegaBison** [comment]
https://ffxiclopedia.fandom.com/wiki/Ranger?oldid=637952
https://ffxiclopedia.fandom.com/wiki/Corsair?oldid=625103

Recycle was not available in 2008.

**Comment by twigete** [comment]
that makes no seance how they can have a merit that increases a trait added in 2006 but not add the trait added

**Comment by MyriKennet** [comment]
meriting Recycle ADDS the Recycle trait, much like Meriting the group 2 Summoner merits that add avatar bloodpacts.  I'm assuming that's where the confusion is coming from.
