### ISSUE TITLE
Cant buy items from fishing guild NPC with guild points

### ISSUE THREAD

**Issue by eaponte23** [OmegaPrivateServer/issues#156]
## Summary

Go to Fennella in Port Windurst to purchase Robber Rigs (x2) and nothing gets added to my inventory. No guild points are taken from me either. It just doesn't allow me to buy them. I have over 15k in guild points it seems. Robber Rigs are just 1500?
## Current Behavior

Doesnt allow me to purchase.
## Characters

Gianna
## Steps to Reproduce

1.Go to Fennella in Port WIndurst
2.Choose Robber Rig
3.Input 2 in quantity
4.Press enter

**Comment by ghost** [comment]
Same issue for me as well. Character: Triss

**Comment by eaponte23** [comment]
Some players have told me that if you select the item under the one you want that you can purchase items. Not sure havent tried it myself.

**Comment by Balfury** [comment]
I am having the exact same issue.
