### ISSUE TITLE
Padfoot Bugged

### ISSUE THREAD

**Issue by Simseru** [OmegaPrivateServer/issues#157]
## Summary

Padfoot is not spawnining properly. For awhile now I have been killing 3/5 padfoots with no drops and the other 2 are no where to be found. Gave it multiple days of testing as maybe someone else had been killing but it was not despawning properly.

After server reboot i was the only one in the zone and killed the same 3 i have been killing and the same 2 were yet again missing.

## Expected Behavior

the below link has a map of the 5 spawn locations.
F7 works
G-H/7-8 Works
K9 works
I-8/9 has not spawned in a long time.
H-9/10 has not spawned in a long time.

## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/Padfoot

## Characters

Kongol
## Steps to Reproduce

1. Waste life in Lufaise
2.
3.
4.

**Comment by Simseru** [comment]
Was able to discern a strange spawn point for the H-9/10  spot but not the  I-8/9 still. 

Appreciate Pieplate reduce it to just 1 problem node. Will check again tomorrow.

**Comment by Sjshovan** [comment]
Thanks @OmegaSimseru, I will be looking into this!

**Comment by Sjshovan** [comment]
Need DB verification

**Comment by Sjshovan** [comment]
This looks to be working correctly
