### ISSUE TITLE
Water Lily not available at NPC

### ISSUE THREAD

**Issue by itssteved** [OmegaPrivateServer/issues#158]
## Summary

Cannot purchase Water Lily at the NPC
## Expected Behavior

Water Lily should be available for purchase
## Current Behavior

N/A cannot purchase from vendor
## Relevant Wiki Link

https://www.bg-wiki.com/bg/Water_Lily
## Possible Solution & Detailed Description

Add item to vendor
## Characters

itssteved
## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
OOE.

Please refer to Aug 2008 or earlier wiki entries.
