### ISSUE TITLE
Vuu Puqu the Beguiler Giddues

### ISSUE THREAD

**Issue by raventn** [OmegaPrivateServer/issues#16]
This nm is bugged in dsp even in Eden he never pop from PH beacsue ph is missing out
only time he is up when server reset even same problem in Nasomi. 

In retail in this area Giddues there suppose to be 2  Yagudo Piper around (H-14) but there is only 1.

## Expected Behavior
Lottery spawn of the Yagudo Piper either of those 2 piper in that place

## Current Behavior
there is only ´1 Yagudo Piper when it should be 2 basic 1 placeholder and 1 random piper..
either way one of them should always be Ph

## Possible Solution
add in the missing mob? or change nm to timed spawn?

**Comment by OmegaBison** [comment]
I just tested and was able to get Vuu Puqu to spawn. The 1 Yagudo Piper in that area is the placeholder. Spawn chance after PH kill is 5%. Cooldown after kill is 15 minutes. Vuu Puqu will not autospawn after server reboot.
