### ISSUE TITLE
Kirin de-claiming and turning white mid fight/resetting hate over and over

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#162]
## Summary

While fighting Kirin in an alliance, he constantly de-claiming turning white. This is resetting hate multiple times during the fight and causes issues.
## Expected Behavior

https://clips.twitch.tv/PoorSnappyTaroDoritosChip

## Steps to Reproduce

1.
2.
3.
4.

## Context

Impossible to maintain hate and causing a 100% hate reset.

**Comment by dvalderrama89** [comment]
Another example: https://clips.twitch.tv/TardyGentleOctopusSuperVinlin

**Comment by dvalderrama89** [comment]
This should be fixed with the last patch.
