### ISSUE TITLE
Weird Login Behavior: 

### ISSUE THREAD

**Issue by whiskeyhughes** [OmegaPrivateServer/issues#163]
## Summary
About once a week, I will get random D/Cs on one character for no reason when zoning, but today when I closed ashita and logged back in, I was at a different characters login screen. This was kind of alarming... 

## Expected Behavior
I should see my character (AFK) Not a random character I don't know. 

![image](https://user-images.githubusercontent.com/24579922/77242068-f8d06d00-6bd0-11ea-865a-b0f14dbb7edd.png)

**Comment by Swerve256** [comment]
DSP issue not a major issue as you cant access the character
