### ISSUE TITLE
Spell of Absorb Acc disapearing after purshcasing

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#165]
## Summary

Purchased Absord Acc twice and after using and zoning it disapears from spell list
## Expected Behavior

Spell was implemented in March 2008, Unsure if meets cut off
## Steps to Reproduce

1.  https://ffxiclopedia.fandom.com/wiki/Absorb-ACC?action=history
2.
3.
4.

**Comment by OmegaBison** [comment]
Resolved
