### ISSUE TITLE
Light Shot

### ISSUE THREAD

**Issue by TheKuguMan** [OmegaPrivateServer/issues#169]
## Summary
Some people think Light Shot is broken, but it still misses all the time.

## Expected Behavior
When you use Light Shot, the target is slept with a Light based sleep.

## Current Behavior
It works well, I hit prob 85% of the Light Shots I use with the rest being resisted or flat out missing with almost capped Agi. When unresisted  it last one min. When resisted but still lands, it last roughly 15 or 30 seconds, depending on how hard it was resisted.

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Quick_Draw?diff=664791&oldid=646850

## Possible Solution & Detailed Description
Check the accuracy to make sure it isn't broken, a lot of people think it shouldn't land as much as it does, but they never notice how many I miss.

## Characters
Tenchu

## Steps to Reproduce
1. Light shot a mob, check duration
2.Light shot a different mob, check duration
3. Light shot any mob you feel should resist it, and watch it get resisted
4. Check the files to make sure its properly coded

## Context
People think Light shot is busted on this server because they came from a broken server where it was supposedly abused. I wanna see my favorite fixed to be in era and not abused if it even is abuseable.

**Comment by Simseru** [comment]
Light Shot accuracy does need to be investigated. It hit an enraged Nidhogg tonight while all other spells were resisted.
![Indora_2020 03 29_013545](https://user-images.githubusercontent.com/59345270/77842280-77dc1d00-715e-11ea-8793-fec0d311dadf.png)
