### ISSUE TITLE
Player not visible after zoning until 50 yalms away

### ISSUE THREAD

**Issue by whandango1016** [OmegaPrivateServer/issues#17]
Player not visible after zoning until 50 yalms away

## Expected Behavior
Players should be visible after changing zones.

## Current Behavior
When you change zones, sometimes other players already within 50 yalms of this zone are not visible. You can run 50 yalms away from the player and then back again and they will be visible.

## Steps to Reproduce
1. join a party with someone
2. zone through the same zone as them
3. 50/50 chance that one of them is not visible to the other after zoning

**Comment by OmegaBison** [comment]
Bug confirmed.

**Comment by Sjshovan** [comment]
My solution for this ticket is below.
**Please have a look at the README within for more information.**

[Player not visible after zoning until 50 yalms away #17.zip](https://github.com/OmegaPrivateServer/issues/files/4296339/Player.not.visible.after.zoning.until.50.yalms.away.17.zip)

**Comment by Sjshovan** [comment]
This issue now has a PR available
