### ISSUE TITLE
Lost Items via Trade

### ISSUE THREAD

**Issue by Moldran** [OmegaPrivateServer/issues#170]
## Summary

Traded various elemental ores to linkshell mate and lost a number of them (6-8 light ore, 6 light beads, 16 dark ore, 8 earth ore)
## Expected Behavior

Everything traded should wind up in the other players inventory, otherwise it should say we cant trade at this time.
## Current Behavior

Trade went through, 6-8 light ore, 6 light beads, 16 dark ore, 8 earth ore were lost
## Possible Solution & Detailed Description

Please review the logs to see what was traded and what was actually received. Review logs to determine quantity of ore prior to trade and after trade to verify.
## Characters

Trade between Astrid and Supplechild beginning  13:00:36 and concluding at 13:01:01 in game 3/25/2020
## Steps to Reproduce

1. Fill trade window with partial and full stacks of items and trade people.
2. 
3.
4.

**Comment by Moldran** [comment]
Any chance i can get with someone in discord to review this within the next 2 weeks?

**Comment by OmegaBison** [comment]
Resolved
