### ISSUE TITLE
Antonia NPC in upper Jeuno 

### ISSUE THREAD

**Issue by Pieplate** [OmegaPrivateServer/issues#171]
## Summary

NPC selling our o era gear
## Expected Behavior

Should have items in list as per Wiki 
https://ffxiclopedia.fandom.com/wiki/Antonia?oldid=361159

## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/Antonia?oldid=361159

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Resolved
