### ISSUE TITLE
Mythril Swords Missing and Rogue Rig not catching Doubles ever.

### ISSUE THREAD

**Issue by PortlyRoy** [OmegaPrivateServer/issues#176]
## Summary
Edit: A mythril sword was caught but the catch rate seems extremely low - still no double catches with rogue rig.

No mythril swords are being caught at all in either Qufim or Sauromugue.  Have tested for 2 days of fishing and didn't catch one.  Qufim also didn't catch anything other than Rusty items, copper and silver rings, and black sole with Rogue Rig.  All fish should be catchable with Rogue Rig and there was exactly 0 double catches over a multi day period.

## Expected Behavior
Mythril Swords should be added to fishing pool in Qufim and Sauromugue.  Rogue Rig should catch double fish at a percentage and also be able to fish up all fish in the zone.

## Current Behavior
No Mythril Swords can be caught, Rogue Rig only catches 1 fish at a time always.  Some fish are not able to be caught with Rogue Rig, ie. 3 Eyed Fish, Gigant Squid in Qufim.

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Qufim_Island?oldid=702438
https://ffxiclopedia.fandom.com/wiki/Sauromugue_Champaign?oldid=748380

## Possible Solution & Detailed Description
Add mythril swords to fishing pool in these areas.
Check fishing pool for rogue rig in both areas to ensure all relevant fish can be caught.
Modify Rogue Rig for Double Catch percentage.

## Characters
Portly

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Mythril Sword confirmed to be fishable with Rogue Rig in Qufim and Sauromugue. If you're fishing in Qufim please make sure you're fishing in the right area.

I don't see any reference to Rogue Rig being able to catch multiple fish. Are you thinking of Sabiki?

Please submit a new bug ticket for Rogue Rig if you find references to it being able to catch multiple fish.
