### ISSUE TITLE
Sniper Ring unavailable 

### ISSUE THREAD

**Issue by boomcats** [OmegaPrivateServer/issues#179]
## Summary
Currently, due to R/EX version of archer and Royal Jelly BCNM being offline, we can't obtain sniper ring.  Staple FFXI item

## Expected Behavior
 Links to ways to obtain archer ring: Royal jelly or bust.  Change Shirakee Ring (r/ex) to be craftable into Snipers, or change it archers (or get RJ working)
 

## Current Behavior
>

## Relevant Wiki Link 

 https://ffxiclopedia.fandom.com/wiki/Archer%27s_Ring
https://ffxiclopedia.fandom.com/wiki/Sniper%27s_Ring

 

## Possible Solution & Detailed Description
Propose one of three things:
Make shirakee (r/ex) change to normal Archer
Allow Shirakee ring to be crafted (90 LW) into snipers
Get Royal Jelly working 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
I have re-coded this BCNM and have it mechanically working. It is being actively worked on and is nearing balance/play testing phase. If this does not make the next patch we will patch it to live when it is ready.

**Comment by zierk** [comment]
Looks like this made it just in time. :)
