### ISSUE TITLE
NPC Ecsa has incorrect name in West Ronfaure

### ISSUE THREAD

**Issue by whandango1016** [OmegaPrivateServer/issues#18]
NPC Ecsa has incorrect name in West Ronfaure

## Expected Behavior
NPC should be named "Ecsa".

## Current Behavior
Instead it is named "Yoshihiro, I.M."

## Steps to Reproduce
1. Go to the tower at F-6 in West Ronfaure
2. Look at the NPC
3. It has the wrong name.

## Additional
This could confuse some new players.

**Comment by OmegaBison** [comment]
Right now players can connect to Omega with any FFXI client version. We won't be able to fix NPC name mismatches unless we lock down the client version and make the omega client from the website required. Closing this ticket until we have a better plan for client version requirements.
