### ISSUE TITLE
You didn't catch anything. 

### ISSUE THREAD

**Issue by Jwter2** [OmegaPrivateServer/issues#181]
## Summary

When fishing, the message "You didn't catch anything" occurs far to often. 
## Expected Behavior

More fish should catch line. 
## Current Behavior

Catch fish 
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Possible Solution & Detailed Description

To have a better catch rate. I would say it's between 25-33% 
## Characters

Lowrider
## Steps to Reproduce

1.
2.
3.
4.

## Context
 fishing skill

**Comment by Exouds** [comment]
I'd Also like to Bump This post to get it fixed ASAP I've had multiple time where i get "failed to catch anything"  Anywhere from 4-11 times in  a row.

**Comment by Setz0r** [comment]
where were you trying to fish.

**Comment by Jwter2** [comment]
This happens in all zones.

**Comment by Setz0r** [comment]
are you targeting certain fish with correct bait?

**Comment by Jwter2** [comment]
Yes, I can go 11-12 fish in a row Hylcon Rod - Shrimp lure -Gold Carp. Was happening with insect paste - moat carp. Happens with Lushang- Cresent - Fly lure. These are just some examples
