### ISSUE TITLE
BARD Maat Fight Unbeatable

### ISSUE THREAD

**Issue by projekte84** [OmegaPrivateServer/issues#182]
## Summary
BRD Maat fight is impossible... Have tried 5+ times with 15 hi-poitions each time and different variations of 2 hour'ed songs and food and regens per all guides and after watching other Maat completion videos, he is hitting far too hard to be beaten.  Even for a Galka with almost 1300 HP.  Best I could get it was 43% and that was mostly luck and a vile elixir.

## Expected Behavior
Each Maat Hit is hitting for 130, 143, 106, 133, 143 with crits landing for 197-220.  That was with mostly capped skills, really good gear, and Black Curry Bun (+180 Def) with double 2 hour'ed Army's Paeon IV / III and a ulegerand range milk on.  After watching multiple videos from retail in 2006 and other servers, expected to hit for 60-90 a hit.

## Current Behavior
Hits way too hard every hit even with defense food to be sustainable. Impossible fight.

## Relevant Wiki Link 
https://www.youtube.com/watch?v=8iUsPVgUa_8

## Possible Solution & Detailed Description
Fix Maat's damage to be accurate for this era so Bard can be defeated.

## Characters
Projekte

## Steps to Reproduce

1. Use Black Curry Bun
2. Use 2 hour Soul Voice
3. Use both Paeon's + Ulegerand Milk
4. FIght Maat and get destroyed no matter what with capped skills.

## Context
Can not progress past 70 without leveling an entirely new job up to 68+... Urgent!

**Comment by dvalderrama89** [comment]
Please take a look at #120 because we have already investigated this and we were able to beat Maat on the 2nd try with the gear listed in that ticket plus food/meds.

If you provide a video of one of your runs it will help us determine if there is still an issue.

**Comment by projekte84** [comment]
I read your response on 120 and I disagree - it's still hitting way too hard and tried a double mambo run and it was even worse - he didn't miss that often and hit even harder 150 a hit... also you should not need a Joyeuse to beat maat - go watch that VIdeo I posted.  Just because you beat it with the best gear possible (cheesed it IMO) doesn't mean it's not broken.  If you're saying that it's never going to be fixed - I'll take that for what it is and go level something that isn't as broken and is easier to beat without camping a lvl 72-74 HNM ....................
