### ISSUE TITLE
Unable to fish up Monsters

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#185]
## Summary

Players fish 4-6 hours and day multiple times a week and never seen message stating a monster has bitten the line. 
## Expected Behavior

Messages displayed upon getting a bite will indicate the size and type of your potential catch as follows:
          
         **###  _****Monsters: "Something clamps onto your line ferociously!"
So still no "ferociously" message to indicate a monster****_**(does not display)

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Possible Solution & Detailed Description

Make monsters able to fixed up or implement another way to targets certain monsters that can only be fished up via other means
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Failgate** [comment]
Just to add a little clarity, it is currently impossible to fish up monsters while fishing.  I've been at it for a couple weeks now and have never had a monster catch the line while fishing in zones where monsters should otherwise be caught.
