### ISSUE TITLE
Cactrot Rapido

### ISSUE THREAD

**Issue by Pieplate** [OmegaPrivateServer/issues#187]
## Summary

Cactrot Rapido unable to claim
## Expected Behavior

Should be running around the zone and claimed by fighting other Cactors.
## Current Behavior

Just stands in one place running can fight it not getting  claim on it but able to fight and kill
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

## Context

We want the Nm to run around the zone like it should and should fight back for sure.

**Comment by dvalderrama89** [comment]
Resolved last patch
