### ISSUE TITLE
Dreamland Dynamis Bosses

### ISSUE THREAD

**Issue by Simseru** [OmegaPrivateServer/issues#189]
## Summary

Dreamland Dynamis Boss ??? are missing.
## Expected Behavior

??? should exist in each zone to trade the appropriate pop item to spawn boss NM.
Dynamis - Buburimu
Dynamis - Valkurm
Dynamis - Qufim
## Current Behavior

???'s are set to disabled and need to be toggled to visible.
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters

Kongol/Indora
## Steps to Reproduce

1.
2.
3.
4.

**Comment by dvalderrama89** [comment]
Check to make sure boss gives players KI

**Comment by dvalderrama89** [comment]
Resolved by last patch
