### ISSUE TITLE
None Era Weighted stones from garliage citadel

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#19]
Should not beable to pick up weighted pouch in this patch to opened banishing gate
## Expected Behavior

no ??? should be there on map
## Possible Solution

remove ??? from garliage citidal
## Steps to Reproduce

1.
2.
3.
4.https://ffxiclopedia.fandom.com/wiki/Pouch_of_weighted_stones

**Comment by whandango1016** [comment]
This was introduced in ToAU era IIRC? If so then it should probably stay (up to the way omega wants it i guess)?
It really is a pain requiring a whole team every time you want to get through to do a minor quest.

**Comment by OmegaBison** [comment]
Going to leave this as-is for now, after receiving feedback from the community. Might revisit this later.
