### ISSUE TITLE
Lullaby appears to not be getting calculated correctly

### ISSUE THREAD

**Issue by Failgate** [OmegaPrivateServer/issues#193]
## Summary
Bard Lullaby appears to not work correctly.

## Expected Behavior
Bard Lullaby to land reliably on XP mobs.

## Current Behavior
I believe that the formula for Lullaby is not being calculated correctly.  XP mobs are highly resistant to BRD sleep that should otherwise not be resistant.

## Relevant Wiki Link 
No relevant wiki link for this, I could not find a formula for it.  I do know that Singing skill and Wind/String skill should be getting applied.

## Possible Solution & Detailed Description
Check to see if the formula for the lullaby spell is being calculated correctly.  All song skills for BRD are at C, but singing should modify both Wind and String which to my understanding would bring them up to A.

## Characters
Hyral

## Steps to Reproduce
1. Level BRD
2. Get Lullaby
3. Cast Lullaby
4. Get Resisted
5. Probably die

## Context
It makes merit point parties particularly difficult since I can't reliably sleep mobs during pulls.

**Comment by dvalderrama89** [comment]
Also turn on Pianissimo while investigating this.

**Comment by Failgate** [comment]
Seems a majority of songs are having similar issues, I have +47 CHR and max merits on wind instrument and can't land any enfeebling songs on bosses.

**Comment by dvalderrama89** [comment]
Resolved by last patch
