### ISSUE TITLE
Tiamat Draw in not working properly

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#196]
## Summary

Whenever tiamat draws an alliance in, she pull them either under ground or into the walls
Possible it only occurs when she draws us in during flying phase
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dvalderrama89** [comment]
Fixed with the last patch.
