### ISSUE TITLE
Beastmaster missing the Snarl ability

### ISSUE THREAD

**Issue by Brimloch** [OmegaPrivateServer/issues#204]
## Summary
On Game update Nov.20, 2007 (JST)
http://www.playonline.com/pcd/update/ff11us/20071120wwnX41/detail.html?_ga=2.41875106.16107669.1587209267-956870398.1576096204

A new beastmaster pet command "Snarl" has been added.
Snarl (Level 45)
Transfer enmity to a pet invoked with the "Call Beast" ability.

## Expected Behavior
Upon leveling up to Beastmaster 45 ,  Beastmaster should have the Snarl Ability

## Current Behavior
At level 47 Beastmaster after using the Call Beast ability and having a jug pet out. there is currently no Snarl ability for Beastmaster. 
Using the syntax /pet "Snarl" < me > does not work because, Snarl is not available.
Pet command Snarl not in pet command menu.
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
Nov.  22, 2007 entry
https://ffxiclopedia.fandom.com/wiki/Snarl?direction=prev&oldid=381332

## Possible Solution & Detailed Description
Turn on the Snarl Beastmaster Ability to be used with Jug Pets through Call Beast ability
It is a (Pet Command) so once it is available you can access it through the Pet Command menu or using syntax /pet "Snarl" < me >

## Characters
Brimkade

## Steps to Reproduce
1. Level Beastmaster to 45
2.
3.
4.

## Context
Not having the ability does not allow Beastmaster to transfer Hate/Enmity to Jug Pet.
-- note* (Snarl cannot be used on charmed pets only on Call Beast - jug Pets.

**Comment by dvalderrama89** [comment]
Added in the last patch, but I've heard reports of the option to use Snarl not showing up in the menu sometimes. Please open an additional ticket with details and we can investigate.
