### ISSUE TITLE
Devil Manta

### ISSUE THREAD

**Issue by Anabeatrizbarros** [OmegaPrivateServer/issues#206]
## Summary

We are unable to fish up the "Devil Manta" NM after repeated tries. I know this might be hard to fix because it is a fishing issue. However, we do need a reasonable way to get Angel Skins.

## Expected Behavior

We should be able to fish up devil manta.

## Current Behavior

Cannot fish up devil manta and thus no real way to obtain angel skins.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Possible Solution & Detailed Description

1. Lower the cost of angel skins from Antiqix in Castle Oztroja--one angel skin is currently 7 L. Jadeshells. I'm not sure what a reasonable price might be, but something in line with the time it takes to fish up and kill devil manta?
2. Include Devil Manta as a possible lottery spawn until the fishing is fixed? 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dvalderrama89** [comment]
Resolved by last patch
