### ISSUE TITLE
Can't Charm the Nemans in Birds of a Feather BCNM 30

### ISSUE THREAD

**Issue by veliusiidx** [OmegaPrivateServer/issues#207]
https://ffxiclopedia.fandom.com/wiki/Birds_of_a_Feather/Strategies

According to this wikipage, the Nemans are charmable. When you use Gauge against them in combat, it says the Nemans are not charmable.

This fight is completely broken. Please fix it. There's even a YT video of a BST soloing it from 2007.

https://www.youtube.com/watch?v=vQ6w5IPeWZU
![Mei_2020 04 21_205320](https://user-images.githubusercontent.com/33435858/79903324-24828500-8413-11ea-8a27-72140a77f2ee.png)

**Comment by dvalderrama89** [comment]
Note to self: Fix script error in Neman.lua

**Comment by dvalderrama89** [comment]
Resolved in last patch
