### ISSUE TITLE
Sacrificial Chamber Key - ZM3 mission

### ISSUE THREAD

**Issue by Ssinz7965** [OmegaPrivateServer/issues#209]
## Summary

NPC  Jakoh Wahcondalo, didnt give Sacrificial Chamber Key and CS. Only the Trial of Daggers quest is being triggered.

## Expected Behavior

CS or Sacrificial Chamber Key KI so ZM4 bcnm fight can be done.

## Current Behavior

NPC  Jakoh Wahcondalo, didnt give Sacrificial Chamber Key and CS. Only the Trial of Daggers quest is being triggered.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Kazham%27s_Chieftainess?oldid=569096

## Characters

Blackkitty

## Steps to Reproduce

1.
2.
3.
4.

## Context
 Not able to proceed to ZM 4 Fight. I'm trying to get into ZM4 fight bcnm

need KI and/or CS

**Comment by Swerve256** [comment]
This works as expected and should have been a GM ticket
