### ISSUE TITLE
combat skill is capped until weapon unequipped or you zone

### ISSUE THREAD

**Issue by whandango1016** [OmegaPrivateServer/issues#21]
combat skill is capped until weapon unequipped or you zone

## Expected Behavior
Combat skills have caps that relate to levels.
I.e. a level 11 WAR with no merits in sword should cap at 34.

## Current Behavior
Today sword capped at 31 (went blue and received no further skillups) until i unequipped the weapon and re-equipped.

**Comment by zierk** [comment]
Has been fixed already.
