### ISSUE TITLE
Astral Flow damage is too high for BCNM60 Jungle Boogeyman

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#210]
## Summary

The SMN tonberry astral flows and from the research we've done it seems like the power of the move is about double where it should be.

## Expected Behavior

Astral flow should hit for maybe 60% of the targets HP in this bcnm (approximately 500-700)

## Current Behavior

Astral flow is hitting for 1200+ depending on the summon. Ifrit hit for 1700+

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://www.youtube.com/watch?v=SrWOmH7334Y
https://ffxiclopedia.fandom.com/wiki/Jungle_Boogymen

## Characters

Aeolus, Nanami, Hyral, Brb, Mileslong, Ashenbubs

**Comment by zierk** [comment]
Astral flow across the entire game is too strong.
