### ISSUE TITLE
BCNM40 Under Observation - mob INT stat is way too high, caster magic dmg too low

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#212]
## Summary

Magic damage setups via a combo of blm or nin/blm should be a viable strategy for this bcnm. Currently these setups are not possible because of the mob INT level

## Expected Behavior

Mob INT should be at a level where a NIN/BLM should between 70-120 dmg unresisted to the mobs depending on race and gear.

## Current Behavior

Currently the Compound Eyes have INT set to 91. A Taru BLM with best in slot gear is pushing around 80 INT. Since the magic dmg calculation factors in the enemies INT, the mob value seems too high by a significant amount.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://www.youtube.com/watch?v=vGX3dJMtgRo
https://ffxiclopedia.fandom.com/wiki/Under_Observation/Strategies

## Possible Solution & Detailed Description

Check to see how the BLM job and INT attribute in mob families is affecting mob base INT and see if any adjustments need to be made so that magic dmg vs hecteyes matches the video above.

## Characters

Aeolus, Hyral, Ashenbubs

**Comment by zierk** [comment]
A fix for this has been pushed and will apply in the next patch.
