### ISSUE TITLE
Sneak Attack dmg is low as sub THF

### ISSUE THREAD

**Issue by gm-bravura** [OmegaPrivateServer/issues#214]
## Summary
Ever since I got THF to 15, and subbed it on my WAR, the Sneak Attack critical are doing LESS damage than my regular auto attacks. I have screenshots to show this and it has never been different. Steve suggested submitting a ticket. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters
Katy

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
I think this is caused by a larger issue with how critical damage is calculated. I've made a small tweak, looks good on test server. Will continue to monitor after changes to live next patch.
