### ISSUE TITLE
Beastmaster pet mob respawn too long

### ISSUE THREAD

**Issue by gm-bravura** [OmegaPrivateServer/issues#215]
## Summary
Beastmaster pet mob respawn time was said to be made more retail accurate, but appears to be too long.
In retail of the era we are aiming for, a BLM lv51-60 could get solo chain5 by 1shotting the pets with Ancient Magic. That being said, the wiki chart for exp chains states that there is only a 90second window to kill a mob to get chain5. The bst pets now appear to be taking around 150seconds to repop which is almost a full minute over the retail mark, making it impossible to solo chain5 at BLM lv51-60 as you should.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Experience_Chain
Link above shows the exp chain timing chart at 90sec for chain5.

## Characters
Split/Habi

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
This was looked at, we lowered the amount of time it takes to respawn. Call Beast was already at a 90 second cooldown but the mob may not use it immediately. Hopefully this will enable solo chain 5s going forward. Fix goes live today.
