### ISSUE TITLE
Fishing rods breaking and guild points don't work.

### ISSUE THREAD

**Issue by gm-bravura** [OmegaPrivateServer/issues#218]
## Summary
Currently Some fish break Fishing Rod's That don't break on. As well As guild points rewards don't Work correctly can't buy some of them..(Fyi Example of fish that breaks rod, nibimonite breaking a hume fishing rod.)

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters
Jonee

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Monique75** [comment]
Hello, I also have an issue about the odd behavior on some fishes ; some of them may snap fishing rod lines whereas they shouldn't (ie.: Shining Trout on Halcyon/Fly Lure combo : lines snapped twice -- Great Blue/Wiki both say the combo isn't suppose to snap/break).
