### ISSUE TITLE
QoL - adjusted warp pricing, weighted stones, static open doors

### ISSUE THREAD

**Issue by radvic86** [OmegaPrivateServer/issues#22]
## Expected Behavior
from our limited sample in discord it seems some people approve the idea of reduced teleport fees.
weighted stones allow progress during an initial time of low server population.
static open doors will make the game feel more open, potentially easier to navigate for new ff11 players.

**Comment by OmegaBison** [comment]
HP and Outpost warps have been reduced to 10% of their normal costs. These will be adjusted back when we have a larger playerbase & more active economy.

The gil & CP values displayed by the client still show the non-reduced amount.

These changes will go live when the next patch is published.
