### ISSUE TITLE
Synth missing - Desynth Januwiyah -1

### ISSUE THREAD

**Issue by Ashenbubs** [OmegaPrivateServer/issues#220]
## Summary
Desynth recipe missing for Januwiyah -1

https://ffxiclopedia.fandom.com/wiki/Januwiyah_-1

## Expected Behavior
Recipe should be in-game.

## Current Behavior
Recipe currently not active within DB

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Januwiyah_-1

## Possible Solution & Detailed Description
Make the recipe live on server.

## Characters

Ashenbubs
## Steps to Reproduce

1. Get Lightning Crystal
2. Get Januwiyah -1
3. Attempt to desynth Januwiyah -1
4. ???
5. Profit

## Context

Recipe is missing, making it very hard to obtain Troll Bronze Ingot (Tr. Brz. Ingot) to use in high-level Blacksmithing.

**Comment by zierk** [comment]
Fixed. The recipe will be added next reboot.
