### ISSUE TITLE
Guild Points item "Goulash" seems to be out of era.

### ISSUE THREAD

**Issue by Raez138** [OmegaPrivateServer/issues#221]
## Summary
Cooking Guild Points NPC "Qhum Knaidjn" requesting "Goulash" item for today's GP. 

## Expected Behavior
NPC should not be requesting Goulash

## Current Behavior
NPC requests Goulash for GP, but when I try to synth I get the message "Synthesis canceled. That combination of materials cannot be synthesized."

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Possible Solution & Detailed Description
Please remove Goulash from the requested GP items.

## Characters
Raez

## Steps to Reproduce

1. Talk to NPC Qhum Knaidjn
2. Attempt to synth Goulash (fire crystal, couerl meat, mithran tomato, paprika, popoto, distilled water)

## Context
I will be able to receive my Chef's Hat after today's item turn in, but now I cannot. I spent gil on materials for the item before realizing it was out of era.

**Comment by zierk** [comment]
Closing this because we are aware that this item is OOE and uncraftable, have a fix planned.
