### ISSUE TITLE
Fishing causes aura and game crashes

### ISSUE THREAD

**Issue by RogerKoche** [OmegaPrivateServer/issues#224]
## Summary
Sometimes when I try to fish, I get an aura around me, and then the game crashes several seconds later.

## Expected Behavior
The game should not crash when fishing.

## Current Behavior
Use /fish. See explosion. Have aura. Game crashes soon after.
![fishingBug](https://user-images.githubusercontent.com/1971360/80922170-d3429180-8d40-11ea-8b98-187a4ec6d5af.png)

## Characters
Sekiro

## Steps to Reproduce
1. /fish (this previously occurred for me in Port Bastok, but is now occuring at the Knightwell). It will happen repeatedly if I log in and try to fish.

**Comment by OmegaBison** [comment]
This is a client problem caused when your character fishes without a fishing rod. Disable your lockstyle addon or equip your fishing rod before zoning.
