### ISSUE TITLE
Level 99 mobs in Dynamis-Tavnazia

### ISSUE THREAD

**Issue by Anabeatrizbarros** [OmegaPrivateServer/issues#225]
## Summary

Demons in Dynamis Tavnazia are level 99

## Expected Behavior

Demons should not be level 99 (I don't know the precise level, and I could not find the levels in wiki)

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Possible Solution & Detailed Description

Adjust Kindred demon levels

## Characters

Anabb/Anabeatriz

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Inprocess

**Comment by Swerve256** [comment]
Submitted for merge
