### ISSUE TITLE
Dynamis Qufim - Mega Boss Issue

### ISSUE THREAD

**Issue by whiskeyhughes** [OmegaPrivateServer/issues#226]
## Summary
When attempting to fight Antaeus, we were unable to use the Sea Monk Venom to stop the bosses Regen. The first time we did the fight, we were allowed to use the item but nothing happened. When we went back for another attempt, we got a message saying "You cannot attack this target" when attempting to use the Venom. We tried having multiple people use the Venom and everyone got the same message. The Auto Regen is huge, with a full on Zerg we were only able to get him to 40%, but he gains back 1% HP a second.  

## Expected Behavior
Regen should disappear if item is used. 

## Current Behavior
Can't use item on boss.

## Relevant Wiki Link 
https://ffxiclopedia.fandom.com/wiki/Scolopendra 

## Possible Solution & Detailed Description
Allow the item to be used on the mega boss

## Characters
AFK / BRB

## Steps to Reproduce
1. Go to Dynamis Qufim with the boys
2. Spend an hour killing Time Extensions and Bosses
3. Gather together at Megaboss
4. Spawn Megaboss
5. Attempt to use Sea Monk Venom
6. Get error that you can't attack target.

**Comment by dvalderrama89** [comment]
Fixed with the last patch.
