### ISSUE TITLE
Dynamis-Tavnazia Monster levels Incorrect

### ISSUE THREAD

**Issue by gm-bravura** [OmegaPrivateServer/issues#227]
## Summary
Dynamis-Tavnazia Monster level - Upon being the first people on the server to enter dyna-tav, we noticed that the mobs on the top floor were all level 99. They all checked IT++ and hit for 400+ making them un-killable without having multiple blm or smn and using a sleep nuke method. This is also an issue in the 3 dreamlands dynamis areas as some of the mobs there are also level 99. All of the mobs on the basement floor and first floor appeared to be the correct level, but the top floor was not correct for the era we are aiming for.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters
Split/Habi

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Ashenbubs** [comment]
Unsure if this will re-open the ticket correctly.

I went into Dynamis Tav earlier to check things out and get a few drops, I can confirm the top floor mobs have now changed correctly, all bar the Demon Dragoon mobs - They are still Lv97-100 - Might this mob just have been missed off the list of the other Demons on the top floor?

Can the same also be done to the Nightmare Leeches and Nightmare Clusters which are also on the top floor - As these are also checking as Lv97-100?

Thanks guys!
