### ISSUE TITLE
Random Character Warping: 

### ISSUE THREAD

**Issue by whiskeyhughes** [OmegaPrivateServer/issues#228]
## Summary
Was fighting mobs in Tandjana Isle in Bhaf Thickets, and both characters got warped to Mamool Staging Point. I noticed that each character warped when a Mog Tablet was discovered. 

## Context
Spent 20 minutes running to this spot to farm, then got warped randomly. Not a huge deal, just very random. 
![warp](https://user-images.githubusercontent.com/24579922/81209056-fb7afc00-8f9d-11ea-9f88-97cafa189731.PNG)

**Comment by whiskeyhughes** [comment]
In the picture you can see I was killing a Wivre which is only on the other island and now my character is at the Staging Point,

**Comment by zierk** [comment]
Have you experienced this issue since may?
