### ISSUE TITLE
Hydra HNM only dropping water crystals

### ISSUE THREAD

**Issue by CosmicForge** [OmegaPrivateServer/issues#229]
## Summary

Hydra's loot pool seems to be only water crystals at this time.

## Expected Behavior

Hydra should have the following loot pool according to the wiki page. Some items in multiples.
Berserker's Torque 
Hydra Fang
Hydra Meat 
Hydra Scale 
Orobon Lure 
Sirius Axe 

## Current Behavior

After several kills, Hydra consistently only dropped 1-2 water crystals.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Hydra?oldid=634775

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Thank you for this issue report. It is in-process now

**Comment by Swerve256** [comment]
Merged to master
