### ISSUE TITLE
Quartermaster does not auto drop items to the quartermaster's inventory.

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#23]
There are 2 loot options in the party menu, one is Lottery and the other is Quartermater which allows you to set a party member who will receive all drops. This feature appears to be broken.
## Expected Behavior

The selected party member designated as the quartermaster should receive all drops.
## Current Behavior

The loot pool acts as if it is still in Lottery mode. See the below screenshot where the loot pool continues to fill up even though one of the party members is set as QM.

![nanami_QM](https://user-images.githubusercontent.com/1855513/70091487-0c7ba780-15d1-11ea-8794-472ab1f39a52.png)

## Steps to Reproduce

1. Form a party
2. Go to the party menu options and under Loot select Quartermaster
3. Select a party member to be the quartmeraster
4. Kill some mobs for drops

## Context (Environment)

While dualboxing it's easier for me to assign quartermaster to one of my characters and then sort out the inventory in one pass later instead of having to sort twice on each character after farming. 

Also, this feature was commonly used during retail for BCNMs because the party leader could set quartermaster to themselves and ensure that they did not get ninja lotted on valueable items when running the BC with random players they did not know.

**Comment by OmegaBison** [comment]
Confirmed broken, and thanks for the detailed submission.
