### ISSUE TITLE
Kirin Astral Flows up to x2 at the same time

### ISSUE THREAD

**Issue by CosmicForge** [OmegaPrivateServer/issues#231]
## Summary

When Kirin Astral Flows around 50% or so, the move hits everyone twice.

## Expected Behavior

Astral Flow should only hit all targets one time each.

## Current Behavior

Astral Flow basically "double attacks" when it goes off, instead of a single AOE.
As the chat log shows, this wasn't just server lag, but a 2nd round of damage with new damage numbers applied.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Kirin?oldid=642250
No indication in the wiki from era 2008 or retail wiki that the AF should hit twice.
Here is the chat log both times it happened:
https://imgur.com/a/BEHs3Cx

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
We had issues reproducing this in test server however we have re-worked the Astral Flow logic and put a hard cap on it. Hopefully he will only do it once per fight now.
