### ISSUE TITLE
The 2 Hour for PUP is not working.

### ISSUE THREAD

**Issue by gm-bravura** [OmegaPrivateServer/issues#234]
## Summary
The 2 Hour for PUP is not working.. says no effect on pet when summoned. Will this be fixed?  

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters
Fatboyj

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Players say it works fine
