### ISSUE TITLE
Ornery Sheep in North Gustaberg do not drop items, only Earth crystals.

### ISSUE THREAD

**Issue by Balfury** [OmegaPrivateServer/issues#239]
## Summary
Ornery Sheep in North Gustaberg do not drop any items except crystals, they should drop the same items as South Gustaberg Ornery Sheep. 

## Expected Behavior
These Ornery Sheep should drop Sheepskin, Sheep Tooth, giant sheep meat and Fresh Blood.

## Current Behavior
Only Earth Crystals are dropped.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Ornery_Sheep?oldid=599194

## Possible Solution & Detailed Description
Have the north gustaberg sheep drop the same items as south gustaberg

## Characters
Crystus

## Steps to Reproduce

1. Go to Noth Gustaberg
2. Kill Ornery sheep
3. Notice how nothing drops
4.

## Context
I have killed 200+ while soloing and missed out on hundreds of sellable goods.

**Comment by Swerve256** [comment]
Thank you for the ticket Issue solved and submitted for review
