### ISSUE TITLE
Paladin AF Boots Fishing NM not working

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#24]
Fished for over 30 mins, no NM pop
## Steps to Reproduce

1.
2.https://ffxiclopedia.fandom.com/wiki/A_Boy%27s_Dream
3.
4.

## Detailed Description

Being able to fish up NM, if not maybe receiving item in inventory

**Comment by OmegaBison** [comment]
Fix implemented. Will be functional after the next patch goes live.
