### ISSUE TITLE
Unable to Trade fishing Guild items

### ISSUE THREAD

**Issue by Balfury** [OmegaPrivateServer/issues#240]
## Summary
Unable to trade Fishing guild items.

## Expected Behavior
When Fennella asks for a fish for guild points I should be able to trade it and receive points in exchange

## Current Behavior
Fennella is asking for Gugru Tuna, when I trade it nothing happens, same thing happened the other day with Bastore Sardine. The item stays in my inventory and I get no points.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

## Context
I am unable to gain rank points, I wish I knew it didnt work before getting all the fish.

**Comment by Swerve256** [comment]
Thank you for the ticket. Issue has been found and submitted for review
