### ISSUE TITLE
Wrong item got from fisherman guild.

### ISSUE THREAD

**Issue by rakelts16** [OmegaPrivateServer/issues#244]
## Summary
I chose to get Fisherman Apron 100 000 points and the npc gave me the Wanders. Also, only took 70k guild point (wanders). I took screenshoot.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

## Context

https://i.gyazo.com/1c2788cd8ed53c1c99fa11427ae9cbf7.png

**Comment by Swerve256** [comment]
Can you confirm the /ver of your client please?

**Comment by Swerve256** [comment]
Cannot reproduce and no other reports of this issue
