### ISSUE TITLE
on

### ISSUE THREAD

**Issue by rakelts16** [OmegaPrivateServer/issues#246]
## Summary
The zone crashed for the second time in a row during a fight. We think it may be related to inviting a player to the alliance when one of the parties is either 5/6 or 6/6.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Duplicate Ticket
