### ISSUE TITLE
Twitch Streaming no longer works

### ISSUE THREAD

**Issue by Ashenbubs** [OmegaPrivateServer/issues#257]
## Summary
Several users have reported (myself including) that the advertised exp+15% Streaming Bonus no longer works.

Tried several things, having 5+ more viewers, stopping/starting stream, refreshing, nothing works anymore - Previously it was always very intermittent on working and would sometimes require at least 1/2 viewers before kicking.

## Expected Behavior

Start Streaming on Final Fantasy XI channel, using correct header/title - Bonus should be received usually 5-10 minutes after starting.

## Current Behavior
No benefit received.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

None required.

## Possible Solution & Detailed Description

Check if Twitch API's have changed and update code where required, possibly?

## Steps to Reproduce

1.
2.
3.
4.

## Context

Advertised as a feature on the website - Bit awkward when new players are starting from viewing these streams and are sending tells complaining that it isn't working as intended.

**Comment by zierk** [comment]
Work is being done to fix this.
