### ISSUE TITLE
Unable to quiver Bronze Bolts

### ISSUE THREAD

**Issue by VeloxVenti** [OmegaPrivateServer/issues#259]
## Summary
Can't quiver Bronze Bolts with Nokkhi Jinjahl. The Bronze Bolt quiver slots show up on the Auction House, but are unable to be made. Not sure if there are other quivers or bullet pouches that are being affected. 

## Expected Behavior
Trade between 1-7 stacks of bronze bolts and 1-7 carnations equal to the bolt stacks to receive the respective number of Bronze Bolt Quivers. 

## Current Behavior
When trading bronze bolts and carnations to Nokkhi Jinjahl, she says "I'm real sorry, but there's nothing I can do with those."

## Characters
Velox

## Steps to Reproduce
Trade 99 Bronze Bolts and 1 carnation to Nokkhi Jinjahl.

**Comment by Swerve256** [comment]
Submitted resolution for review

**Comment by OmegaBison** [comment]
Resolved. Will be pushed to prod with the next patch.
