### ISSUE TITLE
Leathercraft GP Item request Round Shield

### ISSUE THREAD

**Issue by Thayos** [OmegaPrivateServer/issues#260]
## Summary

GP item being request for leathercraft GP is a high level woodworking craft.
## Expected Behavior

Not ask for items outside leatherworking craft.
## Current Behavior

Asking for woodworking item.
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters

Thayos
## Steps to Reproduce

1. Journeyman leatherworking
2. Speak to GP manger for the guild
3. possible request for items outside leatherworking
4.

## Context

Missing an entire day of GPs.

**Comment by Swerve256** [comment]
During test journeyman is asking for a studded vest. Can you confirm if you are using the Omega Client, and what /ver you are on? Thanks

**Comment by Thayos** [comment]
version 30181205_0
can't say if it is the same version as the date of posting.  The GP items varies everyday so can be likely you might not see it.  Also, I am using the omega launcher.

**Comment by Swerve256** [comment]
Thank you found the issue and submitted for implementation.
