### ISSUE TITLE
Aquaveil does not work. It randomly comes off while taking damage.

### ISSUE THREAD

**Issue by gm-bravura** [OmegaPrivateServer/issues#261]
## Summary
Aquaveil does not work. It randomly comes off while taking damage. This can be anywhere from 5sec, first hit, to a minute or two taking several hits. It is supposed to last for 5 minutes period.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters
Shesaid

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
Aquaveil will no longer randomly remove itself.
