### ISSUE TITLE
Weaponskills are not providing skill ups.

### ISSUE THREAD

**Issue by Syfin1** [OmegaPrivateServer/issues#267]
## Summary

When you use a weaponskill it does not give any skill ups.
## Expected Behavior

Each hit of weaponskill should have a chance of providing a skill up.  For instance, Tachi: Enpi hits twice, it should have 2 chances of providing skill ups.
## Current Behavior

There is no possibility of getting skillups on weaponskills
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Possible Solution & Detailed Description

The best solution would to be to code it so a weaponskill, depending on how many hits the weaponskill is, can provide the appropriate amount of skill up chances.
## Characters

Syfin and Laci
## Steps to Reproduce

1. Use a weaponskill on a monster that is at your level, with your skill not capped with the particular weapon
2. There will be no skill up opportunities
3.
4.

## Context

The issue affects everyone in slowing down the skill up process,  The ability to use multi hit weaponskills while skilling up and getting more chances at skill ups helps expedite the process.

**Comment by Thayos** [comment]
https://github.com/OmegaPrivateServer/issues/issues/237
