### ISSUE TITLE
Shock Spell bugged

### ISSUE THREAD

**Issue by NyanNyanSquad** [OmegaPrivateServer/issues#27]
## Expected Behavior
 Shock should shock 

## Current Behavior
 Shock Permacasts 

 Possible that the server simply isnt providing the requested packet to finish casting. Put code into oven at 350º for 45 minutes or until ready

## Steps to Reproduce

1.Cast shock
2.Wait
3.Fall Asleep
4.Maybe die.

**Comment by OmegaBison** [comment]
Confirmed

**Comment by OmegaBison** [comment]
Fix has been implemented and will go live with the next patch.
