### ISSUE TITLE
Divine bijou Not dropping

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#271]
Pop  item for Dynamis windurst boss  (Tzee Xicu Idol) appears to not be on the loot tables of any mob or NM in dynamis windurst

After killing every NM in dynamis windurst over 30 times, we have no seen a single drop to pop the boss

according to test server databases it's showing it as a 1% drop rate which is not correct, it should be closer to 25% referencing the first link

http://www.ffxidb.com/items/3355

https://ffxiclopedia.fandom.com/wiki/Divine_Bijou

**Comment by Swerve256** [comment]
Fix submitted for Review

**Comment by Swerve256** [comment]
Merged into master
