### ISSUE TITLE
Offensive Magic Max Casting Range Incorrect

### ISSUE THREAD

**Issue by Thayos** [OmegaPrivateServer/issues#272]
## Summary

The maximum distance for casting offensive based magic, while varies per monster, still appears to be to short.
## Expected Behavior

Maximum cast range should be 21.8 yalms
## Current Behavior

20.3 yalms is the roughly what I have seen for a "normal" sized monster
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Distance?oldid=636148
## Possible Solution & Detailed Description

Increase maximum casting distance for offensive magic.
## Characters

Thayos
## Steps to Reproduce

1. Cast a spell on monster
2.
3.
4.

**Comment by Swerve256** [comment]
Submitted for next Patch
