### ISSUE TITLE
/heal (resting) ticks are incorrect.

### ISSUE THREAD

**Issue by Ashenbubs** [OmegaPrivateServer/issues#273]
## Summary

HP/MPh ticks are currently not correct - Using the plugin "Tickle" with Windower it will display a small number on your screen ticking down the seconds to show you when you should get your next "Tick" of recoverable HP/MP
When you hit /heal it will start at 20 seconds:
![image](https://user-images.githubusercontent.com/61240482/82830392-82d8d280-9ead-11ea-829b-e8616880cda6.png)

The current ticks on this server appear to be:
20 seconds
10 seconds
10 seconds
13 seconds
10 seconds
10 seconds
13 seconds
10 seconds
10 seconds
13 seconds (...)

## Expected Behavior

Resting ticks should be
20 seconds
10 seconds
10 seconds (...)

## Current Behavior

Resting ticks currently are:
20 seconds
10, 10, 13, 10, 10, 13 (...)

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Tick

## Steps to Reproduce

1.  Install the plugin "Tickle" to check timer on upon resting
2. Watch the timer follow the above incorrect pattern

## Context

Slower recovery speed for mages (MPh) and everyone in general whatever they're doing.

**Comment by zierk** [comment]
Resting ticks should be resolved in the next patch. Arithmetic errors at the millisecond level was causing tick remainders to offset and unbalance the tick timers.
