### ISSUE TITLE
Aeroga castable with insufficient mp.

### ISSUE THREAD

**Issue by Syntex7** [OmegaPrivateServer/issues#274]
## Summary
The Black Mage spell Aeroga's mp cost is incorrect when using a macro.

## Expected Behavior
Aeroga should only be castable when you have 57mp or greater. 

## Current Behavior
Aeroga is castable under 57 mp through the use of a macro command. /ma "Aeroga" <t> will cast aeroga under 57 mp. However when selecting the spell from your spellbook or menu it will be grayed out and give "not enough mp" error.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Aeroga?oldid=529777

## Possible Solution & Detailed Description
Later versions of the game lowered the cost of Aeroga to 45mp. I think when using a macro command it is referencing this value to cast aeroga and not era accurate value. Not sure as to why the macro command accesses a different mp cost.

## Characters
Syntex / Jen

## Steps to Reproduce
1. Be on Blm with spell Aeroga
2. be at 47mp to 56 mp
3. Type /ma "Aeroga" <t> or use a macro with that command
4. Watch as you cast Aeroga without sufficient mp

## Context
Because BLM has access to conserve MP trait its hard to narrow down the exact cost of each aeroga since this could trigger on each and every spell. However Conserve MP only triggers on resolution of cast when MP is spent. It doesn't allow for casting of spells when you have insufficient MP. By getting your MP pool below 57 you eliminate the possibility of conserve MP skewing results. After testing it also seems you need at least 47 mp to cast with the macro command, any lower and you get too little mp error. Also when you have sufficient mp to cast it from the menu it still only uses 47 mp after many cast but displayed 57mp

Also picture of me casting aeroga with insufficient mp https://imgur.com/a/043Fzz0

**Comment by Swerve256** [comment]
spell mp is correct per era, but the menu is not correct value. This value is on the Client side not the server side.
