### ISSUE TITLE
Megalobugard in Lufaise Meadows is not re-spawning

### ISSUE THREAD

**Issue by malachimtg2** [OmegaPrivateServer/issues#275]
The placeholder for the NM Megalobugard in Lufaise Meadows is not re-spawning after being killed. When the server resets the placeholder is there and once killed the NM will appear, once the NM is killed the placeholder with never come back until the server is reset. I have cleared the area of monsters and have camped this NM for hours and hours trying to get the Hercules' Ring it drops for PLD with no sight of the NM at all.

**Comment by Sakura-momo** [comment]
This is still an issue, I've camped this 5+ times at 3-5 hours each time killing every Buggard in the area.

**Comment by zierk** [comment]
Fixed. Will take effect in the next patch.
