### ISSUE TITLE
Dynamis Jeuno no NMs 

### ISSUE THREAD

**Issue by itssteved** [OmegaPrivateServer/issues#277]
## Summary
When you enter Dynamis Jeuno there are no NMs to obtain the mega boss pop item or debuff items. 

## Expected Behavior
The applicable NMS should be automatically roaming their appointed positions.

## Current Behavior
No NMS are spawned. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
Note: Was informed dynamis is stock DSP which is 2010~ Link is Jan 2010 
https://ffxiclopedia.fandom.com/wiki/Dynamis_-_Jeuno?oldid=1069648

## Possible Solution & Detailed Description
Add the applicable NMs listed on the wiki page

## Characters
Everyone attempting to clear Dynamis Jeuno

## Steps to Reproduce
I wish I had the code, not a DEV

## Context
Not being able to clear dynamis jeuno is preventing game progression for everyone on Omega that is attempting to progress to Xarcabard

**Comment by zierk** [comment]
City Dynamis zones will be getting looked at soon. I would like to get all 4 city zones working so access to Glacier and Xarc can be a thing. Work will begin soon on vanilla dynamis zones.
