### ISSUE TITLE
Flesh Eater worms in Attohwa Chasm check as Impossible to Gauge

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#28]
The Flesh Eater worms are classified as normal monsters according to this wiki entry from 2007 regarding the level 34-37 worms in Attohwa Chasm
https://ffxiclopedia.fandom.com/wiki/Flesh_Eater?oldid=223411

## Current Behavior
These mobs are checking as if they are NMs.

## Expected Behavior
The mob should check as a regular mob and give a response from one of the following depending on the level of the player character:

- Too Weak to be Worthwhile
- Easy Prey
- Decent Challenge
- Even Match
- Tough
- Very Tough
- Incredibly Tough

![Aeolus_2019 12 05_214918](https://user-images.githubusercontent.com/1855513/70299604-376d2380-17aa-11ea-86a6-2a4a8b49b910.png)

## Steps to Reproduce
1. Go to Attowha Chasm and locate the Flesh Eater worms near H-9
2. Target a worm and bring up the action menu
3. Select the Check option

## Context (Environment)
The Impossible To Gauge check makes it difficult for players to understand how strong the mob is in comparison to their current level and is intended to be restricted to NMs.

**Comment by OmegaBison** [comment]
Thanks. Fixed. Change will go live with the next patch.
