### ISSUE TITLE
Martial Slacks

### ISSUE THREAD

**Issue by Malevolense** [OmegaPrivateServer/issues#281]
Crypt Ghost doesn't seem to drop Martial Slacks.

Martial Slacks should drop when Crypt Ghost is killed.

Have killed lots of times and never seen Martial Slacks. No history on auction house either, nobody I know has seen them drop or being worn by a person.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Possible Solution & Detailed Description

Badtoad

## Steps to Reproduce

1.
2.
3.
4.

**Comment by owallace** [comment]
My friend just got the drop recently, you're just getting unlucky. They have also been sold on the AH before.

**Comment by Swerve256** [comment]
Thank you for submitting the concern Confirmed the drop is in the game from the ghost
