### ISSUE TITLE
Chocobo Digging - (Accuracy, zone pools, & no need for movement)

### ISSUE THREAD

**Issue by Pugbug** [OmegaPrivateServer/issues#288]
## Summary
There are some aspects to the current chocobo digging that is not accurate, and could have a unintended impacts on the economy - see context. 

In essence, the accuracy is too high, there is either no shared treasure pool or there is an issue with the way the treasure pool depletes, and no need for moving the chocobo between digs. 

1 - Accuracy
2 - Shared treasure pool
3 - Item pool number too high, or does not deplete maybe? maybe coded similar to mining?
4 - Movement between digs 

## Expected Behavior

1 - Accuracy for Amateur rank should be approximately 25%. Accuracy for max rank should be approximately 55%
2 - Diggers are competing for a finite number of items in a treasure pool.
3 - At expert rank the digging accuracy is so high that you will deplete the shared treasure pool fairly quickly (depending on moonphase, but approximately 30-60 minutes of digging)
4 - To get items from digging = Dig, move/change position by a pixel at minimum, Dig, Repeat. If you don't move, you will dig, but find nothing. 

## Current Behavior
1 - Accuracy is currently 50%+ for an amateur rank digger. Not sure on accuracy for expert rank. 
2&3 - There appears to be no limit on the number of items diggers can obtain. 
4 - You stay in one position, and can dig, and get items.  

## Relevant Wiki Link 
https://ffxiclopedia.fandom.com/wiki/Chocobo_Digging_Guide?oldid=353257 
^ does not refer to movement I think, but all videos on youtube should show they are always moving. 

## Possible Solution & Detailed Description
Sorry that it's a drawing: 
https://ibb.co/k9pbS01 

## Characters
All characters

## Steps to Reproduce
1. lvl 20, with choco lisence.
2. wait 1 minute
3. type '/dig'
4. repeat

## Context

Having the accuracy of a max rank digger is unfair to the diggers who diligently dig every day to obtain higher ranks. It also makes skilling up significantly easier, as it takes less number of digs to gain a rank (assuming successful dig counts towards ranking up). Combine this with no shared treasure pool, and/or potentially unlimited items, could also remove people from other HELM activities, and overwhelm the auction house with digging items. Not needing to move to obtain a successful dig means is a bit like fishing where you only needed to cast and hit enter back in the day - easy, boring, and potentially easy to abuse.

**Comment by Pugbug** [comment]
"2&3 - There appears to be no limit on the number of items diggers can obtain." within the 200 fatigue limit, which is working.

**Comment by zierk** [comment]
Thanks for the report. This issue has been addressed in the next patch.
