### ISSUE TITLE
Beastmen's Seal drop when there is no exp

### ISSUE THREAD

**Issue by Pugbug** [OmegaPrivateServer/issues#289]
## Summary
Beastmen's seals should only drop when exp is gained. This means monsters that check as 'too weak' should not give beastmen's seals. However, in mixed level parties, where no exp is gained, you can still get beastmen's seals. 

## Expected Behavior
If no exp is gained then no beastmen's seal. 

## Current Behavior
Even if there is no exp you can get a beastmen seal. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Beastmen%27s_Seal?oldid=291593

## Possible Solution & Detailed Description
Check that experience points is given before giving beastmen's seal. 

## Steps to Reproduce

1. Mix party in starter city. lvl1-9, and lvl 20-75. 
2. Kill starter monsters that proc 
3. Wait for drop, which should be around 5%? or w/e it is. 
4.

## Context
Potentially open to abuse, because 1 hit kills mean you can murderize monsters very quickly and obtain a BS with very little effort. If you were in an aliance where you can get up to 3 bs drops for every 5 minutes, then you can see how someone can amass a stupid number of beastmen seals with very little effort or risk.

**Comment by Pugbug** [comment]
was the issue fixed?

**Comment by Spear-omega** [comment]
Yes, finally, omg
