### ISSUE TITLE
Dispel not generating enmity when it has nothing to dispel

### ISSUE THREAD

**Issue by Syntex7** [OmegaPrivateServer/issues#290]
## Summary
The Red Mage spell Dispel is not generating enmity when used on a mob that has no buffs to dispel.

## Expected Behavior
Dispel should generate appropriate enmity regardless of its success and even when there is nothing to dispel.

## Current Behavior
Dispel is currently generating no enmity when it dispels nothing.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Dispel?oldid=611884

## Possible Solution & Detailed Description
Exclude check for success on enmity formula for dispel. 

## Characters
Syntex / Jen

## Steps to Reproduce
1. Go to Sarutabaruta and have a character pull a level 1 bee.
2. Have 2nd character in party cast dispel repeatedly
3. Watch how the character casting dispel never pulls aggro

## Context
Dispel is an essential enmity generating tool used for RDM tanks in Era. Without this enmity working correctly tanking on RDM is extremely difficult if not impossible. This is not era accurate as RDM was a viable endgame tank and an alternative tank to PLD on long difficult fights. Please see Kanican's enmity table for values: https://web.archive.org/web/20071213043643/http://kanican.livejournal.com/13848.html

Also I suspect that there is a similar issue with other spells like sleep not generating enmity when cast on a mob who has been slept with Sleep II or stun while a mob is already stunned as the behavior is similar.

**Comment by zierk** [comment]
Fixed. Changes will go live in next update. Thanks for the report.
