### ISSUE TITLE
ToAU 15 [The Black Coffin] Unable to enter BCNM [Bugged in the ground]

### ISSUE THREAD

**Issue by lvlrSocom** [OmegaPrivateServer/issues#293]
## Summary
Unable to enter TOAU Mission 15 [The Black Coffin] BCNM.

## Expected Behavior
You should be teleported into the BCNM at this point.

## Current Behavior
Upon selecting the "Cutter" NPC on the ship in The Arrapago Reef I receive a cut-scene before the fight entrance selection screen, which is correct! After the cutscene I select the "Cutter" once more and select to enter the BCNM for Black Coffin. The ship animation/CS shows the boat heading to the Black Coffin. But after zone-changing/loading, I am popped out back into Arrapago Reef, however, bugged into the bottom of the sea, underneath the map. Not teleporting me into the BCNM.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Aht_Urhgan_Mission_15:_The_Black_Coffin?oldid=636038

## Possible Solution & Detailed Description
The players should just be teleported into a working BCNM. Everything before the issue where my characters bug into the sea, is working as intended/expected.

## Characters
Katy & Perry

## Steps to Reproduce

Please find below, two links to screenshots that I had taken in game of my characters in the CS heading to the Black Coffin, and then what appeared after the zone-change. Instead of being on the ship for the BCNM fight, we're stuck in the ground.
[https://drive.google.com/file/d/1RZ_tE_dalraK8kOyIzTVaYh7V4yLmq_u/view?usp=sharing]
[https://drive.google.com/file/d/11oB4B4RwQAT67khZXTXY6AmXPv2aTMKj/view?usp=sharing]

1.Select the "Cutter" NPC/section of the boat in Arrapago Reef to enter the BCNM.
2.The first cut-scene is a pre-fight-cut-scene, you will not be ported to the fight. 
3.After selecting the "Cutter" again, you're given a short CS of the boat heading to the Black Coffin.
4.Upon zoning into the Black Coffin, the characters are tossed under the ground/sea and are stuck. Never entering the BCNM.

## Context
There is no Limbus, there are very limited ENMs, ZNMs do not work either. Assault, Einerjar and Salvage do not work either. I'd like some more working content please, I really enjoy the TOAU story-line. 

If there is anything I can do to assist further please let me know.

**Comment by zierk** [comment]
We are aware of this issue. 
I will say upfront that ToAU story is low on the priority list at this time. The main focus for content as of this writing: zilart > cop > toau.  Once all missions in zilart are working & balanced, we will move to cop missions/end game, then focus on ToAU. We know some people have nothing to do because they got past content before it was implemented. ToAU will become a priority at some point, but today is not that day. The good news is, a lot of zilart/cop are already working so that means ToAU is that much closer to being fixed.
