### ISSUE TITLE
Skillchain is incorrect

### ISSUE THREAD

**Issue by RoTheNerd** [OmegaPrivateServer/issues#294]
## Summary

Raging Rush > Raging Rush is doing the incorrect Skillchain effect
## Expected Behavior

Raging Rush > Raging Rush should be Fragmentation.
## Current Behavior

Currently Raging Rush > Raging Rush is doing Induration.
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
We are aware of this SC and others which are incorrect. There is a logic error happening where weapon skills with multiple elemental affinity are not being combined in the proper order so they produce the wrong SC combination. There are 3-4 other SCs we are aware of that are also affected by this.
