### ISSUE TITLE
Elemental Staves Additional Effect Damage not working

### ISSUE THREAD

**Issue by cubbypanda** [OmegaPrivateServer/issues#297]
## Summary

The Elemental Staves Additional Damage is not proccing on melee hits.
## Expected Behavior

There should be Additional Effect Damage when hitting with elemental staves with that element.
## Current Behavior

Just regular melee damage is occuring.
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1. Get elemental Staff (Fire Staff)
2. Equip Elemental Staff
3. Hit monster
4. No additional effect occurs.

**Comment by Jeffrow419** [comment]
All additional effect on weapons seem not to be working

**Comment by zierk** [comment]
All hidden effects do not seem to be working either. Research needs to be done prior to implementation.
