### ISSUE TITLE
Tea with a Tonberry?

### ISSUE THREAD

**Issue by VeloxVenti** [OmegaPrivateServer/issues#298]
## Summary
"Tea with a Tonberry?" quest not able to be started.

## Expected Behavior
After competing "Signed in Blood" and zoning, NPC Sobane should begin dialogue for "Tea with a Tonberry? " and flag the quest.

## Current Behavior
Sobane is currently not giving any dialogue after competing "Signed in Blood"

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
Comments of quest being completed date back to as early as 2006.

## Characters
Velox

## Steps to Reproduce
1. Talk to Sobane and complete quest "Signed in Blood"
2. Zone
3. Talk with Sobane again to receive no dialogue

## Context
Trying to compete quest for reputation and Willpower Torque

**Comment by Swerve256** [comment]
The problem with this quest currently is you need access to CL ferry. That's more difficult than scripting the quest. To be discussed with staff
