### ISSUE TITLE
BLM spells.

### ISSUE THREAD

**Issue by fenux1** [OmegaPrivateServer/issues#3]
It seems like 3 things are wrong with blm tier 1 spells. They have a very fast cast, they have a 1 second recast, and they cost to little MP.
## Expected Behavior

BLM should destroy ALMOST everything.
## Current Behavior

BLM destroy everything
## Possible Solution

It seems like the MP costs are in the game because when you use the menu to select spells, they state that they cost a larger amount of MP than they actually do.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Resolved.
