### ISSUE TITLE
Installer does not register in Apps or provide uninstall option

### ISSUE THREAD

**Issue by whandango1016** [OmegaPrivateServer/issues#30]
Installer does not register in Apps or provide uninstall option

## Expected Behavior
We should be able to uninstall an app via Windows Apps menu.

## Current Behavior
No install option.

**Comment by OmegaBison** [comment]
Currently working on a full rewrite of the installer. The new installer will be GUI instead of CLI.

**Comment by OmegaBison** [comment]
New GUI installer has been released.
