### ISSUE TITLE
Jailer of Justice / Jailer of Love do not spawn when trading pop items.

### ISSUE THREAD

**Issue by Mstoughton1111** [OmegaPrivateServer/issues#302]
## Summary
Trading the pop items for Jailer of Justice/Love to do not spawn the NM.

## Expected Behavior
NM's should spawn once the 3 required items are traded to the ???.

## Current Behavior
It does nothing. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Jailer_of_Justice
https://ffxiclopedia.fandom.com/wiki/Jailer_of_Love

## Possible Solution & Detailed Description
Get the code from Aeolus, it's working on his test server. Can confirm that it did pop once he made the changes.

## Characters
Spankies

## Steps to Reproduce
Trade 1st Virtue + Deed of Placidity + HQ  Xomzit - Justice should pop
Trade 4th Virtue + 5th Virtue + 6th Virtue - Love should pop

## Context
Trying to get them torques and earrings and pop/kill AV - so its stopping our LS from progressing !

**Comment by zierk** [comment]
JoL and JoJ are broke on purpose because currently they do not represent the challenge they should or have broken mechanics. They are high on the list to get work done, but require a mechanical rewrite and testing before we can release it. We will take a look at them soon.

**Comment by zierk** [comment]
Jailer of Justice will be available in the next patch.
