### ISSUE TITLE
Istakoz - Peeled Lobster

### ISSUE THREAD

**Issue by GiggleCait** [OmegaPrivateServer/issues#304]
## Summary
Peeled Lobster cannot be obtained from Istakoz. 

## Expected Behavior
x1 Wind Crystal & x1 Istakoz = x1 Peeled Lobster

## Current Behavior
Synth is not possible. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Peeled_Lobster?oldid=259572

## Characters
Meflab

## Steps to Reproduce
1. Obtain Wind Crystal
2. Obtain Istakoz
3. Use Wind Crystal
4. Place Istakoz into craft item
5. Press Enter

## Context

Cooking skill.

Mimic code from Gold Lobster Synthesis.

**Comment by zierk** [comment]
Patch submitted to add this recipe. Should go live in a future update. Thanks for reporting the issue.
