### ISSUE TITLE
Able to charm the Lord of Onzozo PH with low level bst

### ISSUE THREAD

**Issue by gm-bravura** [OmegaPrivateServer/issues#311]
## Summary

I Was able to charm the Lord of Onzozo PH with level 12 bst subjob...this should not be possible.
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters

Lil

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
need to do some research on this. charm should consider the max level of the bst job even when using charm as a /bst. since this is working with a level 12 bst i assume the issue is there is no check at all.
