### ISSUE TITLE
Wrong GP Items obtained from Fishing Guild

### ISSUE THREAD

**Issue by Noukon** [OmegaPrivateServer/issues#312]
**Summary**
I have been asking for a pairs of Waders from the Fishing guild, and the reward given was a Fisherman's belt. I lost the GP for the belt though, but I still don't know why this happened.

See the screenshot below.

**Expected Behavior**
Obtain the requested item (70K GP fishing > Waders)
**Current Behavior**
Obtain a fisherman's belt...
Relevant Wiki Link
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

**Possible Solution & Detailed Description**
**Characters**
Rose

**Steps to Reproduce**
Ask the NPC for an item and get something wrong :)
<img width="655" alt="Capture" src="https://user-images.githubusercontent.com/65075045/88058906-6a5efe80-cb64-11ea-8e8c-7d2fcfd16fbf.PNG">

Context

**Comment by eaponte23** [comment]
This is an on going issue with the fishing guild, I first experienced this months ago. 

Next time request the item below the item you want on the "first page". In other words, if you want the Waders select the item just below the Waders on the list. The second page of available items don't seem to be affected by this bug. 

I'd submit a ticket on the page to see if the GM will exchange this for you. I've seen that happen if you submit a ticket. Good luck!

**Comment by Noukon** [comment]
Thanks for the tip! It worked like a charm. 
I did send a ticket to report this and get a refund of these 10K GP lost for an undesired item.

Hope this will be fixed soon :)
