### ISSUE TITLE
Bard Tier 2 Merit Ability Song "Foe Sirvente" is not cast-able

### ISSUE THREAD

**Issue by CosmicForge** [OmegaPrivateServer/issues#313]
## Summary

When Foe Sirvente is purchased with merit points, it remains uncastable. Even after zoning/logging out.

## Expected Behavior

This merit song should be castable and is in-era according to Aug 2008 standards.

## Current Behavior

(Player) cannot cast Foe Sirvente.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Foe_Sirvente?oldid=541053

## Possible Solution & Detailed Description

At a later point in retail, this "merit ability" was changed to a purchasable scroll in the shops. I'm not sure if that's the current issue preventing its casting.

## Characters

Smash

## Steps to Reproduce

1. Purchase the song in the tier 2 merit category and attempt to cast.
2.
3.
4.

**Comment by zierk** [comment]
This spell is not usable because there is no script for it. This will require some research on formulas and then a custom re-write of the ability.
