### ISSUE TITLE
Item Pools for digging in Wajoam / Bhaflau appear to be messed up?

### ISSUE THREAD

**Issue by lvlrSocom** [OmegaPrivateServer/issues#314]
## Summary
Bhaflau Thickets & Wajoam Woodlands digging pools are incorrect. 

## Expected Behavior
Pephredo Hive Chips are supposed to drop from the digging treasure pool in Wajoam Woodlands. There are also other items circa 2008 that are not dropping from these pools also.. I.e. Adaman Ore. 

## Current Behavior
The digging pool is incorrect; some items drop properly.. It appears that they may be the SAME loot pools for both zones? I haven't seen an Adaman ore from Bhafl or Wajoam, and the Wiki linked here does explicitly state that Wajaom should drop these items. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Wajaom_Woodlands?oldid=602231#digging
https://ffxiclopedia.fandom.com/wiki/Bhaflau_Thickets?oldid=602172#digging

## Possible Solution & Detailed Description
Just a match of the circa ~2008 digging pools to match the ones on our server! 

## Characters
Katy / Perry (Ashenbubs also can attest to this)

## Steps to Reproduce
1. Buy Greens required to dig
2. Dig in either Bhaf/Waj zone.. 

## Context
I am unable to dig up proper in era, materials to help expedite my crafting.

**Comment by zierk** [comment]
We will be doing a balance pass on the digging system which will include a look at loot tables, drop rates, exp rates, digging mechanics, and some other things. We are aware of issues with digging and it's on the todo list. Thank you for your report.

**Comment by zierk** [comment]
Thanks for the report. Will be addressed in the next patch.
