### ISSUE TITLE
Sluagh - Out of Era

### ISSUE THREAD

**Issue by GiggleCait** [OmegaPrivateServer/issues#315]
## Summary
Sluagh is out of era and shouldn't be in Fei' Yin. 

## Expected Behavior
Ded

## Current Behavior
Alive

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
NOV2009+

**Comment by zierk** [comment]
Fixed. Will be removed from game on the next update. Thanks for the report.
