### ISSUE TITLE
Eldritch Edge & Blighting Brand - Out of Era

### ISSUE THREAD

**Issue by GiggleCait** [OmegaPrivateServer/issues#316]
## Summary
The set of earrings is not era. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
NOV2009+

## Context

Instead of the market flourishing with other earring options such as morion NQ and HQ this NM is camped. The NM is also camped to further a RDM's ability to enfeeble IG mobs. The set should be removed from the game as it is not the era we all know.

**Comment by Noukon** [comment]
What about those who actually spent time camping these NMs to get these earrings?

**Comment by Thayos** [comment]
@GiggleCait I get what you are saying but thats a terrible comparison saying that morion NQ or HQ earrings = these two earrings.

**Comment by GiggleCait** [comment]
> @GiggleCait I get what you are saying but thats a terrible comparison saying that morion NQ or HQ earrings = these two earrings.

I think you fail to understand my logic. I am not comparing the two. 

> What about those who actually spent time camping these NMs to get these earrings?

Time spent or not, they aren't the era we know.

**Comment by Noukon** [comment]
You can’t unilaterally decide what is « era » and what is not **on Omega**. Following your reasoning, we should discard all items post 2008, that include many items that many users have today (you can do the list just by watching AH/Equipment).
Let’s not forget about running speed which is a bit higher, HP Warp, OP Warp unlocked, etc.

This belongs to a community poll more than a bug report.

**Comment by zierk** [comment]
Actually the development team reserve the right in this case. Our goal here is to get as close to era as possible while taking into consideration QoL adjustments that help everyone.

The server's "era" has been set to August 2008. While it is true that OOE things exist in game, NMs and Items should be reported so they can be removed. OOE QoL changes are designed to make the game less annoying and more enjoyable for everyone equally. We do not want to go down the path of having to make balance adjustments based on what OOE items we decide are acceptable. 

If you participate in OOE content, you are doing so at your own risk. 

We are a volunteer staff and changes are made in an order that makes sense, sometimes it takes a while for OOE things to be corrected but they will eventually be corrected. We rely on players to do their part and report issues so everyone can have the experience you signed up for.

**Comment by Ashenbubs** [comment]
That's a shame.

I've heard from previous Devs that these lower level NMs were still here as it allows players to obtain better gear suited for level sync PTs to help new players enjoy the game more - There are probably a dozen or so lower-level Accuracy+ gear pieces whereas usually in this era the only piece of gear you'd see with any amount of accuracy+ on is a Peacock Charm.

There's currently very little to do - I wish we'd focus more on getting content correct rather than removing content - I can't think of any, these earrings included, NMs that drop anything that would be considered anything "broken" by any means, all their gear seems fairly well balanced considering this level - In a game where a pair of Lv7 boots can be worn until 75, I think the game balances gear out oddly all the way.  Most these items (this example included) are rare/ex so give no downside to the community, which is also small enough that you will never see competition currently.

We're trying to grow the community, not make things harder for newer players.  Just tossing in my two cents and speaking up on behalf of the community, as I know I'm far from the only one who agrees on the above.

**Comment by Noukon** [comment]
I’ll just agree 100% with Ash, and add that removing those non breaking items will just be the exact contrary of the Omega server motto; we all have a life (thus the HP Warps, etc). Removing those items will just mean that all time wasted camping (some NMs have horridous drop rate) will be for absolutely nothing.

There are way better needs to mobilize the devs for.

**Comment by GiggleCait** [comment]
> You can’t unilaterally decide what is « era » and what is not **on Omega**. Following your reasoning, we should discard all items post 2008, that include many items that many users have today (you can do the list just by watching AH/Equipment).
> Let’s not forget about running speed which is a bit higher, HP Warp, OP Warp unlocked, etc.
> 
> This belongs to a community poll more than a bug report.

I agree with the community poll but this is still the appropriate area to report such matters. I don't understand your curt replies as if this were some drawn out argument. Yes there are "Quality of life" adjustments currently in play, as this does assist with boosting server growth. I personally have been a part of DSP since conception and as servers grow they slowly remove such items. I've seen many era servers attempt to claim to be era, yet they implement things that aren't era whatsoever. 

Homam isn't going to be fixed overnight, and although I appreciate the current staff, I don't think they are able to fix the content that is broken. They are however able to fix things that aren't era, and smaller line items. 

I have many ideas for server growth but the current staff appears to be made up of solely GM's and lower tier devs. Let's see what comes over the next few months.

**Comment by zierk** [comment]
We are going to leave these NMs in along with a few others which provide QoL items that help bridge level ranges where there really isn't any options. As long as these items are not game breaking and are not BIS then I do not really see the harm in them. If we took these NMs out then we would need to re-evaluate things like Guerilla Gloves, Hedlong Belt, Crab Sushi, etc.

I realize this is going to look bad considering my previous comment was the exact opposite so I'll just be taking that on the chin. I was in a different position then and things have changed.

**Comment by Swerve256** [comment]
Let me just say while I completely agree with everyone else on this topic. Zierk comments about partaking in OOE NM and other items are at the players risk of being patched. So please continue to report and ask about an OOE item before spending your time getting them.
