### ISSUE TITLE
Cooking GP NPC Qhum Knaidjn does not accept Smoked Salmon when traded

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#32]
The Qhum Knaidjn NPC at E-9 in Windurst Waters is supposed to give the player points in return for a guild item which changse daily. Today's item is smoked salmon, however, trading smoked salmon is not working.
## Expected Behavior

The item should be removed from the player's inventory and the player should be rewarded with GP.
## Current Behavior

The trade window closes as if the trade has completed, but the item is not consumed and no GP is awarded.

## Steps to Reproduce

The steps below may vary depending on the GP item of the day. This was only tested with smoked salmon.
1.  Trade smoked salmon to Qhum Knaidjn at E-9 in Windurst Waters

## Context (Environment)

In order to acquire key items necessary for cooking I must be able to trade GP items to the NPC on a daily basis. Since smoked salmon is one of the easiest trades to do and has a 6k point cap it's a valuable GP item and losing out on the points is a big loss. I'll note here that this may be an issue with all cooking GP items and not just smoked salmon, but it's nearly midnight and need to sleep but I wanted to log a ticket for visibility.

In this screenshot you can see that I have 0 guild points accumulated and also have all my salmon in the inventory even after attempting to trade it.
![Nanami_2019 12 08_233925](https://user-images.githubusercontent.com/1855513/70416790-b1084a00-1a14-11ea-8971-614671f8121e.png)

----
Edit - Additional Info 12/9/2019:
I did some testing on the Sheep server. The cooking NPC accepted GP items for all ranks (novice-veteran) for today's guild pattern (tortilla, iron bread). I assume that the guild pattern is based on the server's timezone and date so I will have to wait until the pattern changes back to the one which includes Smoked Salmon in order to continue testing on Sheep.

----
Edit 12/10/2019:
Confirmed that Black Bread for today's Apprentice pattern item works in prod

**Comment by OmegaBison** [comment]
I don't see anything in the code that would be causing this, and I dug through server logs to find your trade attempt but there were no lua errors produced.

Let me know when Smoked Salmon is back in rotation.

**Comment by dvalderrama89** [comment]
Happened again today, different guild pattern.
Here's a video (skip to the 50 second mark) https://www.twitch.tv/videos/522208240

Also, note that the first time this happened when I opened the ticket I had just become a Novice, meaning that I had never turned in guild point items before. In the example video I've already accumulated some points so I suspect this has to do with ranking up. More investigation is needed, but I don't know how else to test this on my end.

**Comment by dvalderrama89** [comment]
I reproduced the issue on sheep, it seems like it has to do with reaching the point limit of the previous rank before ranking up.
1. Trade the GP item of the day until you max out on points
2. Set your craft rank to the next highest level
3. Attempt to trade the new GP item the NPC requests

I think one of two things should happen in this case, either the player should be allowed to trade the item and get points even though the day has not reset to the next pattern, or there should be a dialogue that says they cannot trade because they're maxed out. Currently the NPC falsely states you can still acquire points after you rank up.

It's worth looking into why this occurs when the player goes from Initiate -> Novice when they have not reached any point limits. It's a poor user experience to make the effort to acquire the GP item after you hit Novice only to be blocked from trading.

**Comment by dvalderrama89** [comment]
After additional research it appears that the NPC is working correctly and that the lockout on the same day you sign up for the guild points is intentional.
