### ISSUE TITLE
Stuck in black screen after completing Up In Arms BCNM

### ISSUE THREAD

**Issue by gm-bravura** [OmegaPrivateServer/issues#321]
## Summary
Stuck in Up in Arm , we finish the NM , then we got stuck in black screen 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters
Giapper

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Known Issue with all BCNM going to close ticket here but will find a fix soon
