### ISSUE TITLE
3 days in a row with OOE Item requested for GP

### ISSUE THREAD

**Issue by Noukon** [OmegaPrivateServer/issues#322]
## Summary
Fishing guild and Woodworking guilds both asked me for OOE items for 3 days in a row (2 days on WW, once on Fishing).
WW asked me for a Credenza and windurstian tea set (using jacaranda lumber, which doesn't exist) ;
Fishing guild asked me for Trumpet shells, which cannot be fished without WOTG. I've been told that many users had also this item as a request at least once.

## Expected Behavior
Those items should not be requested since we're on an "era" server.

## Current Behavior
Items requested don't exist (= waste of players time ----> I've "lost" many GP while these days have passed without any possibility to gain GP).

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Possible Solution & Detailed Description
We need someone to fully review what items can be requested for every crafts and remove those that are not obtainable. 

## Characters
Noukon WW
Rose Fishing

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
Sorry this has affected you multiple days in a row. 

I have made a quick tracker here which lists every single item for GP turn ins. If anyone else would like to help us identify the OOE items on the list it would go a long way towards getting this resolved quicker. You simply need to select the drop down arrow in column I and select to Remove the item. Once we get this list complete we will validate and remove items from the Guild Point database. Thanks for reporting this issue.

https://docs.google.com/spreadsheets/d/1Cx41a2oqWsqfxRuD3wZGzi_Tf-Y1NJ_hQepUTkwuyzE/edit?usp=sharing

**Comment by Noukon** [comment]
Thanks Zierk

I did update the Fishing and Woodworking tabs

**Comment by zierk** [comment]
Thanks for the help. We took a look at the GP items and I think we got all the OOE item requests out.
