### ISSUE TITLE
Khimaira

### ISSUE THREAD

**Issue by Jeffrow419** [OmegaPrivateServer/issues#324]
## Summary
Khimaira seems to weak, also missing ability’s, Tourbillion, Dreadstorm, Plague Swipe, and seems to be missing double attack/triple attack job traits 

## Current Behavior
 Ability’s not working correctly and hp/def to weak

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
 https://ffxiclopedia.fandom.com/wiki/Khimaira

## Characters
 Jeffrow

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
Heh heh heh.
