### ISSUE TITLE
Unable to spawn Yowie in Kuftal tunnel after 100+ PH kills

### ISSUE THREAD

**Issue by Spear-omega** [OmegaPrivateServer/issues#326]
## Summary

After killing the 2 PH for the better part of the last 24 hours and I have been unable to spawn Yowie in Kuftal Tunnel. 
## Expected Behavior

It's a lottery spawn of the 2 PH Deinonychus located at H-8, even if the spawn rate was 1% I would have seen at least 1 spawn from 100+ kills of 2 lottery PH. Lottery rate is either way too low or not spawn able. 
## Current Behavior

After at least a hundred+ kills still no spawn. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Yowie?oldid=621363
https://ffxiclopedia.fandom.com/wiki/Lottery_Spawn?oldid=593850

## Possible Solution & Detailed Description

Please check that NM spawn rate is correct

## Characters

Spiro
## Steps to Reproduce

1. Go to Kuftal Tunnel and murder raptors until you have several stacks of raptor skins
2. cry salty tears of pain as carpal tunnel slowly eats your soul
3. kill more PH and no NM why u do dis?
4. 

## Context

Attempting to obtain Yowie skins to produce Austere/Penance gear for my SMN

**Comment by zierk** [comment]
Yeah looks like Yowie has a bunch of extra place holders outside the designated area. PHs have been adjusted and will take effect next patch. In the meantime try killing all the raptors in the I-8 area as well as the ones near and SE of Tachi Kasha NM spawn point. After the patch the PHs will be in the correct spot.
