### ISSUE TITLE
Sabotender Corrido spawns in Eastern Altepa Desert and is OOE

### ISSUE THREAD

**Issue by Spear-omega** [OmegaPrivateServer/issues#327]
## Summary

Witnessed Sabotender Corrido spawn in Eastern Altepa Desert, NM is out of Era and offers nothing useful. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters

Spiro

## Steps to Reproduce

1. 
2.
3.
4.

**Comment by zierk** [comment]
Thanks for the report.
