### ISSUE TITLE
Cover Does Not Work

### ISSUE THREAD

**Issue by thyrasik** [OmegaPrivateServer/issues#328]
## Summary
Paladin Ability Cover, does not work at all

## Expected Behavior
When standing in front of another player that generated Enmity, the PLD should be able to use Cover and take hits instead of the other player.

## Current Behavior
Does nothing at all. Player with Enmity still gets hit.

## Relevant Wiki Link 
https://ffxiclopedia.fandom.com/wiki/Cover?oldid=604428

## Characters
Rasik

## Context
Main component of the PLD's abilities. Helps to reduce party damage spread

**Comment by zierk** [comment]
Will likely make next patch, thanks for the report.
