### ISSUE TITLE
Cerberus stun resistance 

### ISSUE THREAD

**Issue by zierk** [OmegaPrivateServer/issues#329]
## Summary
"Cerberus's resistance to stun is incorrect. When his Magma Hoplon (stoneskin and blaze spikes) he is basically immune to stun. In retail he would never resist a stun from a BLM, DRK, or RDM/DRK with capped skill.

https://ffxiclopedia.fandom.com/wiki/Cerberus

- All TP attacks can be stunned.
- Does NOT build a resistance to Stun like other HNM.
- Can resist stun, but it is VERY rare.

Magma Hoplon - Stoneskin (~1000 damage) plus potent Blaze Spikes effect. (Spikes effect can be dispelled with Finale & Dispel, though high resist rate)

All the information from the wiki page showing it should be stunnable 99% of the time.

Thank you for your time in looking into this matter have a great day!"

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Cerberus

## Characters
Reported by Split.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
https://ffxiclopedia.fandom.com/wiki/Cerberus?oldid=633733

**Comment by Spear-omega** [comment]
Have 302 Dark skill and still get resisted 98% on Cerb

**Comment by zierk** [comment]
have you stunned him 100 times and only 2 landed?

**Comment by zierk** [comment]
I'll take a look at cerb later this week and try to get him in the next patch.

**Comment by Spear-omega** [comment]
49 times and only landed 1, including ES Stuns

**Comment by zierk** [comment]
Made a change, I played with it some. Let's see what happens. Can adjust if it's not enough.

**Comment by Jeffrow419** [comment]
We haven’t had any issues stunning Cerb, we have killed many times.

**Comment by Swerve256** [comment]
That does not mean it was correct =)

**Comment by Jeffrow419** [comment]
Right just saying we haven’t had issues was all

**Comment by Spear-omega** [comment]
That's weird cause the original report comes from Split. 


> ## Characters
> Reported by Split.
>

**Comment by zierk** [comment]
Well regardless, NM had a little too much INT imo. Looking deeper into the issue I found some other issues with the NM specifically. Overall the fight should be more retail accurate.
