### ISSUE TITLE
Kingdom Signet Staff doesn't apply Signet effect.. 

### ISSUE THREAD

**Issue by lvlrSocom** [OmegaPrivateServer/issues#331]
## Summary
Kingdom Signet Staff doesn't apply Signet effect.. 

## Expected Behavior
Once the signet staff is used, the player should attain signet!

## Current Behavior
I had another San d'Orian member attempt to gain Signet by using my Signet staff, and they were unsuccessful (player name; Chong). When I was running out of Signet, I attempted to use it (while still having signet on for another 30 minutes or so) and my signet was never refreshed.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
No relevant link needed here; the Item is just not working. 

## Possible Solution & Detailed Description
To just make the code apply the status change of signet or however that is accomplished heh..

## Characters
Chong is one member who has used my staff and couldn't attain Signet, and Katy attempted to use it also at one point in time. 

## Steps to Reproduce
1. Equip staff
2. Use staff
3. Do not get signet

## Context
N/A

**Comment by zierk** [comment]
Fixed. Will go live in the next patch.
