### ISSUE TITLE
Rage Timers for Roc / Simurgh not working..

### ISSUE THREAD

**Issue by lvlrSocom** [OmegaPrivateServer/issues#332]
## Summary
Upon the 20 minute timer being reached, there are no significant increases in damage or difficulty in these fights. 

## Expected Behavior
After 20 minutes is passed on these fights, similar to KA and Serket, the NM should Rage. 

## Current Behavior
They are not raging after 20 minutes.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Simurgh?oldid=620148

## Possible Solution & Detailed Description
Alter the code so that the NM is more difficult and has the proper battle mechanics reflecting a Raged monster. 

## Characters
Split/Habi

## Steps to Reproduce
N/A

## Context
N/A

**Comment by zierk** [comment]
Thanks for the report. Will go live in next bug fix patch.
