### ISSUE TITLE
Windy 9-2 Mission BC does not Work

### ISSUE THREAD

**Issue by Mstoughton1111** [OmegaPrivateServer/issues#333]
## Summary
After completing all of the required CS's and going to the BC area, you click the BC and nothing happens. A GM has responded to a ticket, so I felt it's time for a bug report.

## Expected Behavior
The BC should work, giving the option to enter the fight.

## Current Behavior
Does nothing. Can click all days, no response.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Moon_Reading-->

## Possible Solution & Detailed Description
Add the missing code so this BC works 

## Characters
Spankies, Finale, Upinyou

## Steps to Reproduce

1. Complete all 9-1 required CS's
2. Zone into Full Moon Fountain
3. Touch the BC
4. Get Angry

## Context
<! Unable to get rank 10 for over a month now, unable to get Federation Aketon. Was gonna be server first!!
  Taru wants to go fast !

**Comment by Swerve256** [comment]
Getting close Spankies =)
