### ISSUE TITLE
Xolotl's Danse Macabre will cause Attohwa Chasm to crash

### ISSUE THREAD

**Issue by Spear-omega** [OmegaPrivateServer/issues#334]
## Summary

On 2 different encounters when Xolotl used Danse Macabre the zone crashed and upon relogin he has despawned until the next night
## Expected Behavior

Should not crash, could be a problem with player charm that could effect other areas as well.

## Current Behavior

Xolotl readies Danse Macabre and zone goes down

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters

Spiro, Gunkbutter, Bungdup

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
think this is an issue when he charms a charmed player.

**Comment by Spear-omega** [comment]
No, it happens when any player is charmed, as soon as dance or gala macbre lands, zone crashes, there is no chance for a player to get charmed again. We've tested it to be sure its just the Charm, gala macrbe and danse macbre do not crash the zone if they have no effect.

**Comment by zierk** [comment]
Think we identified the reason for this. Working on a fix for the test server.

**Comment by zierk** [comment]
Got a fix merged. Will go live next bug patch.
