### ISSUE TITLE
Fishing Guild GP

### ISSUE THREAD

**Issue by GiggleCait** [OmegaPrivateServer/issues#337]
## Summary
Fishing guild NPC, GP turn in. 

## Expected Behavior
Various fish are not able to be cashed in for GP. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Bhefhel_Marlin?oldid=23104 

## Steps to Reproduce
1. Bhefhel Marlin
2. Red Terrapin
Surely others that are missing, it's been like this for months. 

## Context

Obtain GP items.

**Comment by zierk** [comment]
What is the player name you experienced this on?

**Comment by zierk** [comment]
Both of those fish are in the daily rotations for rank 5 fisherman. Does the NPC request the item from you and then does not let you turn them in? Need more details please. Screenshot would help as well next time it happens.

**Comment by GiggleCait** [comment]
@Meflab IGN. 

The NPC requests the fish and then it does not let me turn it in. Today was Trumpet shell which is OOE.

**Comment by zierk** [comment]
I had to undo some of the OOE changes we made in the patch, a bug fix patch will be coming to re-address. Trumpet Shells won't show up anymore.

**Comment by GiggleCait** [comment]
Ogre Eel - Cannot turn in fish for daily GP.

**Comment by GiggleCait** [comment]
![image](https://user-images.githubusercontent.com/16340017/90344181-fb8e8d00-dfcb-11ea-8287-9d151f98a97c.png)
![image](https://user-images.githubusercontent.com/16340017/90344185-106b2080-dfcc-11ea-8d9c-7d250ca8c9a5.png)

& Nada
