### ISSUE TITLE
WSNM Detonator ??? not in game

### ISSUE THREAD

**Issue by Swerve256** [OmegaPrivateServer/issues#338]
## Summary
Detonator NM doesn't seem to be in game

## Expected Behavior
??? Should Pop NM

## Current Behavior
There is no ???

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Shoot_First,_Ask_Questions_Later?oldid=634280

## Characters
Griptide Confirmed by Swerve

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
Thanks for the report. Got this fixed and working on test server. Will be working correctly next patch on live server.
