### ISSUE TITLE
Lord of Onzozo able to be Slept(spell+bolts) & Silenced. 

### ISSUE THREAD

**Issue by lvlrSocom** [OmegaPrivateServer/issues#339]
## Summary
LoO (Lord of Onzozo) is able to be slept by Bolts & Spells, as well as is able to be silenced, which shouldn't be!

## Expected Behavior
The NM should not be suspectable to sleep (in any facet) or silence. 

## Current Behavior
When attempting to Silence of Sleep the mob, until 20 minutes when he rages, there are no issues with sleeping and silencing.. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/Lord_of_Onzozo
https://ffxi.allakhazam.com/db/bestiary.html?fmob=580

## Possible Solution & Detailed Description
Update the code.

## Characters
Katy / Perry

## Steps to Reproduce
Cast Sleep, Shoot a Sleep Bolt, Cast Silence

## Context
OOE // incorrect mechanics

**Comment by zierk** [comment]
Thanks for the report.
