### ISSUE TITLE
BCNM 40 Under Observation - mobs are missing TP Regain

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#34]
In this BCNM there are 3 enemies, x2 Compound Eyes and x1 Sobbing Eyes. All enemies are expected to have an incredibly potent TP Regain effect. Please refer to both the Wiki entry and this 2009 video of the BCNM on retail for evidence of how powerful the effect is: 
- https://www.youtube.com/watch?v=vGX3dJMtgRo
- https://ffxiclopedia.fandom.com/wiki/Under_Observation
## Expected Behavior

All mobs should have TP Regain
## Current Behavior

None of the mobs use TP moves when they should be able to even without damaging the target for normal TP accumulation.
![Aeostage_2019 12 12_075605](https://user-images.githubusercontent.com/1855513/70728859-006da500-1cb7-11ea-9ed1-96066872abe3.png)

## Steps to Reproduce

1. Obtain Star Orb - item ID 1131
2. Go to Horlais Peak, trade item
3. Aggro mobs by hitting them or casting a spell
4. Enable god mode

## Context (Environment)
The above was tested on the staging environment. 
I tested this BCNM after a user in discord reported an issue with another BC. The fight is intended to be difficult because the eyes spam their TP moves, thus making certain jobs preferred over others, and therefore making it harder to obtain valuable items like PCC.

**Comment by OmegaBison** [comment]
Any speculation on how much TP/tick we should give these guys?

**Comment by dvalderrama89** [comment]
I found [another video](https://www.youtube.com/watch?v=JndRb6OAK-Q) from 2010 and it seems like the mobs are gaining 800 TP approximately every 10 seconds, which is about 3.33 ticks. I'd say to start we can playtest with 250 TP/tick and see how it feels.

**Comment by dvalderrama89** [comment]
Fixed. This will go out with the next patch.
