### ISSUE TITLE
NM ToDs not preserving through zone crashes. 

### ISSUE THREAD

**Issue by LightOmegaDark** [OmegaPrivateServer/issues#343]
## Summary
NM ToDs don't preserve themselves through zone crashes. 

## Expected Behavior
NM ToDs should be preserved through zone crashes. 

## Current Behavior
Zones crash and ToDs get reset based on when the zone goes back up. 

## Characters
Dark & Light

## Steps to Reproduce
1. Kill a NM like simurgh or Roc.
2. Get the ToD.
3. Go out there the next day and wait the entire window.
4. Realize it isn't popping due to a zone crash. 

## Context
On multiple occasions, i've seen NMs not pop in accordance to their ToD for the prior kill. Its affected me in the sense of wasting three hours every time it happens, and having no way to tell how long a zone's been up for, i've continually stood there with the false assumption that it was going to pop.

**Context for a proper solution**: Put a system in place that preserves NM ToDs, or add something to the website that shows how long each zone's been up for.

**Comment by Swerve256** [comment]
This is normal actually for this game. We will have to discuss the possibility of putting this info on the website or not.

**Comment by zierk** [comment]
We have been experiencing some zone crashing recently, it is not normal for zones to crash and we are investigating and fixing crashes daily. Hopefully this will not be an issue in the near future.

**Comment by zierk** [comment]
We may or may not decide to put an uptime counter on the website. It's quite possible though. Some NMs with longer CDs will eventually get preserved through crashes but we are not going to implement this for every single NM.
