### ISSUE TITLE
Shield Bash range is too short on large mob models

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#344]
## Expected Behavior

Should be the same range as melee attacks

## Current Behavior

Works inconsistently on large model mobs such as wyrms and toau kings

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Shield_Bash

## Possible Solution & Detailed Description

Extend the range of bash in abilities table

**Comment by Ashenbubs** [comment]
I believe the same is for most close range abilities - Steal/Mug being the two I can think of the most that I have issues with using.

Would also be worth checking DRK's Weapon Bash and SAM's Blade Bash (merited) abilities.

I don't know if that's just as-is standard, as I don't remember if I had to manually unlock the camera and move into the enemies hit-box in retail, but it is very irritating to do on large enemies - Behemoth, Mantas, Sky Gods, any large model.

**Comment by zierk** [comment]
Thanks. Will look into it.

**Comment by zierk** [comment]
This is going to come down to individually adjusting larger mobs. Their "mobsize" variable in the database is how the game determines how far you are from the center of the mob's hitbox. We can adjust this size var on large mobs so the game thinks you're within range. For that, i will need a list. I will automatically check all of the larger boss mobs (sky, sea, kings) but if you find more mobs please let us know so we can test/adjust.

**Comment by Swerve256** [comment]
Adjusted the distance of the skill probably by too much but it be ok. I also adjusted the ones that ashenbubs spoke about in the comment
