### ISSUE TITLE
White mage AF quest NM

### ISSUE THREAD

**Issue by Beveled47** [OmegaPrivateServer/issues#348]
## Summary
The NM "Altedour" is way to weak

## Expected Behavior
Altedour is suppose to have 16k-17k HP

## Current Behavior
Altedour was killed after dealt 2379

## Relevant Wiki Link 
https://ffxiclopedia.fandom.com/wiki/Altedour_I_Tavnazia

## Characters
Beveled

**Comment by Swerve256** [comment]
Tested multiple fights and he had 15k hp
