### ISSUE TITLE
Recipe Missing: Irmik Helvasi (GP required item)

### ISSUE THREAD

**Issue by CosmicForge** [OmegaPrivateServer/issues#349]
## Summary

The recipe for the food item Irmik Helvasi seems to be missing.

## Current Behavior

Attempting this recipe gives error message: "Synth canceled. That combination of materials cannot be synthesized."

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Irmik_Helvasi?oldid=630201

## Steps to Reproduce

1.
2.
3.
4.

## Context

This cooking item is also requested by the cooking guild NPC for guild points.

**Comment by zierk** [comment]
Will need to research this. It's possible all the AoE foods are disabled for a reason. Some recipes are also quested.

**Comment by zierk** [comment]
https://ffxiclopedia.fandom.com/wiki/A_Taste_of_Honey

Do the quest.
