### ISSUE TITLE
BCNM 40 Royal Jelly does not appear in the list when trading a Star Orb to the BC

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#35]
Waughroon Shrine should offer 2 battles to select from, The Worm's Turn and Royal Jelly. Please refer to the wiki entry for all battles related to Star Orbs.
- https://ffxiclopedia.fandom.com/wiki/Star_Orb
## Expected Behavior

The list should have Royal Jelly
## Current Behavior

The list is missing the battle Royal Jelly and there is no alternate way to enter the battle.

![Aeostage_2019 12 12_073731](https://user-images.githubusercontent.com/1855513/70729291-c81a9680-1cb7-11ea-9ee5-ee2f656ef943.png)

## Steps to Reproduce
1. Obtain a Star Orb, item ID 1131
2. Go to Waughroon Shrine
3. Trade the Star Orb to the Burning Circle

## Context (Environment)
A member in discord reported the issue. Certain BCNMs are easier depending on the party setup, and also drop different items, so this is impacting players who want specific items from Royal Jelly or do not have the job setup for other BCNMs.

**Comment by OmegaBison** [comment]
Combat mechanics & loot are not yet implemented for this battlefield.

**Comment by dvalderrama89** [comment]
Closing as not a bug.
