### ISSUE TITLE
Dynamis Dreamlands NM drop rates ratio are not proprotional. It's 3:1 Jades, when it should be more like 30/30/40 zone specific.

### ISSUE THREAD

**Issue by Mstoughton1111** [OmegaPrivateServer/issues#350]
## Summary
After Several runs of Dynamis on Omega and the test server, there is a huge disproportion of Jades to Bynes and Silvers in dynamis. For every 3 Jades that drop off NM's, only 1 of either M. Silver or 100 Byne bill will drop. 

## Expected Behavior
The NM's should have a drop rate of around 30%,30%,40% respectively on currency, and favoring one specific one only slightly based on the region you are in.
## Current Behavior
Kill dragons nonstop, get 3 Jade shells, then get either 1 M silver, then 1 100 Byne, then back to getting another 3 Jadeshells.

## Relevant Wiki Link 
https://ffxiclopedia.fandom.com/wiki/Dynamis_-_Qufim  ,  https://ffxiclopedia.fandom.com/wiki/Dynamis_-_Valkurm,  https://ffxiclopedia.fandom.com/wiki/Dynamis_-_Buburimu
## Possible Solution & Detailed Description

The code will indeed show that there is a 3:1 ratio for J.Shells in all 3 zones, a simple correction to the loot table will solve this issue.
## Characters
Spankies, Anabb

## Steps to Reproduce

1. Go into Dynamis Dreamlands
2. Kill all 5 time extensions
3. Start killing dragons
4. Start seeing WAY TOO MANY Jadeshells.

## Context

It's stopping us from getting relics, if we only get 1 type of currency all the time.
We have spreedsheet date of a large sample size that will confirm this. Please help!

**Comment by zierk** [comment]
Thanks for the report. This will be addressed when we do the balance pass on Dynamis.
