### ISSUE TITLE
Yaa Haqa the Profane loot table appears to be incorrect.

### ISSUE THREAD

**Issue by DeltaFFXI** [OmegaPrivateServer/issues#351]
## Summary
Yaa Haqa the Profane NM in Castle Oztroja has an incorrect drop/loot table.

## Expected Behavior
Yaa Haqa the Profane NM in Castle Oztroja is supposed to have a guaranteed drop of either a Frost Robe or Earth Doublet.

## Current Behavior
Currently it appears to be possible that the NM does not drop either item. Attached is a screenshot showing the NM was killed and did not drop any items:
![yaa](https://user-images.githubusercontent.com/68086791/90985433-a27da680-e541-11ea-91a7-32017f2335d4.PNG)
I have not yet experienced the Earth Doublet dropping so it's possible that the item is not part of the loot table entirely (though I only have about a dozen kills which is a fairly small sample size).

## Relevant Wiki Link 
https://ffxiclopedia.fandom.com/wiki/Yaa_Haqa_the_Profane?oldid=634254

## Possible Solution & Detailed Description
Verify that the loot table for this NM is correct.

## Characters
Sigma

## Steps to Reproduce
1. Kill NM until no items drop

## Context
This issue will affect user's ability to obtain drops from this NM.

**Comment by zierk** [comment]
The drop rates were incorrect. Fixed. Will take effect next patch.
