### ISSUE TITLE
Raptor Strap desynth missing

### ISSUE THREAD

**Issue by Thayos** [OmegaPrivateServer/issues#352]
## Summary
 Unable to desynth Raptor Straps

## Expected Behavior
 Desnyth Raptor Strap to yield 1 Raptor Skin under NQ, 1 under HQ and 2 under HQ2 when using a Lightning Crystal.

## Current Behavior
 Synthesis Canceled message stating cannot be sythnesized

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

 https://ffxiclopedia.fandom.com/wiki/Raptor_Strap

## Characters
 Thayos

## Steps to Reproduce

1. Use Lightning Crystal
2. Add Raptor Strap into materials list
3.
4.

**Comment by zierk** [comment]
Thanks for the report however it looks like the desynth recipe wasn't added until 2010. 
https://ffxiclopedia.fandom.com/wiki/Raptor_Strap?oldid=583943
