### ISSUE TITLE
Kuftal Digger Aggro

### ISSUE THREAD

**Issue by LouAndLouie** [OmegaPrivateServer/issues#354]
## Summary

Currently, the Kuftal Digger in Kuftal Tunnel are aggressive towards players unless the player has Sneak active.  

## Expected Behavior

Kuftal Digger should not be aggressive towards players that are running by without Sneak.

## Current Behavior

Kuftal Digger aggro to sound.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

ZAM link that has Kuftal Digger as "Not Aggro."  
https://ffxi.allakhazam.com/db/bestiary.html?fmob=945

Link that shows Kuftal Digger not having the "A" tag for Aggresssive under the normal monsters in area.
https://ffxiclopedia.fandom.com/wiki/Kuftal_Tunnel

## Possible Solution & Detailed Description

Change Kuftal Digger aggro behavior only.  Everything else seemed in line with era.

## Characters

Lou
## Steps to Reproduce

1. Run down the area that have Kuftal Digger without sneak or remove sneak when nearby.
2. Aggro one and then have it link with the other ones.
3. Eat various spells such as Stonega III and Quake.
4. Homepoint.

## Context

Ran through Kuftal Tunnel to look at possibly getting a Phantom Tathlum from Phantom Worm.  Does not seem easily feasible.

**Comment by zierk** [comment]
Easy fix. Will take effect next patch.
