### ISSUE TITLE
Sabotender Bailarina

### ISSUE THREAD

**Issue by Simseru** [OmegaPrivateServer/issues#358]
![DuneBoots](https://user-images.githubusercontent.com/59345270/91670763-62dd2e80-eaee-11ea-97e8-d00247bbb7e5.PNG)

## Summary

Sabotender Bailarina fight is too easy and also dropped 2x Dune Boots. Bailarina does not appear to be using multiple TP moves per TP fill.  
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters

Kongol & Indora

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
i'm fixing the drop table now. seems like it was doubled. the NM difficulty will be addressed in a future patch.

**Comment by zierk** [comment]
Fixed in the next patch.
