### ISSUE TITLE
Faded Promises is not working

### ISSUE THREAD

**Issue by kuho23** [OmegaPrivateServer/issues#36]
Faded Promises quest is not working

## Expected Behavior
I am max fame rank in norg and 20+ninja i should be activating the quest when talking to Romualdo - Metalworks (K-9). https://ffxiclopedia.fandom.com/wiki/Faded_Promises

## Current Behavior
Talking to Romualdo - Metalworks (K-9) i do not get a CS with the following quest i get nothing at all. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Quest has been implemented. Will go live with next patch.
