### ISSUE TITLE
King Vinegarroon

### ISSUE THREAD

**Issue by cwkgendron** [OmegaPrivateServer/issues#363]
## Summary
King Vinegarroon (KV) has at least 2 issues where it is not working correctly. 

## Expected Behavior
1. KV should only spawn after 21+ hours at the start single (estimated 10%~ chance) and double (100% chance) earth weather
2. KV should be passive and not aggro

## Current Behavior
1. KV spawns regardless of if earth weather is present after 21+ hours https://imgur.com/sweuNtQ
2. KV will aggro if you are not on a chocobo

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://ffxiclopedia.fandom.com/wiki/King_Vinegarroon
There are no wiki entries prior to July 15, 2009, however the wiki entry itself notes that KV was updated in December 2008, which should prove that the entry is valid. 

## Possible Solution & Detailed Description

Under current conditions, it is difficult to track spawns and despawns due to the mechanic of KV despawning when no weather is present. You cannot rely on the weather NPC to track possible spawns since KV can currently incorrectly spawn without weather.

## Characters
Riiko

## Steps to Reproduce
1. Took screenshots on multiple days of KV spawning without weather
2. Ran up to KV and was attacked
3.
4.

## Context
Unable to correctly track TOD due to KV being able to spawn outside of earth weather. Trying to track TOD in order to put together a group to defeat KV and obtain drops.

**Comment by zierk** [comment]
Kreutzet has working weather spawn behavior. Use as a reference to correct KV.

**Comment by zierk** [comment]
KV has been overhauled. Will be fixed in next patch.
