### ISSUE TITLE
Crafts Above Skill Level 60

### ISSUE THREAD

**Issue by DongerSlayr** [OmegaPrivateServer/issues#364]
## Summary
After you hit level 60 you get 40 levels to distribute among the other crafts you also have above level 60. Meaning you can get every single craft up to 60 without any issues, but post 60 you have 40 levels to distribute.

## Expected Behavior
On a single character, it should be impossible to fully specialize in multiple crafts. Each character has a pool of 40 points he can allocate to his crafts above 60. So for example, one could be 100 in a craft and 60 in the rest. Or, 80/80 and 60 in the rest. Or 75 in 2 crafts, 70 in a third, and so-on.

## Current Behavior
It appears a character can have more than 40+ points allocated into any craft past 60. Players are able to T2 certain items they shouldnt be allowed to. 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
https://classicffxi.fandom.com/wiki/Category:Crafting

## Possible Solution & Detailed Description
Bring out the Cap Hammer!

## Steps to Reproduce
https://xi-omega.com/home/players/search

## Context
Here's just an example of a player having more than the 40 point distributed. 
<img width="416" alt="Annotation 2020-09-01 123352" src="https://user-images.githubusercontent.com/70603907/91898679-ef9ffd80-ec50-11ea-9918-0c7fe5016985.png">

**Comment by Swerve256** [comment]
Yes we are aware and have a fix planned. Currently this is the only player with this type of over craft skills. The others reconciled theirs already

**Comment by zierk** [comment]
https://github.com/OmegaPrivateServer/issues/issues/251
