### ISSUE TITLE
Desperate blows

### ISSUE THREAD

**Issue by elvet20** [OmegaPrivateServer/issues#366]
## Summary
Desperate blows doesn't show up under job traits not sure if it's active even when merited

## Expected Behavior
Desperate blows 1 2 and 3 should be shown under job traits by lvl 45

## Current Behavior
Desperate blows not found 

## Relevant Wiki Link 

https://classicffxi.fandom.com/wiki/Desperate_Blows

## Possible Solution & Detailed Description

List job trait desperate blows in job trait window 

## Characters
Elvet

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Updated the content tag for desperate Blows
