### ISSUE TITLE
Unable to use Pet abilities

### ISSUE THREAD

**Issue by DerrickJFoster** [OmegaPrivateServer/issues#367]
## Summary
On occasion pet abilities wont trigger due to mob "already being claimed" when in a party, solo or duoing. I've noticed it tends to happen when fighting multiple mobs (aggro or on purpose) or while more than one person are in a party together.

## Expected Behavior
ability triggers

## Current Behavior
ability doesn't trigger and texts states the mob has already been claimed

## Relevant Wiki Link 
N/A

## Possible Solution & Detailed Description
system is registering that the mob has been already claimed so it is possible the mob is somehow outside of party while also in party?

## Characters
Mowgli, Cboomtv, FknSteve

## Steps to Reproduce
Steps provided are specific to Beastmaster, however FknSteve has had the same issues on Puppetmaster.
1. Claim multiple mobs and fight (or in party situations)
2. Build tp on pet
3. Use "Ready" ability

## Context
While soloing it has prevented my CC from using abilities which has on occasion almost gotten me killed along with other people in duoing situations. Causes DPS slowdown in party situations and/or deaths.

**Comment by CosmicForge** [comment]
There used to be a work around but for some reason it no longer works: After you get the error "Monster is already claimed" when issuing a pet command, you could "heel" or disengage, then have the pet "fight" or attack again, and commands would work.

Either way the error always seems to happen when there are links, esp when they are linked onto the pet itself. I'll try to test out more scenarios myself to see if I can narrow it down

**Comment by Lilpeoples** [comment]
So while in the Maat fight I encountered the same thing. I could not even reward my pet to heal it. End results I'll be going back to fight Maat again. I don't know how to upload photos
