### ISSUE TITLE
Sweet Lizard Recipe Is not working properly

### ISSUE THREAD

**Issue by Sephiroaf** [OmegaPrivateServer/issues#368]
## Summary

After putting the right materials it tells this

Synthesis canceled. That combination of materials cannot be synthesized.

## Expected Behavior

It should craft Sweet Lizard after using a Fire Crystal with 1x Honey and 1x lizard tail

## Current Behavior

It doesnt allows you to craft it

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Sweet_Lizard?oldid=653723
## Characters

Ardbert

## Steps to Reproduce

1. Use Fire crystal
2. 1x honey 1x Lizard tail on ingredients
3. Ok
4.

## Context

This affected me since i wanted to start skilling up cooking with the materials i got while leveling in the early zones

**Comment by Swerve256** [comment]
Added
