### ISSUE TITLE
Bastok Mission Magicite not rewarding rank 5 after receiving airship pass.

### ISSUE THREAD

**Issue by Craaizy** [OmegaPrivateServer/issues#37]
## Expected Behavior
you recieve airship pass from archduke and go back to your embassy and talk to the receptionist once you do this you are rewarded 10k and rank 5....mission 5-1 starts automatically.

## Current Behavior
after receiving airship pass i talk to the receptionist and he tells me "Welcome to the Embassy of Bastok. Stop by if you ever find yourself in need during your stay in Jeuno"....no cutscene no rank up. i've tried clicking on the ambassadors door, i've gone back to bastok and talked to lucius naji the president and gate guards...no cutscene or rank up from anyone.

## Possible Solution
possibly not registering that i'm completing part of the mission like it does with other missions that have issues.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
trying to hit rank 5

**Comment by OmegaBison** [comment]
Fixed. Will go live with next patch.
