### ISSUE TITLE
Khim Elemental Resistance is WRONG !

### ISSUE THREAD

**Issue by Mstoughton1111** [OmegaPrivateServer/issues#370]
## Summary
Khim Elemental Resistance is just WRONG

## Expected Behavior
You can't Nuke down Khim with 3 blms and expect to win lol.

## Current Behavior
Freeze 2 and Burst 2 Doing 1200 - 1300 Damage on Khim.

## Relevant Wiki Link 
Resistant to Elemental Magic, but susceptible to melee and Avatars.

https://ffxiclopedia.fandom.com/wiki/Khimaira

## Possible Solution & Detailed Description
Makie it resistance to Nukes so its not a Genbu :)
## Characters
I'll be nice :)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zierk** [comment]
Well, if you have hard data to support what the exact resist % should be i'd be interested to see it.

**Comment by zierk** [comment]
If not it will continue to be tested and fine tuned until it's where it needs to be.

**Comment by Mstoughton1111** [comment]
https://github.com/OmegaPrivateServer/issues/issues/370#issuecomment-690845858

Sure thing.... Blizzard 4 and Blizaga III not even cracking 100 damage :)

**Comment by Mstoughton1111** [comment]
https://youtu.be/3925tpou-es

**Comment by zierk** [comment]
> https://youtu.be/3925tpou-es

From your own source video:
Minute 1:49: Freeze 2 1586 dmg
![image](https://user-images.githubusercontent.com/8040548/92957763-c0b83180-f471-11ea-8c62-9f065c5a800e.png)

Minute 1:59: Freeze 2 1730 dmg
![image](https://user-images.githubusercontent.com/8040548/92957932-0d037180-f472-11ea-8b39-14cf92deb932.png)

You're right, Blizz does seem to be a lot lower, in the double digits. Freeze 2 hitting for 1500+ in your video. Scrolling around, the people casting blizzard 4 appear to be blms, but maybe they aren't. Further information and testing is required to fine tune it.
