### ISSUE TITLE
Bi'Gho Headtaker does not drop items as expected, should alternate drops between power crossbow and plantbane

### ISSUE THREAD

**Issue by Spear-omega** [OmegaPrivateServer/issues#371]
## Summary
Bi'Gho Headtaker does not alternate drops, either Plantbane or Power Crossbow should drop 100% of the time

## Expected Behavior
Headtaker should drop either Power Crossbow or Plantbane 

## Current Behavior
In 3 kills I have seen him drop both Plantbane and Power crossbow on one kill, nothing another kill and just a Quadav helm the third kill.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

https://ffxiclopedia.fandom.com/wiki/Bi%27Gho_Headtaker?oldid=569902

## Possible Solution & Detailed Description
Change loot table to include either Power Crossbow or plantbane 100% of the time. 

## Characters
Spiro

## Steps to Reproduce
1. Kill Brass Quadav at spawn location
2. Wait for Bi'Gho Headtaker to spawn
3. Kill Headtaker
4. Profit???

## Context
Unable to obtain Plantbane or Power Crossbow

**Comment by Swerve256** [comment]
The Drop rates have been adjusted, but it is not 100% one or the other. It is a Myth
