### ISSUE TITLE
Lost Key Items when switching from one guild to another

### ISSUE THREAD

**Issue by Spear-omega** [OmegaPrivateServer/issues#372]
## Summary
Lost Key Items when switching from one guild to another, changed from WW to Cooking guild and lost Lumberjack KI

## Expected Behavior
Expect to not lose KI

## Current Behavior
Lost Lumberjack KI

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)
No relevant article

## Possible Solution & Detailed Description
Not lose KIs when you switch guilds

## Characters
Drueth

## Steps to Reproduce
1. Swap Guilds
2. Lost KI
3.
4.

## Context
Lost a KI

**Comment by Swerve256** [comment]
Was this a one time thing or everyone loses when swapping?
