### ISSUE TITLE
Centurio X-I

### ISSUE THREAD

**Issue by Gerschwinn** [OmegaPrivateServer/issues#373]
The place holders are not respawning at 5 minutes as they should. The seem to be at 15 minutes.## Summary

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Thayos** [comment]
https://ffxiclopedia.fandom.com/wiki/Centurio_X-I?oldid=640934

**Comment by Swerve256** [comment]
Expected Thanks Thayos
