### ISSUE TITLE
Dangruf Wadi has level 85 + mobs 

### ISSUE THREAD

**Issue by Pieplate** [OmegaPrivateServer/issues#38]
Dangruf Wadi has areas where mobs are out of era
## Expected Behavior

Should have mobs that are no higher than level 30 
## Current Behavior

https://ffxiclopedia.fandom.com/wiki/Dangruf_Wadi
is a list of all mobs in this zone to current retail

## Possible Solution

http://ffxi.somepage.com/mobdb/list.php?zone=42
list of mobs that should be in era.

## Steps to Reproduce

1.
2.
3.
4.

## Context

Unable to pop NM's in the areas affected with high level mobs

**Comment by OmegaBison** [comment]
Merging with https://github.com/OmegaPrivateServer/issues/issues/12
