### ISSUE TITLE
NM not spawning as intended

### ISSUE THREAD

**Issue by Beveled47** [OmegaPrivateServer/issues#380]
## Summary
Pyuu the Spatemaker is an NM that does not appear to be in game
## Expected Behavior
Pyuu should be a timed spawn 

## Current Behavior
Does not spawn

https://ffxiclopedia.fandom.com/wiki/Pyuu_the_Spatemaker

## Characters
Beveled

**Comment by Thayos** [comment]
I think he wasn't added till 2009

**Comment by Swerve256** [comment]
Currently OOE.
