### ISSUE TITLE
(COR Rolls) Healer's Roll (WHM) effect isn't era accurate

### ISSUE THREAD

**Issue by Noukon** [OmegaPrivateServer/issues#382]
## Summary

Healer's Roll effect isn't era accurate and gives cure potency received+ instead of hMP.

## Expected Behavior

Healer's Roll should give hMP effect.

## Current Behavior

The roll gives Cure Potency Received+.

## Relevant Wiki Link 

https://ffxiclopedia.fandom.com/wiki/Healer%27s_Roll?oldid=463127

## Characters

Everyone

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Needs some testing prior to release

**Comment by Swerve256** [comment]
Will be in next update
