### ISSUE TITLE
Inability to use Bst familiar ability

### ISSUE THREAD

**Issue by Lilpeoples** [OmegaPrivateServer/issues#386]
## Summary
Can't use the bst ability familiar even after calling a new beast pet out, during fighting a mob and without a mob.

## Characters
Lilpeoples

**Comment by Swerve256** [comment]
So you can only use it 1 time total or not at all?

**Comment by Lilpeoples** [comment]
No you can not.

**Comment by Swerve256** [comment]
Fixed will be pushed next update
