### ISSUE TITLE
Return to Delkfutt's Tower not working

### ISSUE THREAD

**Issue by Lilpeoples** [OmegaPrivateServer/issues#388]
## Summary
While doing ZM8 I'm unable to get the Cutscene when I enter the zone to do the fight in Upper Delkfutt's Tower and unable to do the fight.

## Relevant Wiki Link 
https://ffxiclopedia.fandom.com/wiki/Return_to_Delkfutt%27s_Tower

## Characters
Lilpeoplex

**Comment by Swerve256** [comment]
This is a GM ticket as most people have no issue with this

**Comment by Lilpeoples** [comment]
What do you mean? I have the mission status and when I zoned into the area I did not get my Cutscene and I could not trigger the fight.

**Comment by Swerve256** [comment]
I mean request a GM ticket to see what happened. The mission is coded correctly.  Most people miss a CS

**Comment by Spear-omega** [comment]
thanks swerve!
