### ISSUE TITLE
Unlocking Bard/song runes parchment trade

### ISSUE THREAD

**Issue by Nageki-noki** [OmegaPrivateServer/issues#39]
## Expected Behavior

Trading the parchment should give the key item Poetic Parchment.

## Current Behavior

Unable to trade or recieve the key item needed for the bard quest to unlock.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
I checked on your character. It looks like you skipped the part in the questline where you need to speak with Bki Tbujhja in Lower Jeuno.

Please comment if this doesn't fix the issue and I'll re-open the ticket.

**Comment by Nageki-noki** [comment]
Alright,i was able to get it unstuck,however,i did notice that it let me replay the flagged scenes again.the same thing happened when unlocking Beastmaster as well.I'm not sure what caused this but it was able to be solved.
