### ISSUE TITLE
Fishing ~ can't fish in port windy or might be cant fish at all 

### ISSUE THREAD

**Issue by giapper** [OmegaPrivateServer/issues#393]
![Giapper_2020 11 18_234500](https://user-images.githubusercontent.com/65816465/99553177-cd6c7f00-29f8-11eb-806f-a1bc1f107048.png)

try to fish but some weird comment pop up and nothing happen then auto reel my line.

**Comment by DongerSlayr** [comment]
Yeah Swerve mentioned that digging and fishing aren't working right now. It's on #announcement

**Comment by Swerve256** [comment]
Fishing is working but Dialog is incorrect ATM
