### ISSUE TITLE
Strides towards removing everything pass ToAU

### ISSUE THREAD

**Issue by Hugocutt** [OmegaPrivateServer/issues#4]
Hopefully implications of removing everything pass ToAU is in progress and will be implemented asap. 
 
## Expected Behavior
 Earlier we can remove items even early lvl gear that's out of era the better and correctly fix and remove all listings on Auction House to 75 cap gear and items that were associated with ToAU era content. 

## Possible Solution
 I know Bison would be aware of this and hoping this would be the endgame to get everything to ToAU 75 cap era standards but the sooner the better as some gear that is out of era even at lower levels is very superior.

## Steps to Reproduce
 

1. 
2.
3.
4.

## Context (Environment)
 this the reason i joined omega is to play on a fresh 75 ToAU content server that was advertise by omega  streamers as to the reason why i decided to join the server and to help it grow.

**Comment by OmegaBison** [comment]
This is a very broad task and it's very difficult for any one individual to track down everything OOE. We're going to need a handful of content/playtesting team members to tackle this effectively.

In the meantime, if there's anything that's exceptionally gamebreaking I can make one-off adjustments.
