### ISSUE TITLE
Whitegate cant exit in to Wajaom or ride chocobo

### ISSUE THREAD

**Issue by DongerSlayr** [OmegaPrivateServer/issues#408]
## Summary
Tried exiting into Wajaom and was told "do I want to exit into Ronfaure?" Went to ride chocobo he talking about Selling me goldsmithing supplies. 
![img_20201119_093415](https://user-images.githubusercontent.com/70603907/99702512-b8b8d700-2a4a-11eb-889d-a9e6987f1105.png)
![img_20201119_092710](https://user-images.githubusercontent.com/70603907/99702519-ba829a80-2a4a-11eb-8db7-5174d22f3357.png)

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
I tested and it works. Please update the client again just incase you have those Dank files
