### ISSUE TITLE
NMs are not using 2 hour ability 

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#41]
## Expected Behavior

Various NMs should use 2 hour abilities 
## Current Behavior

No Notorious monsters are using 2 hour abilities 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Before I start digging around, do you have a specific example where you've seen this?

**Comment by OmegaBison** [comment]
> Mee Deggi the punisher
> Domi the gallant
> And nearly every other NM in the game including 55 cap NMs

**Comment by OmegaBison** [comment]
2hr abilities have been added for Deggi & Domi. Fixes will go live with the next patch.

If you find any other specific 2hrs that are missing please open up a new ticket.

Thanks.
