### ISSUE TITLE
Chat doesn't work in Cpnt Landing 

### ISSUE THREAD

**Issue by astelmon** [OmegaPrivateServer/issues#414]
## Summary
Chat doesn't work in Cpnt Landing 

## Expected Behavior
Chat should work 

## Current Behavior
Chat doesn't work in Cpnt Landing 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters
Evolve

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Temp fixed until final fix is in place
