### ISSUE TITLE
Attohwa Chasm route to mountain black smoke permanently blocking 

### ISSUE THREAD

**Issue by giapper** [OmegaPrivateServer/issues#418]
## Expected Behavior
will come down after a few min 

## Current Behavior
they dun ever come down blocking the route up 
( first black smoke going up the slope) 

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Gotsz** [comment]
+4 still happening after trying to finish CoP 3-3 to climb. First miasma never stops
