### ISSUE TITLE
Hasim (Lower Jeuno merchant) missing spells

### ISSUE THREAD

**Issue by Anabeatrizbarros** [OmegaPrivateServer/issues#42]
## Expected Behavior
 Hasim should have Barsleepra--he is the only merchant in the game who sells the spell, and apparently it does not drop anywhere.

## Current Behavior
 Hasim does not have Barsleepra and perhaps other spells.

## Possible Solution
 add spells to Hasim

## Steps to Reproduce
 check Hasim's spells in lower jeuno

1.
2.
3.
4.

**Comment by dvalderrama89** [comment]
It looks like the npcs in that shop have their lists set to the August 5th, 2015 list. See Susu's history page for notes on the 2015 entry https://ffxiclopedia.fandom.com/wiki/Susu?action=history

Susu used to sell Barsleepra (among other spells) before 2015.

**Comment by OmegaBison** [comment]
I previously updated Hasim's list to 2008 but never updated Susu's. Susu carries barsleepra. Both are set to 2008 lists now. Changes will go live with the next patch.
