### ISSUE TITLE
Wyverns' Breathes attack replaced by BloodPact: Rage

### ISSUE THREAD

**Issue by Noukon** [OmegaPrivateServer/issues#422]
## Summary
Title
My wyvern doesn't use any breath attack anymore. Instead, she tries to use Blood Pact: Rage with no effect.
Edit: she uses only Ramuh bloodpact, from normal to SP (no damage nor animation) 

## Expected Behavior
Elemental breathes are expected.

## Current Behavior
Use of BP: Rage
See SS
[<a href="https://ibb.co/cb9yFKj"><img src="https://i.ibb.co/DGF1CPZ/chaotic-strike.png" alt="chaotic-strike" border="0"></a>](url)
[<a href="https://ibb.co/6ZrXtQB"><img src="https://i.ibb.co/ky5mDZ1/thunderstorm.png" alt="thunderstorm" border="0"></a>](url)

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters
Noukon

## Steps to Reproduce
1. WS on DRG
2. See the BP: Rage from the wyvern
3. 
4.

**Comment by Swerve256** [comment]
What in the loldrg is going on here

**Comment by Swerve256** [comment]
thats the new drg/smn lol
