### ISSUE TITLE
COR rolls missing as SJ

### ISSUE THREAD

**Issue by Noukon** [OmegaPrivateServer/issues#423]
## Summary
Using /COR, no Corsair's Roll as lv. 10+

## Expected Behavior
Should have access to Corsair's Roll atleast.

## Current Behavior
Only Double-Up as JA available.

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Characters
Noukon

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Spear-omega** [comment]
They are missing as main job too

**Comment by Swerve256** [comment]
Checked this it is OK
