### ISSUE TITLE
Korroloka Tunnel Entrance

### ISSUE THREAD

**Issue by mpinholster** [OmegaPrivateServer/issues#429]
## Summary
When I try to enter Korroloka Tunnel via theh gate in Zeruhn Mines...the door won't open in the cut scene.

## Expected Behavior
It should let me in

## Current Behavior
I am denied

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Tested and it works as expected. May need to update game client
