### ISSUE TITLE
WHM Tranquil Heart job trait not appearing in list

### ISSUE THREAD

**Issue by Anabeatrizbarros** [OmegaPrivateServer/issues#43]
WHM is supposed to get the Tranquil Heart job trait at level 21 according to this ffxiclopedia:

https://ffxiclopedia.fandom.com/wiki/Tranquil_Heart

## Expected Behavior
 WHM should have tranquil heart

## Current Behavior
 I am a level 39 WHM and I do not see Tranquil Heart in my list of job traits

## Possible Solution
 add tranquil heart job trait

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dvalderrama89** [comment]
Tranquil Heart is a White Mage job trait that was added in the May 10th, 2011 version update according to the Japanese wiki: http://wiki.ffo.jp/html/23693.html

Since 2011 is post ToAU, Tranquil Heart is considered out of era.
