### ISSUE TITLE
Pickaxe, Gysahl Greens lost in translation...they were previously stacked to 99 are now at 12.

### ISSUE THREAD

**Issue by OmegaZen** [OmegaPrivateServer/issues#435]
## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
They were always stacked to 12 in Omega previously but I may add that as QoL
