### ISSUE TITLE
Dynamis CoP Zones Boss not popping

### ISSUE THREAD

**Issue by Eragon75** [OmegaPrivateServer/issues#437]
## Summary
Trading item to ??? does not do anything.

## Expected Behavior
When you trade the juju the boss should pop.

## Current Behavior
nothing happens

## Relevant Wiki Link 
(IMPORTANT: AUGUST 2008 WIKI ENTRIES OR EARLIER)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Swerve256** [comment]
Should Be ok Now
