### ISSUE TITLE
Dynasandy Weakness/Stagger Trigger Causes server crash

### ISSUE THREAD

**Issue by Gotsz** [OmegaPrivateServer/issues#449]
## Summary
After getting all 5 TE Key items, I attempt to activate Weakness/stagger but the server crashes as I'm using ability/casting magic but never shows the weakness/stagger.
## Expected Behavior
Mob should trigger to increase slot drops like it does in dreamlands, instead it crashes server before it has a chance to.

## Current Behavior
potentially triggering dynamis-sandoria mobs causes server to crash

## Relevant Wiki Link 
https://ffxiclopedia.fandom.com/wiki/Weakness_Trigger

## Characters
Server

## Steps to Reproduce

1. Get all 5 Sandoria TE.
2. Attempt to stagger mob based on above link.
3.
4.

## Context
Cant farm dynamis properly for loot & relic

**Comment by Swerve256** [comment]
Next maint "should" be fixed
