### ISSUE TITLE
Buying/Using Monomi Ichi and the disappearance of it from the spell list when learned.

### ISSUE THREAD

**Issue by Nageki-noki** [OmegaPrivateServer/issues#45]
## Current Behavior

When you purchase the spell scroll Monomi ichi from the kazham merchant and learn it,you are able to cast it in zone after learning it,but if you leave the zone to go anywhere else,it disappears from your spell list as if it was never learned in the first place.I bought the scroll twice and decided to test out what would happen with this when hearing it ingame that it happened to someone else,but was not reported,so i decided to try myself.

## Possible Solution

I'm not sure if/when the patches we are on are considered in era or out of era,but the date this spell was implemented was march 11th,2008.
here is the referencing note.
https://www.bg-wiki.com/bg/Version_Update_(03/11/2008)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Implemented. Will go live with next patch.

**Comment by Nageki-noki** [comment]
Reopening since it has not been fixed
![img_20191222_102047](https://user-images.githubusercontent.com/58329644/71325690-0cbae480-24a5-11ea-99a6-ad9fbe5ceb9b.jpg)
![img_20191222_101937](https://user-images.githubusercontent.com/58329644/71325691-0e84a800-24a5-11ea-83a3-c01a4cc92ec4.jpg)

**Comment by Nageki-noki** [comment]
correction,it reappeared back in the list.working as intended! thanks!
