### ISSUE TITLE
Enveloped in Darkness

### ISSUE THREAD

**Issue by Taemin100** [OmegaPrivateServer/issues#46]
## Expected Behavior
With !OldBoots Ki and !CrawlersBlood Ki you Click ??? At i-10 in Crawlers nest and Wait 40 Secs and receive Warlock Boots after clicking again RDM AF2

## Current Behavior
Used both the KI and it prompt a trade i agreed now Gives msg : "Would like to trade Yes & ? " no Boots are givin to the player and now Both KI are gone.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Confirmed working.
