### ISSUE TITLE
NM Padfoot does not drop items

### ISSUE THREAD

**Issue by Craaizy** [OmegaPrivateServer/issues#49]
## Expected Behavior
5 padfoots spawn 1 of the 5 is guaranteed to drop either a  Assailant's Ring or Astral Earring i checked back to the farthest history on wiki and even it said the drops were gauranteed

## Current Behavior
after killing all 5 none of them drop either item.

## Steps to Reproduce

1.kill all 5 padfoots again
2.
3.
4.

**Comment by OmegaBison** [comment]
Fixed. Change will go live with the next patch.
