### ISSUE TITLE
The Emissary (windurst)

### ISSUE THREAD

**Issue by kuho23** [OmegaPrivateServer/issues#5]
upon entering the BCN the first CS freezes the whole fight can not move nor logout target or anything. Need to force shutdown (even Waiting 25mins for fight to runout does not end it)

## Expected Behavior
Should be going thru all CS's then fight then ending CS to get Key item

## Current Behavior
Freezes on opening CS

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Resolved.
