### ISSUE TITLE
Limit break 5 Thf battle

### ISSUE THREAD

**Issue by Nageki-noki** [OmegaPrivateServer/issues#51]
## Expected Behavior

the battle should end and Maat should deaggro the player

## Current Behavior

In the fight against Maat,a thf can either win the fight by defeating maat to zero hp,or by stealing the warp scroll from him.the scroll was stolen but the fight did not complete.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Confirmed broken.

**Comment by OmegaBison** [comment]
Fixed. Change will go live with the next patch.
