### ISSUE TITLE
Beastmaster's ready ability not working with maat, when his pet is alive

### ISSUE THREAD

**Issue by Fhrancih** [OmegaPrivateServer/issues#52]
I was fighting Maat today and when I tried to used Bubble Shower so my pet gets aggro, I received the following message
"You cannot attack that target, it is already claimed."
My Character's name: Fhrancis

## Expected Behavior

When Maat call his pet again, I start hitting it and use command "/pet "Bubble Shower" <me> so my pet keeps hate from the damage done by this ability.

## Current Behavior

When I use the command /pet "Bubble Shower" <me> I receive message "Cannot attack this target it is already claimed.

## Possible Solution

Since my pet was not able to keep hate off me, I died.
Since I was streaming at the time, this link shows  a clip at the start of fight.
https://clips.twitch.tv/CloudyVastCucumberCopyThis
This link is for the complete battle that starts at 1:56:47
https://www.twitch.tv/videos/525474373

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Confirmed.
