### ISSUE TITLE
Demons in Samurai AF helm fight for quest A thief in norg!? seem to have triple the hp they should

### ISSUE THREAD

**Issue by Craaizy** [OmegaPrivateServer/issues#54]
## Expected Behavior
Onki HP should equal 3000, Gaki should have 6000 and Rasetsu should have 7500

## Current Behavior
we were able to kill 1 demon will a full party Onki and after adding up all of the damage we did it equalled out to almost 9000 hp which is triple what he's supposed to have.

## Possible Solution
lower their hp values

## Steps to Reproduce

1.go fight the NMs again in god mode and tally up the dmg
2.
3.
4.

## Context
cannot finish AF quests and receive gear

**Comment by OmegaBison** [comment]
Where did you get those HP values from?

**Comment by OmegaBison** [comment]
Found it here: https://ffxiclopedia.fandom.com/wiki/A_Thief_in_Norg!%3F

Fixed. Changes will go live with the next patch.
