### ISSUE TITLE
Mousse replaced with lv 95 mob (Panna Cotta)

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#55]
In Bostaunieux Oubliette zone Mousse mobs have been replaced with Panna Cotta  a lv 96-97 mob
## Expected Behavior

Mousse should be at H-11 & i-ll in zone
## Possible Solution

replace Panna Cotta with appropriate lv mobs to spawn Sewer Syrup NM
## Steps to Reproduce

1. http://ffxi.somepage.com/mobdb/63
2. https://ffxiclopedia.fandom.com/wiki/Sewer_Syrup
3.
4.

## Context

Trying to pop Sewer Syrup NM and can't kill lv 95 mobs

## Possible Implementation

either replace mobs or lower lv of the current mobs and double check they can pop Sewer Syrup

**Comment by dvalderrama89** [comment]
I confirmed on the test server that the placeholder does not match the 2008 spec according to [this entry in the wiki](https://ffxiclopedia.fandom.com/wiki/Sewer_Syrup?oldid=645496).

**Comment by OogaBooga1316** [comment]
Is it possible to just put the NM on a timed spawn instead of changing the PHs?

**Comment by dvalderrama89** [comment]
@OogaBooga1316 it's still possible to pop the NM from an alternate mob group, I'll message you in game.

**Comment by OmegaBison** [comment]
@reddituser7777 Is the changeset that we discussed on Discord the correct implementation for 2008 era?

**Comment by dvalderrama89** [comment]
Yes, I believe that's the correct implementation, however I think on our end we also need to modify `sql/mob_groups.sql` and `sql/mob_spawn_points.sql` to remove the Panna Cotta spawns.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
