### ISSUE TITLE
NPC Taza does not sell any items

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#58]
Taza is supposed to have spells that Hasim and Susu do not.
## Expected Behavior

She should carry the spells in the list here https://ffxiclopedia.fandom.com/wiki/Taza?oldid=537769
## Current Behavior

Currently she sells nothing

## Steps to Reproduce

1. Go to Lower Jeuno at H-9 and speak to Taza

## Context

Currently Taza is the only npc which we can obtain shellra from.

**Comment by OmegaBison** [comment]
Fixed. Will go live with the next patch.
