### ISSUE TITLE
NMs not 2 houring

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#59]
## Summary

Boreal Tiger- MIghty strikes
Boreal Coeurl- Perfect Dodge
Boreal Hound - Blood Weapon

## Expected Behavior

did not use 2 hour
## Steps to Reproduce

1.https://ffxiclopedia.fandom.com/wiki/Atop_the_Highest_Mountains
2.
3.
4.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
