### ISSUE TITLE
Maat not 2 houring

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#60]
## Summary

Maat did not 2 hour on thief fight nor paladin fight
## Expected Behavior

Should use job specific 2 hour
## Steps to Reproduce

1. https://www.youtube.com/watch?v=Q-F_9NnOB1o
2.  @5:09 Maat 2 hours
3. This video is from 2007
4.

**Comment by OmegaBison** [comment]
Already fixed in staging environment. Hasn't been pushed live yet.
