### ISSUE TITLE
Quu Domi the Gallant and Mee Deggi the Punisher 2hrs happen multiple times

### ISSUE THREAD

**Issue by Pieplate** [OmegaPrivateServer/issues#63]
## Summary

2hrs happen multiple times
## Expected Behavior

Should only happen once a fight
## Current Behavior

Nm's will 2hr multiple times
## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
