### ISSUE TITLE
Chocoboleech drop rate not 100% for Gassan

### ISSUE THREAD

**Issue by xammy0** [OmegaPrivateServer/issues#64]
## Summary

Chocoboleech is not dropping Gassan 100% of the time.

## Expected Behavior

Oldest Wikis show that it should be 100% drop rate

## Current Behavior

Players are reporting not receiving Gassan after defeating Chocoboleech

## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/Chocoboleech?oldid=57437

## Possible Solution & Detailed Description

Set drop rate for Gassan to 100%.

## Characters

On Xammy I am 1/1 on it, but other players stated they have not received the drop upon killing.

## Steps to Reproduce

1. Pop Chocoboleech with Fresh Blood
2. Kill
3. ????
4. Not 100% drop rate on Gassan

**Comment by OmegaBison** [comment]
I can't reproduce this issue. Just killed Chocoboleech several times and got Gassan every time.
