### ISSUE TITLE
Avatar continue attacking after  caster's death

### ISSUE THREAD

**Issue by Shukinen** [OmegaPrivateServer/issues#66]
## Summary
 while both the smn and the avatar were engaged and in a party, the player got killed and carbuncle kept attacking the ennemy

## Expected Behavior
carbuncle should disapear on death of the smn

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Does this happen every time or only sometimes?

**Comment by Shukinen** [comment]
i will try to redo the event tomorow and clip it

**Comment by Shukinen** [comment]
Di it again solo and it still does it

https://youtu.be/SzoCMASgNek

**Comment by Sjshovan** [comment]
My solution for this ticket is below.
**Please have a look at the README within for more information.**

[Avatar continue attacking after caster's death #66.zip](https://github.com/OmegaPrivateServer/issues/files/4295344/Avatar.continue.attacking.after.caster.s.death.66.zip)

**Comment by Sjshovan** [comment]
This issue now has a PR available
