### ISSUE TITLE
King Ranperre's Tomb Aggro Issues

### ISSUE THREAD

**Issue by Quetzaxi** [OmegaPrivateServer/issues#67]
## Steps to Reproduce

1. Walk around the tomb 
2.
3.
4.

## Context
 Died trying to do rank 1 missions for Sandy.

**Comment by OmegaBison** [comment]
"Walk around the tomb" doesn't explain anything. Need more information on current behavior vs expected behavior.

**Comment by raventn** [comment]
There is a pos where one of the Dire Bat aggro from below its DSP issue it happens in eden and Nasomi aswell only thing is remove that bat or simply make them non aggro.
