### ISSUE TITLE
Cura

### ISSUE THREAD

**Issue by Shukinen** [OmegaPrivateServer/issues#68]
## Summary
Cura spell drops, can be learned and used

## Expected Behavior
should not be implemented

## Current Behavior
Cura spell drops, can be learned and used

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Cura?oldid=858901

## Characters
Shukinen

**Comment by Shukinen** [comment]
![img_20200105_153158](https://user-images.githubusercontent.com/8355652/71785695-918f1d80-2fd0-11ea-85f9-faa1a126e867.jpg)
 
prrodf that i used it

but now it has disapeared from my spell list (i guess it did upon zoning)

**Comment by OmegaBison** [comment]
Thanks. Updated & will go live with the next patch.
