### ISSUE TITLE
Crystal drop rate/behavior.

### ISSUE THREAD

**Issue by kainff2** [OmegaPrivateServer/issues#69]
## Summary

Crystal drop rate is lower than normal and signet is not causing multiple crystals to drop in PT.
## Expected Behavior

Crystals should drop more often (though not 100%). In a PT, crystals should drop PER PERSON with signet on. I spoke with others and they believed this behavior was era as well. Though I personally am not 100% sure on that.
## Current Behavior

Crystals do drop, but at really low rates. In a PT they have a low rate and still only drop 1 per mob.

## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/Signet?oldid=392594

## Steps to Reproduce

1. Get signet
2. Kill something
3. Probably wont get crystal
4. Wish you could craft.

## Context

The low crystal drops make it harder for low levels to begin crafting or even make money. It also increases the price of the crystals we do get, scarcity and all that.

UPDATE: After a friend went to level a job from 1 without his alt, he appeared to have more normal crystal drops. Since joining the server My friend and I have rarely killed mobs without being with our alts in PT. It is quite possible the low drop rate is ONLY when in a PT. It was a small test (lv 6-10 or so) so it might have been a fluke but I figured it was relevant enough to put here.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
