### ISSUE TITLE
Rank Mission 3-3 Appointment Jeuno Bug

### ISSUE THREAD

**Issue by Hugocutt** [OmegaPrivateServer/issues#7]
rank 4is bugged but only the ending part the rest of the custscenes  are fine until the last cutscene. Npc will give the cutscene saying congrats here's rank 4 but it doesnt apply to our stats n nor does the npc give the gil reward and which as well keeps at rank 3. Also, if u click the door for the cutscene again it will redo the whole rank 4 cutscene again n again nothing. 

## Expected Behavior
 Small bug I believe as I said previously everything else other than the final cutscene for the reward works.

## Current Behavior
 Glitched caught in a loop it seems

## Possible Solution
 Let Bison work his magic to fix asap :)

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
 Cannot progress any further in rank missions

**Comment by OmegaBison** [comment]
Thank you. This is fixed and will be released with the next patch.

**Comment by OmegaBison** [comment]
As a side, note: This bug appears to only affect the San d'Oria mission line.
