### ISSUE TITLE
Garuda Prime battle,and possible mob TP gain/usage of all mobs

### ISSUE THREAD

**Issue by Nageki-noki** [OmegaPrivateServer/issues#72]
## Summary

https://www.twitch.tv/videos/534268455    1/2
https://www.twitch.tv/videos/534270241    2/2

## Current Behavior

Videos showing Garuda prime fights with immense damage/lack of dmg resistance when astral flow is used,even on the weakness day of the monster,as well as the immense Tp gain of a mob and move spam usage,on not only Garuda,but every mob in the game.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dvalderrama89** [comment]
@Nageki-noki do you have some examples for the mob TP gain? I reviewed the videos about Garuda Prime but I'd also like to have other reference points for normal mobs exhibiting the same TP issue so I can investigate.

**Comment by Nageki-noki** [comment]
At the moment,i cant name any mobs personally that i've run into other than worms quickcasting spells in the beginning zones,which is why i put it down as a possibility,if anyone else has run into something like this from a regular mob/another fight,feel free to speak up please.

**Comment by dvalderrama89** [comment]
Fixed and will go out with the next patch. Please submit a separate ticket regarding mob TP gain with additional details if it continues to be an issue.
