### ISSUE TITLE
DRG af quest Chasing Quotas

### ISSUE THREAD

**Issue by Pieplate** [OmegaPrivateServer/issues#73]
## Summary

Unable to progress DRG af gear i am getting stuck at the talk to Esca in West Ronfaure 

## Expected Behavior

Should be able to get past the CS 
## Current Behavior

Unable to get past the CS Also cannot get Coffers to drop other AF gear as well. so stuck 
## Relevant Wiki Link

https://www.bg-wiki.com/bg/Chasing_Quotas

## Characters

Pieplate

## Steps to Reproduce

1.
2.
3.
4.

## Context

I am not able to get the AF gear for DRG would like to get it all.  had top use the !stuck command to get out of the broken CS

**Comment by OmegaBison** [comment]
Fixed. Will go live with the next patch.
