### ISSUE TITLE
Entering Trial By Lightning Battlefield crashes the game server

### ISSUE THREAD

**Issue by dvalderrama89** [OmegaPrivateServer/issues#74]
## Summary

This is an existing crash from DSP that was fixed by them in this PR https://github.com/DarkstarProject/darkstar/pull/6275/commits/601a200db24e4d21d24d0da49cde59cbfcc12a3d

To all current players on the live server - please do not enter this battlefield until the issue is fixed.

## Expected Behavior

Player should be able to enter the battlefield

## Current Behavior

The server blows up

## Possible Solution & Detailed Description

I applied the fixes from the PR I linked above to my local but it did not fix the issue for me.
My memory dump stopped on the following breakpoint, suggesting that there is still a problem with the args passed for this particular quest. Please note that several other Avatar Prime fights are working and I am able to enter them without any crashes or script errors. It seems to be isolated to just the one for Ramuh.
![2020-01-15 10_09_01-lua_baseentity cpp (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/1855513/72459232-2b985800-377f-11ea-9773-46712c807964.png)

Some other details: I made sure the quest name showed up in the Other Areas log. I also made sure I had the key item in my inventory. Then, when selecting the Protocrystal I only had the Trial By Lightning quest to select from. The crash occurs before the entry CS begins.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
