### ISSUE TITLE
Shadowlord battle/group fight

### ISSUE THREAD

**Issue by Nageki-noki** [OmegaPrivateServer/issues#75]
## Current Behavior

When entering 5-2(Shadowlord fight) as a group,what is now happening is the leader of the group enters the instance and the shadowlord will pop there first,making it a solo instance,while the rest of the members are put into a seperate instance with no shadowlord.If/when the leader leaves their instance,the shadowlord will then pop into the remaining members of the party,s instance and immediately aggro them.
Also,if you wait 30minuts and time out the fight,you will win the battle,this clip i do not have since i cannot complete that portion.

https://www.twitch.tv/videos/536131279

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.

**Comment by raventn** [comment]
Fight dosent work at all atm i get stuck once try get into BC fight
