### ISSUE TITLE
True Will - Nin AF body

### ISSUE THREAD

**Issue by dalmatica** [OmegaPrivateServer/issues#76]
## Summary

???'s don't appear after defeating the 3 nms. Unable to get the KI old trick box .

## Expected Behavior

???'s should appear after last nm defeated allowing player to get KI old trick box.

## Current Behavior

Enough time waited the ???'s respawn but when clicked the nm's spawn again.
## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/True_Will?oldid=511292

## Possible Solution & Detailed Description

See if a certain mob of the three triggers the ???'s and might need to be killed last? No idea what else could cause it unless it's not in the game at all 

## Characters
 Hecatomb , assisted by chapstick, nageki , and omni.

## Steps to Reproduce

1. Kill and look for ???'s
2. We killed 1 nms via despawn method no ???
3. We killed 2 nms and let 1 despawn no ???
4. We killed all 3 nms and same result no ???'s

## Context
 move forward and get AF body.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
