### ISSUE TITLE
Monster coeurl Family "Dragon kick?? = charged whisker"

### ISSUE THREAD

**Issue by raventn** [OmegaPrivateServer/issues#77]
https://ffxiclopedia.fandom.com/wiki/Category:Coeurls

Useing very powerful moves like **"Dragoon kick basicly another word Charged Whisker"** every coeurls use it that move and its from CoP area / wotg only move. And Damage from charged whisker is very powerful exampel Master Coeurl  44 - 47 | Sanctuary of Zi'Tah can hit me for 400+ dmg as level 61 So that spell has to be nerf or removed.

**Comment by OmegaBison** [comment]
Updated Master Coeurl. Changes will go live with the next server reboot.
