### ISSUE TITLE
Gravity not slowing down mobs fast enough due increase movement speed

### ISSUE THREAD

**Issue by OogaBooga1316** [OmegaPrivateServer/issues#78]
## Summary

Noticed with gravity on a mob you still can not out run mobs. also might want to check the evasion down buff on it too when cast on enemies.
## Expected Behavior

Mages should be able to nuke/cast at max range before mob reaches 
## Relevant Wiki Link

https://www.youtube.com/watch?v=NJs2YIoDZJ8
## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.

**Comment by OogaBooga1316** [comment]
Good work, keep it up
