### ISSUE TITLE
Balloon Mob Drop item

### ISSUE THREAD

**Issue by pimpndabox** [OmegaPrivateServer/issues#79]
## Summary
Incorrect Drop item from Balloon Mob in Outer Horutoto.

## Expected Behavior
Balloon Mob in Outer Horutoto Ruins should drop Coarse Boomerang.

## Current Behavior
Balloon Mob in Outer Horutoto Ruins drops Asbestos Mitts.

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Balloon?oldid=626678

## Possible Solution & Detailed Description

Balloon Mob in Outer Horutoto Ruins should drop Coarse Boomerang and Balloon Mob in Inner Horutoto Ruins should drop Asbestos Mitts.

## Characters
Pimpndabox

## Steps to Reproduce

1. After killing 50+ Balloon mobs in Outer Horutoto Ruins, only Asbestos Mitts dropped.
2. After checking the dsp database (vanilla), Asbestos Mitts drop from Balloon Mobs in both Inner and Outer Horutoto Ruins and Neither drop the Coarse Boomerang.
3.
4.

**Comment by OmegaBison** [comment]
Updated droplist for Balloons in Outer Horutoto Ruins. Changes will go live with the next server reboot.
