### ISSUE TITLE
Quest: Exit the Gambler doesn't reward Map of King Ranperre's Tomb

### ISSUE THREAD

**Issue by xammy0** [OmegaPrivateServer/issues#8]
Completion of the quest 'Exit the Gambler' from NPC Aurege in Northern San d'Oria rewards 2000xp but doesn't reward Map of King Ranperre's Tomb.

## Expected Behavior
After speaking to Aurege to complete the quest, he should reward the player with 2000xp and a Map of King Ranperre's Tomb

## Current Behavior
Aurege in Northern San d'Oria rewards 2000xp but doesn't reward Map of King Ranperre's Tomb.

## Possible Solution
N/A

## Steps to Reproduce
1. Speak with Aurege to begin the quest. Speak with Varchet and then win against Varchet in gambling, then return to Aurege to complete the quest.

## Detailed Description
NPC Aurege needs to award Map of King Ranperre's Tomb upon completion of quest 'Exit the Gambler'
Screenshot showing the xp rewards in log, no map in Key Items > Magical Maps

![img_20191124_163042](https://user-images.githubusercontent.com/1676239/69501945-e28efa80-0ed7-11ea-8365-637315162f46.jpg)

**Comment by OmegaBison** [comment]
Hi, can you try checking your key items again after zoning?

**Comment by OmegaBison** [comment]
Just confirmed zoning does not fix the issue. There was a bug in the quest logic. This quest has been fixed and will function properly after the next patch goes live.
