### ISSUE TITLE
Nanah Mihgo THF AF

### ISSUE THREAD

**Issue by Catfightx** [OmegaPrivateServer/issues#80]
## Summary
Finishing THF AF Bonnet, did quest with another THF, he got bonnet AF, nanah migho gave me instead the quest Rock Rocketeer and since doesnt give other choices.

Decided to test the quest, did the steps, went to get the Sharp Stone and after 6 stacks of Pickaxes decided it was much than I can handle.

2 bugs here.

1 - Cannot finish THF AF
2 - cannot finish Rock Rocketeer.

## Characters
Catfight

## Steps to Reproduce

1.
2.
3.
4.

## Context
cannot finish and continue on the AF THF.

**Comment by OmegaBison** [comment]
Did you take off all of your equipment & trade the `Grapnel` to `???` for cutscene?

It looks like your character hasn't completed that part.

Please re-open this ticket if this doesn't fix the issue.

**Comment by Catfightx** [comment]
Got CS and des

Le lun. 27 janv. 2020 1 h 56 p.m., OmegaBison <notifications@github.com> a
écrit :

**Comment by Catfightx** [comment]
Got CS on tower, yes did remove all the Gear, and was able to do the all further steps. Till the last CS.
But for some reason, the grapnel remained in my inventory. And the KI wasnt showing up.

yes got to finish it, had to go see the CS again.

Question : dont remember if we could skip the first KI and get the second even if we didnt get the first.
