### ISSUE TITLE
RDM AF BOOTS

### ISSUE THREAD

**Issue by Catfightx** [OmegaPrivateServer/issues#81]
## Summary
Got Ki from Curilla, Got Blood from Chest. Went to I-10 in CN.

Got a message : you get a boots for monitor .

Waited 40+ seconds.. nothing but  getting weird messages

![image](https://user-images.githubusercontent.com/60296008/73142360-9a1cc600-405b-11ea-8821-683e7aca8cc6.png)

## Expected Behavior

Go bury the boots by clicking on the ??? at (I-10) on the bottom floor of the nest. Note that this is the northern basement (the one with the zone back to a plateau in Rolanberry Fields).

Click the ??? once more to obtain Warlock's Boots

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Enveloped_in_Darkness

## Characters
CONA

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Catfightx** [comment]
Finally came back after passing more than 3 hours and got the AF ... time wait should be verified.

**Comment by OmegaBison** [comment]
2008 era quest requires waiting until the next real-life day: https://ffxiclopedia.fandom.com/wiki/Enveloped_in_Darkness?oldid=600496

Might consider removing the time requirement for this quest.
