### ISSUE TITLE
Sanctuary of Zi'Tah Master Coeurl Special Attacks

### ISSUE THREAD

**Issue by Jeffrow419** [OmegaPrivateServer/issues#82]
## Summary

Sanctuary of Zi'Tah Master Coeurl Special Attacks
## Expected Behavior

Charged Whisker
 ##Current Behavior

Master Coeurl is using Dragon Kick name instead of Charged Whisker
## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/Category:Coeurls
## Characters

Jeffrow
## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Thanks. This has already been fixed here: https://github.com/OmegaPrivateServer/issues/issues/77
