### ISSUE TITLE
Jaggedy Eared Jack Drop Rate :

### ISSUE THREAD

**Issue by whiskeyhughes** [OmegaPrivateServer/issues#83]
## Summary
I am currently 0/46 on Jaggedy Ear Jack, just wanted to confirm that the loot pool is correct. I’ve had TH2 for all of these kills. 

## Expected Behavior
Every time I have played FFXI I have never went above 20 kills without a drop, so it just feels off. 

## Current Behavior
If things are working as intended, I’ll suck it up and keep killing, just want to double check before spending more time on it. 

## Characters
AFK

## Steps to Reproduce

1. Kill JEJ
2. Obtain Hare meat
3. Get sad about losing two hours

## Context
How has this issue affected you? I’ve gained 20 pounds and no one wants to be my friend without the proper THF gear.

**Comment by OmegaBison** [comment]
Drop table is correct. 2 characters on Omega have charm so far.

Good luck!
