### ISSUE TITLE
Fradubio NM

### ISSUE THREAD

**Issue by Fizzld** [OmegaPrivateServer/issues#84]
## Summary
I've been killing the Fraelissa for about 20 hours straight now, having no luck getting Fradubio to spawn. As well as Fradubio not spawning, Fraelissa seems to spawn at exactly 1:40 instead of between 1 - 1 1/2 hours. Have also heard from other players they have had no luck spawning him.

## Expected Behavior
Fradubio should be a lottery pop from Fraelissa, who should respawn from an hour to an hour and a half after death

## Current Behavior
Only Fraelissa is spawning and at exactly 1:40 everytime.

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Fradubio?oldid=680570

## Possible Solution & Detailed Description
https://github.com/DarkstarProject/darkstar/tree/master/scripts/zones
 	Jugner_Forest 	[client update] npc ID shifts 
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Jugner_Forest/mobs/Fraelissa.lua
if not dsp.mob.phOnDespawn(mob, ID.mob.FRADUBIO_PH, 10, math.random(75600, 86400)) then -- 21-24 hours
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Jugner_Forest/mobs/Fradubio.lua

I *think* its possible ID shifts have unlinked Fradubio and Fraelissa maybe, FRADUBIO_PH may not be correct? No idea why the timer is incorrect though.

## Characters
None

## Steps to Reproduce
1. Kill Fraelissa
2. Take nap
3. Kill Fraelissa
4. Take nap

## Context
Trying to get a Bellicose Mantle

**Comment by dvalderrama89** [comment]
@Fizzld We've identified an issue with the NM's script. I'll update here when we have a fix ready but for now I would wait to camp it.

**Comment by dvalderrama89** [comment]
Fixed. Will go out with the next patch.
