### ISSUE TITLE
Elementals in Jugner Forest

### ISSUE THREAD

**Issue by Fizzld** [OmegaPrivateServer/issues#85]
## Summary
Lightning elementals don't seem to spawn in Jugner during thunder weather

## Expected Behavior
They should spawn during weather

## Current Behavior
Checked every spot one should spawn, not a single one was up

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Jugner_Forest

https://vignette.wikia.nocookie.net/ffxi/images/2/22/JugnerForestElementals.png/revision/latest?cb=20060405185125

## Possible Solution & Detailed Description
I'm really not sure, I don't see elementals in the mob list, but I also don't see them in other places where I've killed elementals. I tried comparing the zone lua to pashhow marshlands' but I don't really know what I'm looking for.

## Characters
None

## Steps to Reproduce
1. Enter Jugner forest with Thunder weather active
2. Check relevant spawn spots
3.
4.

## Context
Was trying to farm lightning clusters. I also think Jugner thunder weather is not currently working for the Summoner Quest. I didn't check to see if water elementals spawn during rainstorms.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
