### ISSUE TITLE
seekers of adolin CS in sandy north

### ISSUE THREAD

**Issue by dakumauler** [OmegaPrivateServer/issues#87]
## Summary

zone into north sandy as a new player your given a cutscene for seekers of adolin expansion 
## Expected Behavior

out of era
## Possible Solution & Detailed Description

just need to be removed
## Characters

dakumauler
## Steps to Reproduce

1.zone into north sandy
2.triggers CS as new player
3.
4.

**Comment by Volkaru** [comment]
CS also showing up in Windurst Woods

**Comment by dakumauler** [comment]
Just enter bastock markets and it also has same CS for seekers of adolin so all 3 city states have it.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
