### ISSUE TITLE
Esuna

### ISSUE THREAD

**Issue by Shukinen** [OmegaPrivateServer/issues#88]
## Summary
Esuna dropped from goblin alchemist, and i was able to learn it/cast it until i zoned

## Expected Behavior
out of era

## Current Behavior
dropped and learnable

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Esuna?limit=500&action=history

## Possible Solution & Detailed Description
remove drop

## Characters
Shukinen

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
