### ISSUE TITLE
Goblin Fisher dropped the wrong crystal.

### ISSUE THREAD

**Issue by CalOmega** [OmegaPrivateServer/issues#89]
## Summary
Goblin fisher in East Ronfaure dropped a fire crystal instead of a lightning crystal.
![Cal_2020 02 01_100804](https://user-images.githubusercontent.com/47418706/73595214-83eb8b80-44db-11ea-9f52-5e02f8050ef8.png)

## Expected Behavior
Drop Lightning Crystal.

## Current Behavior
Drops Fire Crystal.

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Goblin_Fisher?oldid=372420

## Characters
Cal

## Steps to Reproduce
1. Defeat Goblin Fisher EP or above with Signet Active. 
2.
3.
4.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live after next server reboot.
