### ISSUE TITLE
Monster TP Regain is very high.

### ISSUE THREAD

**Issue by raventn** [OmegaPrivateServer/issues#90]
I duo with my pupetmaster with pet i noticed som seriously anoying thing on Omega server is TP regain on the monster.

They can after 3 - 4s after start battle they use TP move and they will use it more like every 3s like they gain 100%+ tp per second in this server.

For Exampel i fight T crab with my bst, bst pet + pupetmaster and pet and the monster will actully Spams ability like bubble water that does 200 dmg+

**Comment by Godlylegato** [comment]
a bunch of use new players have noticed this as well. its so bad in exp parties that even 2 healer's can't keep up. I hope this gets some serious attention. I saw a ton of flustration due to it from new players
