### ISSUE TITLE
Repose Disapearing

### ISSUE THREAD

**Issue by Shukinen** [OmegaPrivateServer/issues#91]
## Summary
Bought repose, disapear upon zoning

## Expected Behavior
should stay in spell list

## Current Behavior
spell disapear from spel list

## Characters
Shukinen

![img_20200202_015230](https://user-images.githubusercontent.com/8355652/73604464-357fd080-455f-11ea-982a-0a6ef48bed78.jpg)

**Comment by Shukinen** [comment]
the picture is from before zoning

**Comment by OmegaBison** [comment]
Fixed. Changes will go live after next server reboot.
