### ISSUE TITLE
Lumber jack

### ISSUE THREAD

**Issue by Shukinen** [OmegaPrivateServer/issues#92]
## Summary
Lumber jack not spwaning on Weeping willow's death

## Expected Behavior
as Weeping willow die, it should spwawn

## Current Behavior
Weeping willow dies and thats it

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Lumber_Jack?oldid=627445

## Characters
Shukinen

**Comment by dvalderrama89** [comment]
Fixed for the next patch.
