### ISSUE TITLE
Bluemage is very underwhelming and needs some love.

### ISSUE THREAD

**Issue by Craaizy** [OmegaPrivateServer/issues#93]
## Summary
 Bluemage is very weak against IT mobs being resisted and doing little to no damage at all. I know the blue formula has issues on DSP and is a very complicated mess to fix.

## Expected Behavior
Actually do damage and not be resisted when using acc gear and food ect.

## Current Behavior
tons of resists/failed to have any effect....very very low damage sometimes hitting for 0.

## Relevant Wiki Link

https://ffxiclopedia.fandom.com/wiki/Blue_Mage_Damage_Guide https://ffxiclopedia.fandom.com/wiki/Calculating_Blue_Magic_Damage
These may not be perfect but they should be a step in the right direction.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by dalmatica** [comment]
Also 2hr does nothing at all doesn't even put you under 2 hr effect status

**Comment by CalOmega** [comment]
I concur, blu is very underwhelming against ITs. With acc+ food, madrigal, above avg. gear, and capped blue magic skill. I hit 0s 75% of the time. Solo play against Ts and below blu feels fine.

**Comment by dvalderrama89** [comment]
Phase 1 was implemented in the last patch. Further balance adjustments are planned for patches in the future. If one spell in particular is working incorrectly or not at all please open additional tickets.
