### ISSUE TITLE
Save the children 1-3 mission

### ISSUE THREAD

**Issue by dakumauler** [OmegaPrivateServer/issues#94]
## Summary
 after entering the fight the three orcs stand still and do not engage you till you attack it well others 2 do not help they wait there turn.

## Expected Behavior

all three orcs should engage the moment you get close enough together.
## Current Behavior
 We were able to attack one at a time without the other two attacking till we attacked them.

## Possible Solution & Detailed Description
 I imagine this is base DSP code that needs to be fixed.

## Characters

Dakumauler
## Steps to Reproduce

1.Enter battle
2. Attack one target only
3. Others will not engage
4.

## Context
 just trying to help out the community.

**Comment by Swerve256** [comment]
Plan to leave it the way it is right now due to population
