### ISSUE TITLE
Evoker's Roll, wrong MP/tick

### ISSUE THREAD

**Issue by KingKugu** [OmegaPrivateServer/issues#95]
## Summary
Evoker's roll not giving the correct mp/tick

## Expected Behavior
Dice roll 1-4+9, gives 1mp/tick, 5+10 gives 3mp/tick, 6,7,8 give 2mp/tick, 11 gives 4mp/tick without SMN in party. 

## Current Behavior
Some dice rolls are giving OTHER party members 1 less mp/tick. 5+10 are giving my party members 2 mp/tick and 11 is only giving 3mp/tick.

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Evoker%27s_Roll?diff=624819&oldid=624817

## Characters
Tenchu

## Steps to Reproduce
1.Use Evoker's Roll
2.Check each roll with a party member 
3.???
4.Profit MP/tick

## Context
Just trying to get my favorite job fixed

**Comment by dalmatica** [comment]
Friendly bump. Today he was doing evokes and it was giving 0 per tick.

**Comment by OmegaBison** [comment]
Resolved. Issue was due to COR being lower level than roll recipients.
