### ISSUE TITLE
Sticky Rice: NPC in Tenshedo should sell Sticky Rice : Amalasandra. 

### ISSUE THREAD

**Issue by Jwter2** [OmegaPrivateServer/issues#97]
## Expected Behavior
 add item sticky rice

## Relevant Wiki Link

https://ffxi.allakhazam.com/db/item.html?fitem=4912
## Possible Solution & Detailed Description
 
 add item sticky rice to NPC Amalasandra. 

## Characters
 Lowrider 

## Steps to Reproduce

1.
2.
3.
4.

## Context
 make Rice Dumplings 
 please add item to make Rice Dumpling cooking recipe.

**Comment by OmegaBison** [comment]
@reddituser7777 need to talk to you about this one.

**Comment by Jwter2** [comment]
OK?

**Comment by Jwter2** [comment]
Let know your thoughts.
