### ISSUE TITLE
Warrior needs Retaliation added.

### ISSUE THREAD

**Issue by Craaizy** [OmegaPrivateServer/issues#98]
## Summary
warrior job ability retaliation needs to be unlocked for the server it came out before the august 2008 deadline.

## Relevant Wiki Link
https://ffxiclopedia.fandom.com/wiki/Retaliation?action=history

## Steps to Reproduce

1.
2.
3.
4.

**Comment by OmegaBison** [comment]
Fixed. Changes will go live with the next patch.
