### ISSUE TITLE
Please look into how hate is calculated on the server.

### ISSUE THREAD

**Issue by Craaizy** [OmegaPrivateServer/issues#99]
## Summary
There may or may not be an issue with either tanks generating hate...tanks capping out at hate too soon or other jobs producing too much hate on mobs.

## Expected Behavior
pretty obvious

## Current Behavior
currently hate seems a bit wonky...i have pulled hate off of a paladin after they have used Invincible with 1 weaponskill on sam. i have kept hate off of a ninja using voke by just auto attacking. so either the hate cap is far to low and tanks are hitting it then losing hate too fast  and dps are staying at the hate cap due to damage or tanks are just not producing enough hate. either way it needs to be looked into. i can't be a galka sam tank forever please help me.

## Characters
Chapstick - paladin hecatomb - ninja craaizy - samurai

## Steps to Reproduce

1.
2.
3.
4.

## Context
i can't do HNMS like serket with the group because i end up main tanking even if i only weapon skill and dont  auto attack. which leads to me dieing and hate bouncing around healers heal bombing me losing precious mp needed for the actual tanks...its a total mess.

**Comment by raventn** [comment]
this is not only in Omega this on all DSP server even EDEN nasomi and i have been try convice the gm that hate system is crap.

**Comment by dvalderrama89** [comment]
If it's possible for you to do so, please provide a video example with the battle log visible. This will help us determine what formulas we can potentially adjust.

**Comment by dvalderrama89** [comment]
An extensive review of how CE and VE are calculated was performed as part of the last patch. This included testing for hate cap, VE decay over time, spell damage enmity, ability enmity, normal damage enmity, enmity lost while hit, etc. Cure V and Sentinel were found to be inaccurate and adjusted. All other hate calculating formulas were analyzed and found to be correct.
